// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admins.sql

package sqlc

import (
	"context"
	"time"

	"github.com/codercollo/willcoll/backend/pkg/moneyfmt"
	"github.com/google/uuid"
)

const adminGetManager = `-- name: AdminGetManager :one
SELECT managers.id, managers.firm_name, managers.username, managers.email, managers.phone, managers.password_hash, managers.status, managers.activated_at, managers.created_at, managers.version, managers.trial_ends_at,
       -- sqlc can't infer that these LEFT JOIN columns are nullable, so a
       -- firm with no subscription yields '' and 0001-01-01; the data layer
       -- maps both back to "none".
       COALESCE(latest.status, '')::text AS subscription_status,
       COALESCE(latest.current_period_end, '0001-01-01')::date AS subscription_period_end,
       (SELECT count(*) FROM properties p
         WHERE p.tenant_id = managers.id AND p.deleted_at IS NULL)::int AS property_count,
       (SELECT count(*) FROM units u
         JOIN properties p ON p.id = u.property_id
         WHERE u.tenant_id = managers.id AND p.deleted_at IS NULL)::int AS unit_count
FROM managers
LEFT JOIN (
    SELECT DISTINCT ON (manager_id) manager_id, status, current_period_end
    FROM subscriptions
    ORDER BY manager_id, current_period_end DESC
) latest ON latest.manager_id = managers.id
WHERE managers.id = $1
`

type AdminGetManagerRow struct {
	Manager               Manager
	SubscriptionStatus    string
	SubscriptionPeriodEnd time.Time
	PropertyCount         int32
	UnitCount             int32
}

// AdminGetManager is one manager with the same oversight columns.
func (q *Queries) AdminGetManager(ctx context.Context, id uuid.UUID) (AdminGetManagerRow, error) {
	row := q.db.QueryRowContext(ctx, adminGetManager, id)
	var i AdminGetManagerRow
	err := row.Scan(
		&i.Manager.ID,
		&i.Manager.FirmName,
		&i.Manager.Username,
		&i.Manager.Email,
		&i.Manager.Phone,
		&i.Manager.PasswordHash,
		&i.Manager.Status,
		&i.Manager.ActivatedAt,
		&i.Manager.CreatedAt,
		&i.Manager.Version,
		&i.Manager.TrialEndsAt,
		&i.SubscriptionStatus,
		&i.SubscriptionPeriodEnd,
		&i.PropertyCount,
		&i.UnitCount,
	)
	return i, err
}

const adminListManagers = `-- name: AdminListManagers :many

SELECT count(*) OVER() AS total_records,
       managers.id, managers.firm_name, managers.username, managers.email, managers.phone, managers.password_hash, managers.status, managers.activated_at, managers.created_at, managers.version, managers.trial_ends_at,
       -- sqlc can't infer that these LEFT JOIN columns are nullable, so a
       -- firm with no subscription yields '' and 0001-01-01; the data layer
       -- maps both back to "none".
       COALESCE(latest.status, '')::text AS subscription_status,
       COALESCE(latest.current_period_end, '0001-01-01')::date AS subscription_period_end,
       (SELECT count(*) FROM properties p
         WHERE p.tenant_id = managers.id AND p.deleted_at IS NULL)::int AS property_count,
       (SELECT count(*) FROM units u
         JOIN properties p ON p.id = u.property_id
         WHERE u.tenant_id = managers.id AND p.deleted_at IS NULL)::int AS unit_count
FROM managers
LEFT JOIN (
    SELECT DISTINCT ON (manager_id) manager_id, status, current_period_end
    FROM subscriptions
    ORDER BY manager_id, current_period_end DESC
) latest ON latest.manager_id = managers.id
WHERE ($1::text IS NULL OR managers.status = $1::text)
ORDER BY
    CASE WHEN $2::text = 'firm_name' THEN managers.firm_name END ASC,
    CASE WHEN $2::text = '-firm_name' THEN managers.firm_name END DESC,
    CASE WHEN $2::text = 'created_at' THEN managers.created_at END ASC,
    CASE WHEN $2::text = '-created_at' THEN managers.created_at END DESC,
    managers.id ASC
LIMIT $4 OFFSET $3
`

type AdminListManagersParams struct {
	Status     *string
	Sort       string
	PageOffset int32
	PageLimit  int32
}

type AdminListManagersRow struct {
	TotalRecords          int64
	Manager               Manager
	SubscriptionStatus    string
	SubscriptionPeriodEnd time.Time
	PropertyCount         int32
	UnitCount             int32
}

// ---------------------------------------------------------------- oversight
// AdminListManagers pages every manager (firm) with its latest
// subscription (NULL when it has none) and portfolio size
// (GET /v1/admin/managers).
func (q *Queries) AdminListManagers(ctx context.Context, arg AdminListManagersParams) ([]AdminListManagersRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListManagers,
		arg.Status,
		arg.Sort,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListManagersRow{}
	for rows.Next() {
		var i AdminListManagersRow
		if err := rows.Scan(
			&i.TotalRecords,
			&i.Manager.ID,
			&i.Manager.FirmName,
			&i.Manager.Username,
			&i.Manager.Email,
			&i.Manager.Phone,
			&i.Manager.PasswordHash,
			&i.Manager.Status,
			&i.Manager.ActivatedAt,
			&i.Manager.CreatedAt,
			&i.Manager.Version,
			&i.Manager.TrialEndsAt,
			&i.SubscriptionStatus,
			&i.SubscriptionPeriodEnd,
			&i.PropertyCount,
			&i.UnitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListSubscriptions = `-- name: AdminListSubscriptions :many
SELECT count(*) OVER() AS total_records,
       subscriptions.id, subscriptions.manager_id, subscriptions.plan_id, subscriptions.status, subscriptions.current_period_start, subscriptions.current_period_end, subscriptions.payhero_channel_id, subscriptions.version,
       managers.firm_name,
       subscription_plans.name AS plan_name,
       subscription_plans.price AS plan_price,
       subscription_plans.billing_interval AS plan_billing_interval
FROM subscriptions
JOIN managers ON managers.id = subscriptions.manager_id
JOIN subscription_plans ON subscription_plans.id = subscriptions.plan_id
WHERE ($1::text IS NULL OR subscriptions.status = $1::text)
ORDER BY
    CASE WHEN $2::text = 'current_period_end' THEN subscriptions.current_period_end END ASC,
    CASE WHEN $2::text = '-current_period_end' THEN subscriptions.current_period_end END DESC,
    subscriptions.id ASC
LIMIT $4 OFFSET $3
`

type AdminListSubscriptionsParams struct {
	Status     *string
	Sort       string
	PageOffset int32
	PageLimit  int32
}

type AdminListSubscriptionsRow struct {
	TotalRecords        int64
	Subscription        Subscription
	FirmName            string
	PlanName            string
	PlanPrice           moneyfmt.Money
	PlanBillingInterval string
}

// AdminListSubscriptions pages every firm's subscriptions
// (GET /v1/admin/subscriptions), soonest-ending first by default.
func (q *Queries) AdminListSubscriptions(ctx context.Context, arg AdminListSubscriptionsParams) ([]AdminListSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListSubscriptions,
		arg.Status,
		arg.Sort,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListSubscriptionsRow{}
	for rows.Next() {
		var i AdminListSubscriptionsRow
		if err := rows.Scan(
			&i.TotalRecords,
			&i.Subscription.ID,
			&i.Subscription.ManagerID,
			&i.Subscription.PlanID,
			&i.Subscription.Status,
			&i.Subscription.CurrentPeriodStart,
			&i.Subscription.CurrentPeriodEnd,
			&i.Subscription.PayheroChannelID,
			&i.Subscription.Version,
			&i.FirmName,
			&i.PlanName,
			&i.PlanPrice,
			&i.PlanBillingInterval,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdmin = `-- name: GetAdmin :one

SELECT id, name, email, password_hash, created_at, is_singleton FROM admins
WHERE id = $1
`

// Super Admin (system-design.txt 1.1, 3.1, 4.9). Platform-level, outside
// the tenant boundary.
//
// The admin account queries (GetAdmin, GetAdminByEmail, UpsertAdmin) run on
// the API's willcoll_app pool. The oversight queries further down run ONLY
// on the willcoll_admin pool (BYPASSRLS, read-mostly — system-design.txt
// 3.7), because they read across every tenant; under willcoll_app, RLS
// would hide the tenant-scoped rows they count.
func (q *Queries) GetAdmin(ctx context.Context, id uuid.UUID) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdmin, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsSingleton,
	)
	return i, err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, name, email, password_hash, created_at, is_singleton FROM admins
WHERE email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsSingleton,
	)
	return i, err
}

const getSystemMetadata = `-- name: GetSystemMetadata :one
SELECT key, value, updated_at FROM system_metadata
WHERE key = $1
`

// GetSystemMetadata reads a platform fact recorded outside the API, e.g.
// 'last_backup' from scripts/db_backup_verify.sh (migration 000022).
func (q *Queries) GetSystemMetadata(ctx context.Context, key string) (SystemMetadatum, error) {
	row := q.db.QueryRowContext(ctx, getSystemMetadata, key)
	var i SystemMetadatum
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const upsertAdmin = `-- name: UpsertAdmin :one
INSERT INTO admins (name, email, password_hash)
VALUES ($1, $2, $3)
ON CONFLICT (is_singleton) DO UPDATE
SET name = EXCLUDED.name, email = EXCLUDED.email, password_hash = EXCLUDED.password_hash
RETURNING id, name, email, password_hash, created_at, is_singleton
`

type UpsertAdminParams struct {
	Name         string
	Email        string
	PasswordHash []byte
}

// UpsertAdmin provisions the one Super Admin from configuration at
// startup. It conflicts on is_singleton (000023), so there is only ever
// one row: a changed ADMIN_EMAIL updates it in place, keeping its id.
func (q *Queries) UpsertAdmin(ctx context.Context, arg UpsertAdminParams) (Admin, error) {
	row := q.db.QueryRowContext(ctx, upsertAdmin, arg.Name, arg.Email, arg.PasswordHash)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsSingleton,
	)
	return i, err
}
