// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_metrics.sql

package sqlc

import (
	"context"
)

const adminReviewQueueDepth = `-- name: AdminReviewQueueDepth :one

SELECT
    count(*) FILTER (WHERE status = 'unmatched')::bigint AS unmatched,
    count(*) FILTER (WHERE auto_applied_unconfirmed)::bigint AS unconfirmed
FROM payments
`

type AdminReviewQueueDepthRow struct {
	Unmatched   int64
	Unconfirmed int64
}

// Business gauges for GET /debug/vars (system-design.txt section 5). Counts
// only, across every manager, on the willcoll_admin pool (BYPASSRLS, SELECT
// only); no row, id or amount leaves the database.
// AdminReviewQueueDepth is how many payments still need a manager: those no
// unit could be found for (the number that should trend to zero as intent
// payments replace paybill ones), and those the engine placed on a guess.
func (q *Queries) AdminReviewQueueDepth(ctx context.Context) (AdminReviewQueueDepthRow, error) {
	row := q.db.QueryRowContext(ctx, adminReviewQueueDepth)
	var i AdminReviewQueueDepthRow
	err := row.Scan(&i.Unmatched, &i.Unconfirmed)
	return i, err
}
