// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_plans.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/codercollo/willcoll/backend/pkg/moneyfmt"
	"github.com/google/uuid"
)

const adminArchiveSubscriptionPlan = `-- name: AdminArchiveSubscriptionPlan :one
UPDATE subscription_plans SET archived_at = now() WHERE id = $1 AND archived_at IS NULL
RETURNING id, name, price, billing_interval, unit_cap, is_test, archived_at, pricing_type, per_unit_price, min_price, sort_order
`

// AdminArchiveSubscriptionPlan hides a plan from managers and blocks renewals
// onto it; existing subscribers keep their period, and history is untouched.
func (q *Queries) AdminArchiveSubscriptionPlan(ctx context.Context, id uuid.UUID) (SubscriptionPlan, error) {
	row := q.db.QueryRowContext(ctx, adminArchiveSubscriptionPlan, id)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.BillingInterval,
		&i.UnitCap,
		&i.IsTest,
		&i.ArchivedAt,
		&i.PricingType,
		&i.PerUnitPrice,
		&i.MinPrice,
		&i.SortOrder,
	)
	return i, err
}

const adminCreateSubscriptionPlan = `-- name: AdminCreateSubscriptionPlan :one

INSERT INTO subscription_plans (name, price, billing_interval, unit_cap, is_test, pricing_type, per_unit_price, min_price, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, price, billing_interval, unit_cap, is_test, archived_at, pricing_type, per_unit_price, min_price, sort_order
`

type AdminCreateSubscriptionPlanParams struct {
	Name            string
	Price           moneyfmt.Money
	BillingInterval string
	UnitCap         sql.NullInt32
	IsTest          bool
	PricingType     string
	PerUnitPrice    *moneyfmt.Money
	MinPrice        *moneyfmt.Money
	SortOrder       int32
}

// Subscription plan management for the Super Admin (system-design.txt 1.1,
// 3.6). subscription_plans is global (no tenant), and only the willcoll_admin
// role may write it; the API role can only read it. Plans are never deleted:
// subscriptions reference them.
func (q *Queries) AdminCreateSubscriptionPlan(ctx context.Context, arg AdminCreateSubscriptionPlanParams) (SubscriptionPlan, error) {
	row := q.db.QueryRowContext(ctx, adminCreateSubscriptionPlan,
		arg.Name,
		arg.Price,
		arg.BillingInterval,
		arg.UnitCap,
		arg.IsTest,
		arg.PricingType,
		arg.PerUnitPrice,
		arg.MinPrice,
		arg.SortOrder,
	)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.BillingInterval,
		&i.UnitCap,
		&i.IsTest,
		&i.ArchivedAt,
		&i.PricingType,
		&i.PerUnitPrice,
		&i.MinPrice,
		&i.SortOrder,
	)
	return i, err
}

const adminListSubscriptionPlans = `-- name: AdminListSubscriptionPlans :many
SELECT p.id, p.name, p.price, p.billing_interval, p.unit_cap, p.is_test, p.archived_at, p.pricing_type, p.per_unit_price, p.min_price, p.sort_order, (SELECT count(*) FROM subscriptions s WHERE s.plan_id = p.id)::bigint AS subscribers
FROM subscription_plans p
ORDER BY p.sort_order, p.price, p.name
`

type AdminListSubscriptionPlansRow struct {
	ID              uuid.UUID
	Name            string
	Price           moneyfmt.Money
	BillingInterval string
	UnitCap         sql.NullInt32
	IsTest          bool
	ArchivedAt      *time.Time
	PricingType     string
	PerUnitPrice    *moneyfmt.Money
	MinPrice        *moneyfmt.Money
	SortOrder       int32
	Subscribers     int64
}

// AdminPlanSubscriberCount is how many subscriptions use a plan, so the admin
// sees what a change affects.
func (q *Queries) AdminListSubscriptionPlans(ctx context.Context) ([]AdminListSubscriptionPlansRow, error) {
	rows, err := q.db.QueryContext(ctx, adminListSubscriptionPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListSubscriptionPlansRow{}
	for rows.Next() {
		var i AdminListSubscriptionPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.BillingInterval,
			&i.UnitCap,
			&i.IsTest,
			&i.ArchivedAt,
			&i.PricingType,
			&i.PerUnitPrice,
			&i.MinPrice,
			&i.SortOrder,
			&i.Subscribers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminRestoreSubscriptionPlan = `-- name: AdminRestoreSubscriptionPlan :one
UPDATE subscription_plans SET archived_at = NULL WHERE id = $1 AND archived_at IS NOT NULL
RETURNING id, name, price, billing_interval, unit_cap, is_test, archived_at, pricing_type, per_unit_price, min_price, sort_order
`

// AdminRestoreSubscriptionPlan un-archives a plan.
func (q *Queries) AdminRestoreSubscriptionPlan(ctx context.Context, id uuid.UUID) (SubscriptionPlan, error) {
	row := q.db.QueryRowContext(ctx, adminRestoreSubscriptionPlan, id)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.BillingInterval,
		&i.UnitCap,
		&i.IsTest,
		&i.ArchivedAt,
		&i.PricingType,
		&i.PerUnitPrice,
		&i.MinPrice,
		&i.SortOrder,
	)
	return i, err
}

const adminUpdateSubscriptionPlan = `-- name: AdminUpdateSubscriptionPlan :one
UPDATE subscription_plans
SET name = $2, price = $3, billing_interval = $4, unit_cap = $5, is_test = $6,
    pricing_type = $7, per_unit_price = $8, min_price = $9, sort_order = $10
WHERE id = $1
RETURNING id, name, price, billing_interval, unit_cap, is_test, archived_at, pricing_type, per_unit_price, min_price, sort_order
`

type AdminUpdateSubscriptionPlanParams struct {
	ID              uuid.UUID
	Name            string
	Price           moneyfmt.Money
	BillingInterval string
	UnitCap         sql.NullInt32
	IsTest          bool
	PricingType     string
	PerUnitPrice    *moneyfmt.Money
	MinPrice        *moneyfmt.Money
	SortOrder       int32
}

// AdminUpdateSubscriptionPlan changes a plan. A new price applies to invoices
// raised from then on; invoices already issued keep the amount they carry.
func (q *Queries) AdminUpdateSubscriptionPlan(ctx context.Context, arg AdminUpdateSubscriptionPlanParams) (SubscriptionPlan, error) {
	row := q.db.QueryRowContext(ctx, adminUpdateSubscriptionPlan,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.BillingInterval,
		arg.UnitCap,
		arg.IsTest,
		arg.PricingType,
		arg.PerUnitPrice,
		arg.MinPrice,
		arg.SortOrder,
	)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.BillingInterval,
		&i.UnitCap,
		&i.IsTest,
		&i.ArchivedAt,
		&i.PricingType,
		&i.PerUnitPrice,
		&i.MinPrice,
		&i.SortOrder,
	)
	return i, err
}
