// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: arrears_commitments.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createArrearsCommitment = `-- name: CreateArrearsCommitment :one
INSERT INTO arrears_commitments (tenant_id, unit_id, period, note, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at
`

type CreateArrearsCommitmentParams struct {
	TenantID  uuid.UUID
	UnitID    uuid.UUID
	Period    time.Time
	Note      string
	CreatedBy uuid.UUID
}

type CreateArrearsCommitmentRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CreateArrearsCommitment(ctx context.Context, arg CreateArrearsCommitmentParams) (CreateArrearsCommitmentRow, error) {
	row := q.db.QueryRowContext(ctx, createArrearsCommitment,
		arg.TenantID,
		arg.UnitID,
		arg.Period,
		arg.Note,
		arg.CreatedBy,
	)
	var i CreateArrearsCommitmentRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listArrearsCommitments = `-- name: ListArrearsCommitments :many

SELECT ac.unit_id, u.unit_code, ac.note, ac.created_at
FROM arrears_commitments ac
INNER JOIN units u ON u.id = ac.unit_id
WHERE ac.tenant_id = $1 AND u.property_id = $2 AND ac.period = $3
ORDER BY u.unit_code
`

type ListArrearsCommitmentsParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
	Period     time.Time
}

type ListArrearsCommitmentsRow struct {
	UnitID    uuid.UUID
	UnitCode  string
	Note      string
	CreatedAt time.Time
}

// Commitment letters: the one piece of NOTE:2 that is a manager's record
// of a real paper document, not derived from the ledger.
func (q *Queries) ListArrearsCommitments(ctx context.Context, arg ListArrearsCommitmentsParams) ([]ListArrearsCommitmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listArrearsCommitments, arg.TenantID, arg.PropertyID, arg.Period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArrearsCommitmentsRow{}
	for rows.Next() {
		var i ListArrearsCommitmentsRow
		if err := rows.Scan(
			&i.UnitID,
			&i.UnitCode,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
