// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package sqlc

import (
	"context"
	"time"

	"github.com/codercollo/willcoll/backend/pkg/moneyfmt"
	"github.com/google/uuid"
)

const activateSubscription = `-- name: ActivateSubscription :one
UPDATE subscriptions
SET status = 'active', plan_id = $3, current_period_start = $4, current_period_end = $5, version = version + 1
WHERE manager_id = $1 AND id = $2
RETURNING version
`

type ActivateSubscriptionParams struct {
	ManagerID          uuid.UUID
	ID                 uuid.UUID
	PlanID             uuid.UUID
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
}

// ActivateSubscription starts a paid period, on the plan the paid invoice
// named (a switch takes effect here, not at renewal request time).
func (q *Queries) ActivateSubscription(ctx context.Context, arg ActivateSubscriptionParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, activateSubscription,
		arg.ManagerID,
		arg.ID,
		arg.PlanID,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const countManagerUnits = `-- name: CountManagerUnits :one
SELECT count(*)::int FROM units u
JOIN properties p ON p.id = u.property_id
WHERE u.tenant_id = $1 AND p.deleted_at IS NULL
`

// CountManagerUnits is the manager's occupied+vacant unit count across their
// live properties, checked against a plan's unit_cap before a renewal.
func (q *Queries) CountManagerUnits(ctx context.Context, tenantID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countManagerUnits, tenantID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (manager_id, plan_id, status, current_period_start, current_period_end)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, manager_id, plan_id, status, current_period_start, current_period_end, payhero_channel_id, version
`

type CreateSubscriptionParams struct {
	ManagerID          uuid.UUID
	PlanID             uuid.UUID
	Status             string
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, createSubscription,
		arg.ManagerID,
		arg.PlanID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ManagerID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.PayheroChannelID,
		&i.Version,
	)
	return i, err
}

const createSubscriptionInvoice = `-- name: CreateSubscriptionInvoice :one
INSERT INTO subscription_invoices (manager_id, subscription_id, plan_id, amount, period, mpesa_receipt, status)
VALUES ($1, $2, $3, $4, $5, $6, 'pending')
RETURNING id, manager_id, subscription_id, amount, period, mpesa_receipt, status, paid_at, created_at, plan_id
`

type CreateSubscriptionInvoiceParams struct {
	ManagerID      uuid.UUID
	SubscriptionID uuid.UUID
	PlanID         uuid.UUID
	Amount         moneyfmt.Money
	Period         time.Time
	MpesaReceipt   string
}

// CreateSubscriptionInvoice opens a pending invoice. mpesa_receipt is unique
// and not yet known, so it holds a placeholder until the payment arrives.
// plan_id is the plan the manager chose for this renewal: it may differ from
// the subscription's current plan_id, and is what the webhook activates once
// the payment is confirmed.
func (q *Queries) CreateSubscriptionInvoice(ctx context.Context, arg CreateSubscriptionInvoiceParams) (SubscriptionInvoice, error) {
	row := q.db.QueryRowContext(ctx, createSubscriptionInvoice,
		arg.ManagerID,
		arg.SubscriptionID,
		arg.PlanID,
		arg.Amount,
		arg.Period,
		arg.MpesaReceipt,
	)
	var i SubscriptionInvoice
	err := row.Scan(
		&i.ID,
		&i.ManagerID,
		&i.SubscriptionID,
		&i.Amount,
		&i.Period,
		&i.MpesaReceipt,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.PlanID,
	)
	return i, err
}

const devDeleteSubscription = `-- name: DevDeleteSubscription :execrows
DELETE FROM subscriptions WHERE manager_id = $1
`

// DevDeleteSubscription removes a manager's subscription (and, by cascade,
// its invoices). Used only by cmd/devtools' dev/reset-trial, never by the API.
func (q *Queries) DevDeleteSubscription(ctx context.Context, managerID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, devDeleteSubscription, managerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getManagerBillingContact = `-- name: GetManagerBillingContact :one
SELECT id, firm_name, email, phone FROM managers WHERE id = $1
`

type GetManagerBillingContactRow struct {
	ID       uuid.UUID
	FirmName string
	Email    string
	Phone    string
}

func (q *Queries) GetManagerBillingContact(ctx context.Context, id uuid.UUID) (GetManagerBillingContactRow, error) {
	row := q.db.QueryRowContext(ctx, getManagerBillingContact, id)
	var i GetManagerBillingContactRow
	err := row.Scan(
		&i.ID,
		&i.FirmName,
		&i.Email,
		&i.Phone,
	)
	return i, err
}

const getSubscriptionByManager = `-- name: GetSubscriptionByManager :one
SELECT id, manager_id, plan_id, status, current_period_start, current_period_end, payhero_channel_id, version FROM subscriptions WHERE manager_id = $1
`

func (q *Queries) GetSubscriptionByManager(ctx context.Context, managerID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByManager, managerID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ManagerID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.PayheroChannelID,
		&i.Version,
	)
	return i, err
}

const getSubscriptionInvoice = `-- name: GetSubscriptionInvoice :one
SELECT id, manager_id, subscription_id, amount, period, mpesa_receipt, status, paid_at, created_at, plan_id FROM subscription_invoices
WHERE manager_id = $1 AND id = $2
`

type GetSubscriptionInvoiceParams struct {
	ManagerID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetSubscriptionInvoice(ctx context.Context, arg GetSubscriptionInvoiceParams) (SubscriptionInvoice, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionInvoice, arg.ManagerID, arg.ID)
	var i SubscriptionInvoice
	err := row.Scan(
		&i.ID,
		&i.ManagerID,
		&i.SubscriptionID,
		&i.Amount,
		&i.Period,
		&i.MpesaReceipt,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.PlanID,
	)
	return i, err
}

const getSubscriptionPlan = `-- name: GetSubscriptionPlan :one
SELECT id, name, price, billing_interval, unit_cap, is_test, archived_at, pricing_type, per_unit_price, min_price, sort_order FROM subscription_plans WHERE id = $1
`

func (q *Queries) GetSubscriptionPlan(ctx context.Context, id uuid.UUID) (SubscriptionPlan, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionPlan, id)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.BillingInterval,
		&i.UnitCap,
		&i.IsTest,
		&i.ArchivedAt,
		&i.PricingType,
		&i.PerUnitPrice,
		&i.MinPrice,
		&i.SortOrder,
	)
	return i, err
}

const listSubscriptionInvoices = `-- name: ListSubscriptionInvoices :many
SELECT count(*) OVER() AS total_records, subscription_invoices.id, subscription_invoices.manager_id, subscription_invoices.subscription_id, subscription_invoices.amount, subscription_invoices.period, subscription_invoices.mpesa_receipt, subscription_invoices.status, subscription_invoices.paid_at, subscription_invoices.created_at, subscription_invoices.plan_id
FROM subscription_invoices
WHERE manager_id = $1
ORDER BY created_at DESC, id ASC
LIMIT $3 OFFSET $2
`

type ListSubscriptionInvoicesParams struct {
	ManagerID  uuid.UUID
	PageOffset int32
	PageLimit  int32
}

type ListSubscriptionInvoicesRow struct {
	TotalRecords        int64
	SubscriptionInvoice SubscriptionInvoice
}

func (q *Queries) ListSubscriptionInvoices(ctx context.Context, arg ListSubscriptionInvoicesParams) ([]ListSubscriptionInvoicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionInvoices, arg.ManagerID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionInvoicesRow{}
	for rows.Next() {
		var i ListSubscriptionInvoicesRow
		if err := rows.Scan(
			&i.TotalRecords,
			&i.SubscriptionInvoice.ID,
			&i.SubscriptionInvoice.ManagerID,
			&i.SubscriptionInvoice.SubscriptionID,
			&i.SubscriptionInvoice.Amount,
			&i.SubscriptionInvoice.Period,
			&i.SubscriptionInvoice.MpesaReceipt,
			&i.SubscriptionInvoice.Status,
			&i.SubscriptionInvoice.PaidAt,
			&i.SubscriptionInvoice.CreatedAt,
			&i.SubscriptionInvoice.PlanID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionPlans = `-- name: ListSubscriptionPlans :many

SELECT id, name, price, billing_interval, unit_cap, is_test, archived_at, pricing_type, per_unit_price, min_price, sort_order FROM subscription_plans
WHERE archived_at IS NULL AND (is_test = false OR $1::bool)
ORDER BY sort_order, price, name
`

// Platform billing: a manager pays Willcoll a subscription through PayHero
// (system-design.txt 3.6, 4.8, 7b). Plans are global; subscriptions and
// their invoices are scoped to the manager (the tenant) under RLS.
// ListSubscriptionPlans is what a manager may subscribe to: archived plans
// never show, and a TEST plan (is_test) only shows when include_test is set
// (the API sets it only in development — cmd/api's source of truth, not the
// frontend).
func (q *Queries) ListSubscriptionPlans(ctx context.Context, includeTest bool) ([]SubscriptionPlan, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionPlans, includeTest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionPlan{}
	for rows.Next() {
		var i SubscriptionPlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.BillingInterval,
			&i.UnitCap,
			&i.IsTest,
			&i.ArchivedAt,
			&i.PricingType,
			&i.PerUnitPrice,
			&i.MinPrice,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubscriptionInvoiceFailed = `-- name: MarkSubscriptionInvoiceFailed :execrows
UPDATE subscription_invoices
SET status = 'failed'
WHERE manager_id = $1 AND id = $2 AND status = 'pending'
`

type MarkSubscriptionInvoiceFailedParams struct {
	ManagerID uuid.UUID
	ID        uuid.UUID
}

// MarkSubscriptionInvoiceFailed records a failed or cancelled push, leaving a
// paid invoice alone.
func (q *Queries) MarkSubscriptionInvoiceFailed(ctx context.Context, arg MarkSubscriptionInvoiceFailedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markSubscriptionInvoiceFailed, arg.ManagerID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markSubscriptionInvoicePaid = `-- name: MarkSubscriptionInvoicePaid :execrows
UPDATE subscription_invoices
SET status = 'paid', mpesa_receipt = $3, paid_at = $4
WHERE manager_id = $1 AND id = $2 AND status <> 'paid'
`

type MarkSubscriptionInvoicePaidParams struct {
	ManagerID    uuid.UUID
	ID           uuid.UUID
	MpesaReceipt string
	PaidAt       *time.Time
}

// MarkSubscriptionInvoicePaid settles a pending or failed invoice. Zero rows
// means it was already paid: a redelivered callback.
func (q *Queries) MarkSubscriptionInvoicePaid(ctx context.Context, arg MarkSubscriptionInvoicePaidParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markSubscriptionInvoicePaid,
		arg.ManagerID,
		arg.ID,
		arg.MpesaReceipt,
		arg.PaidAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resolveSubscriptionInvoice = `-- name: ResolveSubscriptionInvoice :one
SELECT id, manager_id FROM subscription_invoices WHERE id = $1
`

type ResolveSubscriptionInvoiceRow struct {
	ID        uuid.UUID
	ManagerID uuid.UUID
}

// ResolveSubscriptionInvoice is a CROSS-TENANT lookup for the subscriptions
// webhook, which arrives with only the invoice reference. Runs on the
// willcoll_admin pool (BYPASSRLS, SELECT only) and returns ids only.
func (q *Queries) ResolveSubscriptionInvoice(ctx context.Context, id uuid.UUID) (ResolveSubscriptionInvoiceRow, error) {
	row := q.db.QueryRowContext(ctx, resolveSubscriptionInvoice, id)
	var i ResolveSubscriptionInvoiceRow
	err := row.Scan(&i.ID, &i.ManagerID)
	return i, err
}
