// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: charges.sql

package sqlc

import (
	"context"
	"time"

	"github.com/codercollo/willcoll/backend/pkg/moneyfmt"
	"github.com/google/uuid"
)

const createCharge = `-- name: CreateCharge :one

INSERT INTO charges (
    tenant_id, ledger_account_id, source_type, source_id, period, amount, description, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id
`

type CreateChargeParams struct {
	TenantID        uuid.UUID
	LedgerAccountID uuid.UUID
	SourceType      string
	SourceID        *uuid.UUID
	Period          time.Time
	Amount          moneyfmt.Money
	Description     string
	CreatedBy       uuid.UUID
}

// Charges: WHAT IS OWED (system-design.txt 3.3). Append-only: INSERT and
// SELECT only. A wrong charge is corrected by a negative-amount 'manual'
// charge (storno), never an UPDATE or DELETE.
func (q *Queries) CreateCharge(ctx context.Context, arg CreateChargeParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createCharge,
		arg.TenantID,
		arg.LedgerAccountID,
		arg.SourceType,
		arg.SourceID,
		arg.Period,
		arg.Amount,
		arg.Description,
		arg.CreatedBy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
