// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: garbage.sql

package sqlc

import (
	"context"
	"time"

	"github.com/codercollo/willcoll/backend/pkg/moneyfmt"
	"github.com/google/uuid"
)

const createGarbageRun = `-- name: CreateGarbageRun :one
INSERT INTO garbage_runs (tenant_id, property_id, period, fee_snapshot, locked)
VALUES ($1, $2, $3, $4, true)
RETURNING id
`

type CreateGarbageRunParams struct {
	TenantID    uuid.UUID
	PropertyID  uuid.UUID
	Period      time.Time
	FeeSnapshot moneyfmt.Money
}

// CreateGarbageRun records the run. A second run for the same property and
// period violates garbage_runs_property_id_period_key.
func (q *Queries) CreateGarbageRun(ctx context.Context, arg CreateGarbageRunParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createGarbageRun,
		arg.TenantID,
		arg.PropertyID,
		arg.Period,
		arg.FeeSnapshot,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const garbageRunExists = `-- name: GarbageRunExists :one
SELECT EXISTS (
    SELECT 1 FROM garbage_runs
    WHERE tenant_id = $1 AND property_id = $2 AND period = $3
)
`

type GarbageRunExistsParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
	Period     time.Time
}

// GarbageRunExists tells the preview whether the period is already billed.
func (q *Queries) GarbageRunExists(ctx context.Context, arg GarbageRunExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, garbageRunExists, arg.TenantID, arg.PropertyID, arg.Period)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listGarbageInvoices = `-- name: ListGarbageInvoices :many
SELECT
    ch.ledger_account_id,
    la.unit_id,
    u.unit_code,
    COALESCE(l.tenant_name, '')::text AS tenant_name,
    gr.period,
    gr.generated_at AS bill_date,
    ch.amount AS fee,
    COALESCE((
        SELECT SUM(CASE le.direction WHEN 'DEBIT' THEN le.amount ELSE -le.amount END)
        FROM ledger_entries le
        WHERE le.ledger_account_id = la.id AND le.created_at < gr.generated_at
    ), 0)::numeric(12,2) AS prior_balance
FROM garbage_runs gr
INNER JOIN charges ch ON ch.source_type = 'garbage_run' AND ch.source_id = gr.id
INNER JOIN ledger_accounts la ON la.id = ch.ledger_account_id AND la.type = 'GARBAGE'
INNER JOIN units u ON u.id = la.unit_id
LEFT JOIN LATERAL (
    SELECT tenant_name FROM leases
    WHERE unit_id = u.id AND start_date < (gr.period + interval '1 month')
    ORDER BY start_date DESC
    LIMIT 1
) l ON true
WHERE gr.tenant_id = $1
  AND gr.property_id = $2
  AND gr.period = $3
  AND ($4::uuid IS NULL OR la.unit_id = $4::uuid)
ORDER BY u.unit_code
`

type ListGarbageInvoicesParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
	Period     time.Time
	UnitID     *uuid.UUID
}

type ListGarbageInvoicesRow struct {
	LedgerAccountID uuid.UUID
	UnitID          uuid.UUID
	UnitCode        string
	TenantName      string
	Period          time.Time
	BillDate        time.Time
	Fee             moneyfmt.Money
	PriorBalance    moneyfmt.Money
}

// ListGarbageInvoices is the data for every unit billed by the period's
// run. The fee is the charge actually posted; prior_balance is the GARBAGE
// balance before the run.
func (q *Queries) ListGarbageInvoices(ctx context.Context, arg ListGarbageInvoicesParams) ([]ListGarbageInvoicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGarbageInvoices,
		arg.TenantID,
		arg.PropertyID,
		arg.Period,
		arg.UnitID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGarbageInvoicesRow{}
	for rows.Next() {
		var i ListGarbageInvoicesRow
		if err := rows.Scan(
			&i.LedgerAccountID,
			&i.UnitID,
			&i.UnitCode,
			&i.TenantName,
			&i.Period,
			&i.BillDate,
			&i.Fee,
			&i.PriorBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGarbageUnitsForPeriod = `-- name: ListGarbageUnitsForPeriod :many

SELECT
    u.id AS unit_id,
    u.unit_code,
    COALESCE(l.tenant_name, '')::text AS tenant_name,
    COALESCE(b.balance, 0)::numeric(12,2) AS prior_balance,
    EXISTS (SELECT 1 FROM leases gl WHERE gl.unit_id = u.id AND gl.status = 'active' AND gl.garbage_billed) AS billed
FROM units u
LEFT JOIN LATERAL (
    SELECT tenant_name FROM leases
    WHERE unit_id = u.id AND status = 'active'
    LIMIT 1
) l ON true
LEFT JOIN LATERAL (
    SELECT ub.balance FROM unit_ledger_balances ub
    WHERE ub.unit_id = u.id AND ub.type = 'GARBAGE'
) b ON true
WHERE u.tenant_id = $1 AND u.property_id = $2 AND u.status = 'occupied'
ORDER BY u.unit_code
`

type ListGarbageUnitsForPeriodParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
}

type ListGarbageUnitsForPeriodRow struct {
	UnitID       uuid.UUID
	UnitCode     string
	TenantName   string
	PriorBalance moneyfmt.Money
	Billed       bool
}

// Garbage billing (system-design.txt 3.9 step 4). No per-unit input: the
// property's fixed fee is charged to every occupied unit. A garbage_runs
// row is the run itself (locked on insert); its generated_at is the moment
// an invoice's "previous balance B/F" is measured against.
// ListGarbageUnitsForPeriod is every occupied unit with its tenant, current
// GARBAGE balance, and whether its active lease has garbage billing turned
// on: the preview grid lists all of these (toggled-off units show "Not
// billed" rather than disappearing), and a run only charges the billed ones.
func (q *Queries) ListGarbageUnitsForPeriod(ctx context.Context, arg ListGarbageUnitsForPeriodParams) ([]ListGarbageUnitsForPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, listGarbageUnitsForPeriod, arg.TenantID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGarbageUnitsForPeriodRow{}
	for rows.Next() {
		var i ListGarbageUnitsForPeriodRow
		if err := rows.Scan(
			&i.UnitID,
			&i.UnitCode,
			&i.TenantName,
			&i.PriorBalance,
			&i.Billed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
