// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: landlords.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createLandlord = `-- name: CreateLandlord :one

INSERT INTO landlords (
    tenant_id, name, phone, email, bank_name, bank_account_name, bank_account_number
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, tenant_id, name, phone, email, bank_name, bank_account_name, bank_account_number, created_at, version
`

type CreateLandlordParams struct {
	TenantID          uuid.UUID
	Name              string
	Phone             string
	Email             *string
	BankName          *string
	BankAccountName   *string
	BankAccountNumber *string
}

// Landlords (system-design.txt 1.3, 3.2). Tenant-scoped under RLS; every
// query also filters on tenant_id.
func (q *Queries) CreateLandlord(ctx context.Context, arg CreateLandlordParams) (Landlord, error) {
	row := q.db.QueryRowContext(ctx, createLandlord,
		arg.TenantID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.BankName,
		arg.BankAccountName,
		arg.BankAccountNumber,
	)
	var i Landlord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.BankName,
		&i.BankAccountName,
		&i.BankAccountNumber,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const getLandlord = `-- name: GetLandlord :one
SELECT id, tenant_id, name, phone, email, bank_name, bank_account_name, bank_account_number, created_at, version FROM landlords
WHERE tenant_id = $1 AND id = $2
`

type GetLandlordParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetLandlord(ctx context.Context, arg GetLandlordParams) (Landlord, error) {
	row := q.db.QueryRowContext(ctx, getLandlord, arg.TenantID, arg.ID)
	var i Landlord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.BankName,
		&i.BankAccountName,
		&i.BankAccountNumber,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const listLandlords = `-- name: ListLandlords :many
SELECT count(*) OVER() AS total_records, landlords.id, landlords.tenant_id, landlords.name, landlords.phone, landlords.email, landlords.bank_name, landlords.bank_account_name, landlords.bank_account_number, landlords.created_at, landlords.version
FROM landlords
WHERE tenant_id = $1
ORDER BY
    CASE WHEN $2::text = 'name' THEN name END ASC,
    CASE WHEN $2::text = '-name' THEN name END DESC,
    CASE WHEN $2::text = 'created_at' THEN created_at END ASC,
    CASE WHEN $2::text = '-created_at' THEN created_at END DESC,
    id ASC
LIMIT $4 OFFSET $3
`

type ListLandlordsParams struct {
	TenantID   uuid.UUID
	Sort       string
	PageOffset int32
	PageLimit  int32
}

type ListLandlordsRow struct {
	TotalRecords int64
	Landlord     Landlord
}

// ListLandlords pages a tenant's landlords. The sort key comes from the
// handler's safelist (see ListProperties for the CASE-ordering idiom).
func (q *Queries) ListLandlords(ctx context.Context, arg ListLandlordsParams) ([]ListLandlordsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLandlords,
		arg.TenantID,
		arg.Sort,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLandlordsRow{}
	for rows.Next() {
		var i ListLandlordsRow
		if err := rows.Scan(
			&i.TotalRecords,
			&i.Landlord.ID,
			&i.Landlord.TenantID,
			&i.Landlord.Name,
			&i.Landlord.Phone,
			&i.Landlord.Email,
			&i.Landlord.BankName,
			&i.Landlord.BankAccountName,
			&i.Landlord.BankAccountNumber,
			&i.Landlord.CreatedAt,
			&i.Landlord.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLandlord = `-- name: UpdateLandlord :one
UPDATE landlords
SET name = $1,
    phone = $2,
    email = $3,
    bank_name = $4,
    bank_account_name = $5,
    bank_account_number = $6,
    version = version + 1
WHERE tenant_id = $7 AND id = $8 AND version = $9
RETURNING version
`

type UpdateLandlordParams struct {
	Name              string
	Phone             string
	Email             *string
	BankName          *string
	BankAccountName   *string
	BankAccountNumber *string
	TenantID          uuid.UUID
	ID                uuid.UUID
	Version           int32
}

// UpdateLandlord: optimistic concurrency; zero rows means the version moved on.
func (q *Queries) UpdateLandlord(ctx context.Context, arg UpdateLandlordParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, updateLandlord,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.BankName,
		arg.BankAccountName,
		arg.BankAccountNumber,
		arg.TenantID,
		arg.ID,
		arg.Version,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}
