// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leases.sql

package sqlc

import (
	"context"
	"time"

	"github.com/codercollo/willcoll/backend/pkg/moneyfmt"
	"github.com/google/uuid"
)

const createLease = `-- name: CreateLease :one

INSERT INTO leases (
    tenant_id, unit_id, tenant_name, primary_phone, rent_amount,
    rent_deposit_amount, water_deposit_amount, electricity_deposit_amount,
    start_date, end_date, status, garbage_billed
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12
)
RETURNING id, tenant_id, unit_id, tenant_name, primary_phone, rent_amount, rent_deposit_amount, water_deposit_amount, start_date, end_date, status, created_at, version, garbage_billed, electricity_deposit_amount
`

type CreateLeaseParams struct {
	TenantID                 uuid.UUID
	UnitID                   uuid.UUID
	TenantName               string
	PrimaryPhone             string
	RentAmount               moneyfmt.Money
	RentDepositAmount        moneyfmt.Money
	WaterDepositAmount       moneyfmt.Money
	ElectricityDepositAmount moneyfmt.Money
	StartDate                time.Time
	EndDate                  *time.Time
	Status                   string
	GarbageBilled            bool
}

// Leases (system-design.txt 3.2, 3.2.1). Tenant-scoped under RLS. The
// LEASE_START deposit posting runs in the same transaction as CreateLease;
// see data.LeaseModel.Insert and ADR 0002.
func (q *Queries) CreateLease(ctx context.Context, arg CreateLeaseParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, createLease,
		arg.TenantID,
		arg.UnitID,
		arg.TenantName,
		arg.PrimaryPhone,
		arg.RentAmount,
		arg.RentDepositAmount,
		arg.WaterDepositAmount,
		arg.ElectricityDepositAmount,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.GarbageBilled,
	)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnitID,
		&i.TenantName,
		&i.PrimaryPhone,
		&i.RentAmount,
		&i.RentDepositAmount,
		&i.WaterDepositAmount,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.Version,
		&i.GarbageBilled,
		&i.ElectricityDepositAmount,
	)
	return i, err
}

const getLease = `-- name: GetLease :one
SELECT id, tenant_id, unit_id, tenant_name, primary_phone, rent_amount, rent_deposit_amount, water_deposit_amount, start_date, end_date, status, created_at, version, garbage_billed, electricity_deposit_amount FROM leases
WHERE tenant_id = $1 AND id = $2
`

type GetLeaseParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetLease(ctx context.Context, arg GetLeaseParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, getLease, arg.TenantID, arg.ID)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnitID,
		&i.TenantName,
		&i.PrimaryPhone,
		&i.RentAmount,
		&i.RentDepositAmount,
		&i.WaterDepositAmount,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.Version,
		&i.GarbageBilled,
		&i.ElectricityDepositAmount,
	)
	return i, err
}

const listActiveLeasesWithoutElectricityDeposit = `-- name: ListActiveLeasesWithoutElectricityDeposit :many
SELECT l.id, l.tenant_id, l.unit_id, l.tenant_name, l.primary_phone, l.rent_amount, l.rent_deposit_amount, l.water_deposit_amount, l.start_date, l.end_date, l.status, l.created_at, l.version, l.garbage_billed, l.electricity_deposit_amount FROM leases l
INNER JOIN units u ON u.id = l.unit_id
WHERE l.tenant_id = $1 AND u.property_id = $2
  AND l.status = 'active' AND l.electricity_deposit_amount = 0
ORDER BY u.unit_code
`

type ListActiveLeasesWithoutElectricityDepositParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
}

// ListActiveLeasesWithoutElectricityDeposit is every active lease on the
// property that has never had an electricity deposit charged (amount still
// zero — the same invariant the lease-start charge loop uses: zero means
// "nothing to charge," never "waived after being charged"). Used to
// retroactively charge existing leases the one time electricity_enabled
// flips on for the property.
func (q *Queries) ListActiveLeasesWithoutElectricityDeposit(ctx context.Context, arg ListActiveLeasesWithoutElectricityDepositParams) ([]Lease, error) {
	rows, err := q.db.QueryContext(ctx, listActiveLeasesWithoutElectricityDeposit, arg.TenantID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lease{}
	for rows.Next() {
		var i Lease
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UnitID,
			&i.TenantName,
			&i.PrimaryPhone,
			&i.RentAmount,
			&i.RentDepositAmount,
			&i.WaterDepositAmount,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.CreatedAt,
			&i.Version,
			&i.GarbageBilled,
			&i.ElectricityDepositAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLeaseElectricityDeposit = `-- name: SetLeaseElectricityDeposit :exec
UPDATE leases SET electricity_deposit_amount = $1, version = version + 1
WHERE tenant_id = $2 AND id = $3
`

type SetLeaseElectricityDepositParams struct {
	ElectricityDepositAmount moneyfmt.Money
	TenantID                 uuid.UUID
	ID                       uuid.UUID
}

// SetLeaseElectricityDeposit records the amount an existing lease was
// retroactively charged for its electricity deposit, in the same
// transaction as the charge itself (EnableElectricityDeposit). Not part of
// UpdateLease: like the other deposits, this is a one-time posting, not an
// ordinary edit.
func (q *Queries) SetLeaseElectricityDeposit(ctx context.Context, arg SetLeaseElectricityDepositParams) error {
	_, err := q.db.ExecContext(ctx, setLeaseElectricityDeposit, arg.ElectricityDepositAmount, arg.TenantID, arg.ID)
	return err
}

const updateLease = `-- name: UpdateLease :one
UPDATE leases
SET tenant_name = $1,
    primary_phone = $2,
    rent_amount = $3,
    end_date = $4,
    status = $5,
    garbage_billed = $6,
    version = version + 1
WHERE tenant_id = $7 AND id = $8 AND version = $9
RETURNING version
`

type UpdateLeaseParams struct {
	TenantName    string
	PrimaryPhone  string
	RentAmount    moneyfmt.Money
	EndDate       *time.Time
	Status        string
	GarbageBilled bool
	TenantID      uuid.UUID
	ID            uuid.UUID
	Version       int32
}

// UpdateLease covers edits and termination. Deposits and start_date are
// deliberately not updatable: they were posted to the ledger at lease
// start, and changing them is a storno adjustment, not an edit.
func (q *Queries) UpdateLease(ctx context.Context, arg UpdateLeaseParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, updateLease,
		arg.TenantName,
		arg.PrimaryPhone,
		arg.RentAmount,
		arg.EndDate,
		arg.Status,
		arg.GarbageBilled,
		arg.TenantID,
		arg.ID,
		arg.Version,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}
