// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lease_payers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createLeasePayer = `-- name: CreateLeasePayer :one

INSERT INTO lease_payers (tenant_id, lease_id, name, phone)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, lease_id, name, phone
`

type CreateLeasePayerParams struct {
	TenantID uuid.UUID
	LeaseID  uuid.UUID
	Name     string
	Phone    *string
}

// Lease co-payers (system-design.txt 2, 1.4): the other people allowed to pay
// for a unit, the "OR" names on the payments schedule. Their phones can also
// request the pay-page one-time code and identify organic paybill payments.
// Tenant-scoped under RLS. Not ledger tables, so rows may be removed.
// CreateLeasePayer adds a co-payer to a lease.
func (q *Queries) CreateLeasePayer(ctx context.Context, arg CreateLeasePayerParams) (LeasePayer, error) {
	row := q.db.QueryRowContext(ctx, createLeasePayer,
		arg.TenantID,
		arg.LeaseID,
		arg.Name,
		arg.Phone,
	)
	var i LeasePayer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LeaseID,
		&i.Name,
		&i.Phone,
	)
	return i, err
}

const deleteLeasePayer = `-- name: DeleteLeasePayer :execrows
DELETE FROM lease_payers
WHERE tenant_id = $1 AND lease_id = $2 AND id = $3
`

type DeleteLeasePayerParams struct {
	TenantID uuid.UUID
	LeaseID  uuid.UUID
	ID       uuid.UUID
}

// DeleteLeasePayer removes a co-payer. Zero rows means it is not on that lease.
func (q *Queries) DeleteLeasePayer(ctx context.Context, arg DeleteLeasePayerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLeasePayer, arg.TenantID, arg.LeaseID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listLeasePayers = `-- name: ListLeasePayers :many
SELECT id, tenant_id, lease_id, name, phone FROM lease_payers
WHERE tenant_id = $1 AND lease_id = $2
ORDER BY name, id
`

type ListLeasePayersParams struct {
	TenantID uuid.UUID
	LeaseID  uuid.UUID
}

func (q *Queries) ListLeasePayers(ctx context.Context, arg ListLeasePayersParams) ([]LeasePayer, error) {
	rows, err := q.db.QueryContext(ctx, listLeasePayers, arg.TenantID, arg.LeaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeasePayer{}
	for rows.Next() {
		var i LeasePayer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LeaseID,
			&i.Name,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeasesForUnit = `-- name: ListLeasesForUnit :many
SELECT id, tenant_id, unit_id, tenant_name, primary_phone, rent_amount, rent_deposit_amount, water_deposit_amount, start_date, end_date, status, created_at, version, garbage_billed, electricity_deposit_amount FROM leases
WHERE tenant_id = $1 AND unit_id = $2
ORDER BY start_date DESC, created_at DESC
`

type ListLeasesForUnitParams struct {
	TenantID uuid.UUID
	UnitID   uuid.UUID
}

// ListLeasesForUnit is a unit's lease history, newest first: the active lease
// (at most one) and every terminated one.
func (q *Queries) ListLeasesForUnit(ctx context.Context, arg ListLeasesForUnitParams) ([]Lease, error) {
	rows, err := q.db.QueryContext(ctx, listLeasesForUnit, arg.TenantID, arg.UnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lease{}
	for rows.Next() {
		var i Lease
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UnitID,
			&i.TenantName,
			&i.PrimaryPhone,
			&i.RentAmount,
			&i.RentDepositAmount,
			&i.WaterDepositAmount,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.CreatedAt,
			&i.Version,
			&i.GarbageBilled,
			&i.ElectricityDepositAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
