// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger_view.sql

package sqlc

import (
	"context"
	"time"

	"github.com/codercollo/willcoll/backend/pkg/moneyfmt"
	"github.com/google/uuid"
)

const createPaymentAllocation = `-- name: CreatePaymentAllocation :exec
INSERT INTO payment_allocations (id, tenant_id, payment_id, ledger_account_id, ledger_entry_id, amount)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreatePaymentAllocationParams struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	PaymentID       uuid.UUID
	LedgerAccountID uuid.UUID
	LedgerEntryID   uuid.UUID
	Amount          moneyfmt.Money
}

// CreatePaymentAllocation links a payment to the ledger entry that credited
// it. The caller picks the id up front because the credit entry reference_id
// must point back at this row: entry first, then this row. INSERT only.
func (q *Queries) CreatePaymentAllocation(ctx context.Context, arg CreatePaymentAllocationParams) error {
	_, err := q.db.ExecContext(ctx, createPaymentAllocation,
		arg.ID,
		arg.TenantID,
		arg.PaymentID,
		arg.LedgerAccountID,
		arg.LedgerEntryID,
		arg.Amount,
	)
	return err
}

const getLedgerEntryForReversal = `-- name: GetLedgerEntryForReversal :one
SELECT
    le.id, le.ledger_account_id, le.direction, le.amount, le.reference_type, le.reference_id,
    la.unit_id, la.type AS ledger_type,
    EXISTS (
        SELECT 1 FROM ledger_entries r
        WHERE r.reference_type = 'reversal' AND r.reference_id = le.id
    ) AS reversed
FROM ledger_entries le
INNER JOIN ledger_accounts la ON la.id = le.ledger_account_id
WHERE le.tenant_id = $1 AND le.id = $2
`

type GetLedgerEntryForReversalParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetLedgerEntryForReversalRow struct {
	ID              uuid.UUID
	LedgerAccountID uuid.UUID
	Direction       string
	Amount          moneyfmt.Money
	ReferenceType   string
	ReferenceID     uuid.UUID
	UnitID          uuid.UUID
	LedgerType      string
	Reversed        bool
}

// GetLedgerEntryForReversal loads an entry with its account, tenant-scoped,
// and whether it has already been reversed.
func (q *Queries) GetLedgerEntryForReversal(ctx context.Context, arg GetLedgerEntryForReversalParams) (GetLedgerEntryForReversalRow, error) {
	row := q.db.QueryRowContext(ctx, getLedgerEntryForReversal, arg.TenantID, arg.ID)
	var i GetLedgerEntryForReversalRow
	err := row.Scan(
		&i.ID,
		&i.LedgerAccountID,
		&i.Direction,
		&i.Amount,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.UnitID,
		&i.LedgerType,
		&i.Reversed,
	)
	return i, err
}

const getManualPaymentByReference = `-- name: GetManualPaymentByReference :one
SELECT id FROM payments
WHERE tenant_id = $1 AND source = 'manual' AND account_reference = $2
`

type GetManualPaymentByReferenceParams struct {
	TenantID         uuid.UUID
	AccountReference *string
}

// GetManualPaymentByReference finds an earlier hand-entered payment with the
// same reference, so a double submit is refused instead of credited twice.
func (q *Queries) GetManualPaymentByReference(ctx context.Context, arg GetManualPaymentByReferenceParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getManualPaymentByReference, arg.TenantID, arg.AccountReference)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listLedgerEntriesWithBalance = `-- name: ListLedgerEntriesWithBalance :many

WITH entries AS (
    SELECT
        le.id, le.transaction_header_id, le.ledger_account_id, le.direction, le.amount,
        le.reference_type, le.reference_id, le.created_at,
        h.type AS transaction_type,
        h.description,
        SUM(CASE le.direction WHEN 'DEBIT' THEN le.amount ELSE -le.amount END)
            OVER (ORDER BY le.created_at, le.id)::numeric(12,2) AS running_balance,
        EXISTS (
            SELECT 1 FROM ledger_entries r
            WHERE r.reference_type = 'reversal' AND r.reference_id = le.id
        ) AS reversed
    FROM ledger_entries le
    INNER JOIN ledger_accounts la ON la.id = le.ledger_account_id
    INNER JOIN transaction_headers h ON h.id = le.transaction_header_id
    WHERE le.tenant_id = $4 AND la.unit_id = $5 AND la.type = $6
)
SELECT count(*) OVER() AS total_records, entries.id, entries.transaction_header_id, entries.ledger_account_id, entries.direction, entries.amount, entries.reference_type, entries.reference_id, entries.created_at, entries.transaction_type, entries.description, entries.running_balance, entries.reversed
FROM entries
ORDER BY
    CASE WHEN $1::text = 'created_at' THEN entries.created_at END ASC,
    CASE WHEN $1::text = '-created_at' THEN entries.created_at END DESC,
    entries.id ASC
LIMIT $3 OFFSET $2
`

type ListLedgerEntriesWithBalanceParams struct {
	Sort       string
	PageOffset int32
	PageLimit  int32
	TenantID   uuid.UUID
	UnitID     uuid.UUID
	LedgerType string
}

type ListLedgerEntriesWithBalanceRow struct {
	TotalRecords        int64
	ID                  uuid.UUID
	TransactionHeaderID uuid.UUID
	LedgerAccountID     uuid.UUID
	Direction           string
	Amount              moneyfmt.Money
	ReferenceType       string
	ReferenceID         uuid.UUID
	CreatedAt           time.Time
	TransactionType     string
	Description         string
	RunningBalance      moneyfmt.Money
	Reversed            bool
}

// Read side of the append-only ledger, plus what a reversal (storno) and a
// payment posting need. INSERT and SELECT only on the ledger tables; see
// ledger_entries.sql for the writes and data.TestAppendOnlyQueries.
// ListLedgerEntriesWithBalance pages one unit ledger for display: each entry
// with the running balance after it (over the whole ledger, oldest first),
// its transaction type and description (a reversal reason lives there), and
// whether a later reversal has cancelled it. Newest first unless
// sort = 'created_at'.
func (q *Queries) ListLedgerEntriesWithBalance(ctx context.Context, arg ListLedgerEntriesWithBalanceParams) ([]ListLedgerEntriesWithBalanceRow, error) {
	rows, err := q.db.QueryContext(ctx, listLedgerEntriesWithBalance,
		arg.Sort,
		arg.PageOffset,
		arg.PageLimit,
		arg.TenantID,
		arg.UnitID,
		arg.LedgerType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLedgerEntriesWithBalanceRow{}
	for rows.Next() {
		var i ListLedgerEntriesWithBalanceRow
		if err := rows.Scan(
			&i.TotalRecords,
			&i.ID,
			&i.TransactionHeaderID,
			&i.LedgerAccountID,
			&i.Direction,
			&i.Amount,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.CreatedAt,
			&i.TransactionType,
			&i.Description,
			&i.RunningBalance,
			&i.Reversed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPaymentMatch = `-- name: SetPaymentMatch :exec
UPDATE payments
SET status = $1,
    matched_unit_id = $2,
    matched_intent_id = $3,
    auto_applied_unconfirmed = $4,
    review_note = $5
WHERE tenant_id = $6 AND id = $7
`

type SetPaymentMatchParams struct {
	Status                 string
	MatchedUnitID          *uuid.UUID
	MatchedIntentID        *uuid.UUID
	AutoAppliedUnconfirmed bool
	ReviewNote             *string
	TenantID               uuid.UUID
	ID                     uuid.UUID
}

// SetPaymentMatch records where a payment landed: its status, unit and
// intent, whether the engine applied it on a guess a manager should confirm,
// and a note saying why it needs review.
func (q *Queries) SetPaymentMatch(ctx context.Context, arg SetPaymentMatchParams) error {
	_, err := q.db.ExecContext(ctx, setPaymentMatch,
		arg.Status,
		arg.MatchedUnitID,
		arg.MatchedIntentID,
		arg.AutoAppliedUnconfirmed,
		arg.ReviewNote,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const sumPaymentAllocations = `-- name: SumPaymentAllocations :one
SELECT COALESCE(SUM(amount), 0)::numeric(12,2) AS allocated
FROM payment_allocations
WHERE tenant_id = $1 AND payment_id = $2
`

type SumPaymentAllocationsParams struct {
	TenantID  uuid.UUID
	PaymentID uuid.UUID
}

// SumPaymentAllocations backs the zero-sum assertion (system-design.txt
// 3.8): what has been allocated from one payment so far.
func (q *Queries) SumPaymentAllocations(ctx context.Context, arg SumPaymentAllocationsParams) (moneyfmt.Money, error) {
	row := q.db.QueryRowContext(ctx, sumPaymentAllocations, arg.TenantID, arg.PaymentID)
	var allocated moneyfmt.Money
	err := row.Scan(&allocated)
	return allocated, err
}
