// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger_entries.sql

package sqlc

import (
	"context"
	"time"

	"github.com/codercollo/willcoll/backend/pkg/moneyfmt"
	"github.com/google/uuid"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entries (
    tenant_id, transaction_header_id, ledger_account_id, direction, amount, reference_type, reference_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id
`

type CreateLedgerEntryParams struct {
	TenantID            uuid.UUID
	TransactionHeaderID uuid.UUID
	LedgerAccountID     uuid.UUID
	Direction           string
	Amount              moneyfmt.Money
	ReferenceType       string
	ReferenceID         uuid.UUID
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createLedgerEntry,
		arg.TenantID,
		arg.TransactionHeaderID,
		arg.LedgerAccountID,
		arg.Direction,
		arg.Amount,
		arg.ReferenceType,
		arg.ReferenceID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createTransactionHeader = `-- name: CreateTransactionHeader :one
INSERT INTO transaction_headers (tenant_id, type, idempotency_key, description, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateTransactionHeaderParams struct {
	TenantID       uuid.UUID
	Type           string
	IdempotencyKey string
	Description    string
	CreatedBy      string
}

func (q *Queries) CreateTransactionHeader(ctx context.Context, arg CreateTransactionHeaderParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createTransactionHeader,
		arg.TenantID,
		arg.Type,
		arg.IdempotencyKey,
		arg.Description,
		arg.CreatedBy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getOrCreateLedgerAccount = `-- name: GetOrCreateLedgerAccount :one

INSERT INTO ledger_accounts (tenant_id, unit_id, type)
VALUES ($1, $2, $3)
ON CONFLICT (unit_id, type) DO UPDATE SET type = EXCLUDED.type
RETURNING id
`

type GetOrCreateLedgerAccountParams struct {
	TenantID uuid.UUID
	UnitID   uuid.UUID
	Type     string
}

// The append-only ledger core (system-design.txt 3.3/3.4, ADR 0002).
// transaction_headers and ledger_entries are INSERT and SELECT only: there
// is deliberately no UPDATE or DELETE query here, the API role has no such
// privilege (000018/000019), and data.TestAppendOnlyQueries fails if one
// is ever added. Corrections are storno reversals.
// GetOrCreateLedgerAccount returns the unit's anchor account of the given
// type, creating it on first use. (ledger_accounts is not append-only; the
// no-op DO UPDATE just makes RETURNING yield the existing row's id.)
func (q *Queries) GetOrCreateLedgerAccount(ctx context.Context, arg GetOrCreateLedgerAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateLedgerAccount, arg.TenantID, arg.UnitID, arg.Type)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUnitLedgerBalance = `-- name: GetUnitLedgerBalance :one
SELECT COALESCE((
    SELECT b.balance
    FROM unit_ledger_balances b
    INNER JOIN units u ON u.id = b.unit_id
    WHERE u.tenant_id = $1 AND b.unit_id = $2 AND b.type = $3::text
), 0)::numeric(12,2) AS balance
`

type GetUnitLedgerBalanceParams struct {
	TenantID   uuid.UUID
	UnitID     uuid.UUID
	LedgerType string
}

// GetUnitLedgerBalance reads the derived balance (never a stored column).
// The view is security_invoker (000020), so RLS applies through it; the
// units join adds the explicit tenant filter.
func (q *Queries) GetUnitLedgerBalance(ctx context.Context, arg GetUnitLedgerBalanceParams) (moneyfmt.Money, error) {
	row := q.db.QueryRowContext(ctx, getUnitLedgerBalance, arg.TenantID, arg.UnitID, arg.LedgerType)
	var balance moneyfmt.Money
	err := row.Scan(&balance)
	return balance, err
}

const getUnitLedgerBalanceAsOf = `-- name: GetUnitLedgerBalanceAsOf :one
SELECT COALESCE((
    SELECT SUM(CASE le.direction WHEN 'DEBIT' THEN le.amount ELSE -le.amount END)
    FROM ledger_entries le
    INNER JOIN ledger_accounts la ON la.id = le.ledger_account_id
    WHERE la.tenant_id = $1 AND la.unit_id = $2 AND la.type = $3::text
      AND le.created_at < $4::timestamptz
), 0)::numeric(12,2) AS balance
`

type GetUnitLedgerBalanceAsOfParams struct {
	TenantID   uuid.UUID
	UnitID     uuid.UUID
	LedgerType string
	AsOf       time.Time
}

// GetUnitLedgerBalanceAsOf is GetUnitLedgerBalance frozen at a cutoff
// (exclusive), for telling apart genuine carried-over arrears (a balance
// already positive before the current period's own charge was posted)
// from a just-billed current-period charge that simply hasn't been paid
// yet — the two look identical as an instantaneous "balance right now"
// but only the first is arrears. Same shape as ListUnitRentBalancesAsOf,
// for one unit instead of a whole property.
func (q *Queries) GetUnitLedgerBalanceAsOf(ctx context.Context, arg GetUnitLedgerBalanceAsOfParams) (moneyfmt.Money, error) {
	row := q.db.QueryRowContext(ctx, getUnitLedgerBalanceAsOf,
		arg.TenantID,
		arg.UnitID,
		arg.LedgerType,
		arg.AsOf,
	)
	var balance moneyfmt.Money
	err := row.Scan(&balance)
	return balance, err
}
