// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: managers.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createManager = `-- name: CreateManager :one

INSERT INTO managers (firm_name, username, email, phone, password_hash, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, firm_name, username, email, phone, password_hash, status, activated_at, created_at, version, trial_ends_at
`

type CreateManagerParams struct {
	FirmName     string
	Username     string
	Email        string
	Phone        string
	PasswordHash []byte
	Status       string
}

// Managers: the SaaS tenant (system-design.txt 3.1). Not tenant-scoped (no
// RLS), so these run on the Store directly, outside ExecTenantTx.
func (q *Queries) CreateManager(ctx context.Context, arg CreateManagerParams) (Manager, error) {
	row := q.db.QueryRowContext(ctx, createManager,
		arg.FirmName,
		arg.Username,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.Status,
	)
	var i Manager
	err := row.Scan(
		&i.ID,
		&i.FirmName,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Status,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.Version,
		&i.TrialEndsAt,
	)
	return i, err
}

const getManager = `-- name: GetManager :one
SELECT id, firm_name, username, email, phone, password_hash, status, activated_at, created_at, version, trial_ends_at FROM managers
WHERE id = $1
`

func (q *Queries) GetManager(ctx context.Context, id uuid.UUID) (Manager, error) {
	row := q.db.QueryRowContext(ctx, getManager, id)
	var i Manager
	err := row.Scan(
		&i.ID,
		&i.FirmName,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Status,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.Version,
		&i.TrialEndsAt,
	)
	return i, err
}

const getManagerByEmail = `-- name: GetManagerByEmail :one
SELECT id, firm_name, username, email, phone, password_hash, status, activated_at, created_at, version, trial_ends_at FROM managers
WHERE email = $1
`

func (q *Queries) GetManagerByEmail(ctx context.Context, email string) (Manager, error) {
	row := q.db.QueryRowContext(ctx, getManagerByEmail, email)
	var i Manager
	err := row.Scan(
		&i.ID,
		&i.FirmName,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Status,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.Version,
		&i.TrialEndsAt,
	)
	return i, err
}

const getManagerForToken = `-- name: GetManagerForToken :one
SELECT managers.id, managers.firm_name, managers.username, managers.email, managers.phone, managers.password_hash, managers.status, managers.activated_at, managers.created_at, managers.version, managers.trial_ends_at
FROM managers
INNER JOIN tokens ON tokens.manager_id = managers.id
WHERE tokens.hash = $1 AND tokens.scope = $2 AND tokens.expiry > now()
`

type GetManagerForTokenParams struct {
	Hash  []byte
	Scope string
}

// GetManagerForToken finds the manager a still-valid token of the given
// scope belongs to. The caller passes the token's SHA-256 hash.
func (q *Queries) GetManagerForToken(ctx context.Context, arg GetManagerForTokenParams) (Manager, error) {
	row := q.db.QueryRowContext(ctx, getManagerForToken, arg.Hash, arg.Scope)
	var i Manager
	err := row.Scan(
		&i.ID,
		&i.FirmName,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Status,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.Version,
		&i.TrialEndsAt,
	)
	return i, err
}

const setManagerStatus = `-- name: SetManagerStatus :one
UPDATE managers
SET status = $1, version = version + 1
WHERE id = $2 AND status = $3
RETURNING version
`

type SetManagerStatusParams struct {
	ToStatus   string
	ID         uuid.UUID
	FromStatus string
}

// SetManagerStatus moves a manager from one status to another: the Super
// Admin's suspend and reinstate (/v1/admin/managers/:id/suspend|reinstate).
// The from_status guard makes each move explicit: zero rows means the
// manager doesn't exist or wasn't in from_status.
func (q *Queries) SetManagerStatus(ctx context.Context, arg SetManagerStatusParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, setManagerStatus, arg.ToStatus, arg.ID, arg.FromStatus)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const updateManager = `-- name: UpdateManager :one
UPDATE managers
SET firm_name = $1,
    username = $2,
    email = $3,
    phone = $4,
    password_hash = $5,
    status = $6,
    activated_at = $7,
    trial_ends_at = $8,
    version = version + 1
WHERE id = $9 AND version = $10
RETURNING version
`

type UpdateManagerParams struct {
	FirmName     string
	Username     string
	Email        string
	Phone        string
	PasswordHash []byte
	Status       string
	ActivatedAt  *time.Time
	TrialEndsAt  *time.Time
	ID           uuid.UUID
	Version      int32
}

// UpdateManager: optimistic concurrency; zero rows means the version moved on.
func (q *Queries) UpdateManager(ctx context.Context, arg UpdateManagerParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, updateManager,
		arg.FirmName,
		arg.Username,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.Status,
		arg.ActivatedAt,
		arg.TrialEndsAt,
		arg.ID,
		arg.Version,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}
