// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/codercollo/willcoll/backend/pkg/moneyfmt"
	"github.com/google/uuid"
)

type Admin struct {
	ID           uuid.UUID
	Name         string
	Email        string
	PasswordHash []byte
	CreatedAt    time.Time
	IsSingleton  bool
}

type ArrearsCommitment struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UnitID    uuid.UUID
	Period    time.Time
	Note      string
	CreatedBy uuid.UUID
	CreatedAt time.Time
}

type Charge struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	LedgerAccountID uuid.UUID
	SourceType      string
	SourceID        *uuid.UUID
	Period          time.Time
	Amount          moneyfmt.Money
	Description     string
	CreatedBy       uuid.UUID
	CreatedAt       time.Time
}

type GarbageRun struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	PropertyID  uuid.UUID
	Period      time.Time
	FeeSnapshot moneyfmt.Money
	Locked      bool
	GeneratedAt time.Time
}

type Landlord struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	Name              string
	Phone             string
	Email             *string
	BankName          *string
	BankAccountName   *string
	BankAccountNumber *string
	CreatedAt         time.Time
	Version           int32
}

type Lease struct {
	ID                       uuid.UUID
	TenantID                 uuid.UUID
	UnitID                   uuid.UUID
	TenantName               string
	PrimaryPhone             string
	RentAmount               moneyfmt.Money
	RentDepositAmount        moneyfmt.Money
	WaterDepositAmount       moneyfmt.Money
	StartDate                time.Time
	EndDate                  *time.Time
	Status                   string
	CreatedAt                time.Time
	Version                  int32
	GarbageBilled            bool
	ElectricityDepositAmount moneyfmt.Money
}

type LeasePayer struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	LeaseID  uuid.UUID
	Name     string
	Phone    *string
}

type LedgerAccount struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UnitID    uuid.UUID
	Type      string
	CreatedAt time.Time
}

type LedgerEntry struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	TransactionHeaderID uuid.UUID
	LedgerAccountID     uuid.UUID
	Direction           string
	Amount              moneyfmt.Money
	ReferenceType       string
	ReferenceID         uuid.UUID
	CreatedAt           time.Time
}

type Manager struct {
	ID           uuid.UUID
	FirmName     string
	Username     string
	Email        string
	Phone        string
	PasswordHash []byte
	Status       string
	ActivatedAt  *time.Time
	CreatedAt    time.Time
	Version      int32
	TrialEndsAt  *time.Time
}

type PayOtp struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	UnitID     uuid.UUID
	Phone      string
	CodeHash   string
	Attempts   int32
	ExpiresAt  time.Time
	ConsumedAt *time.Time
	CreatedAt  time.Time
}

type Payment struct {
	ID                     uuid.UUID
	TenantID               uuid.UUID
	Source                 string
	MpesaReceipt           string
	PayheroReference       *string
	Amount                 moneyfmt.Money
	Msisdn                 string
	PayerName              *string
	AccountReference       *string
	MatchedUnitID          *uuid.UUID
	MatchedIntentID        *uuid.UUID
	Status                 string
	RawPayload             json.RawMessage
	ReceivedAt             time.Time
	CreatedAt              time.Time
	AutoAppliedUnconfirmed bool
	ReviewNote             *string
}

type PaymentAllocation struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	PaymentID       uuid.UUID
	LedgerAccountID uuid.UUID
	LedgerEntryID   uuid.UUID
	Amount          moneyfmt.Money
	CreatedAt       time.Time
}

type PaymentIntent struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	UnitID            uuid.UUID
	Lines             json.RawMessage
	ExternalReference string
	Phone             string
	Status            string
	CreatedAt         time.Time
	ExpiresAt         time.Time
	CheckoutRequestID *string
	FailureReason     *string
}

type Property struct {
	ID                       uuid.UUID
	TenantID                 uuid.UUID
	LandlordID               uuid.UUID
	Name                     string
	Location                 string
	Slug                     string
	GarbageEnabled           bool
	GarbageFee               moneyfmt.Money
	WaterRatePerUnit         moneyfmt.Money
	ManagementFeePercent     float64
	PayheroChannelID         *string
	CreatedAt                time.Time
	Version                  int32
	DeletedAt                *time.Time
	PrintTheme               *json.RawMessage
	UndergroundCapacityUnits *moneyfmt.Money
	RooftopCapacityUnits     *moneyfmt.Money
	ReconnectionFee          *moneyfmt.Money
	ElectricityEnabled       bool
	ElectricityDepositAmount moneyfmt.Money
}

type PropertyMeterReading struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	PropertyID      uuid.UUID
	Period          time.Time
	CurrentReading  moneyfmt.Money
	RecordedBy      uuid.UUID
	CreatedAt       time.Time
	PreviousReading *moneyfmt.Money
	ReadingDate     time.Time
	UnitsConsumed   *moneyfmt.Money
}

type Receipt struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	UnitID              uuid.UUID
	ReceiptNo           int64
	PaymentIds          []uuid.UUID
	Period              time.Time
	GeneratedAt         time.Time
	PropertyID          uuid.UUID
	PaymentAllocationID *uuid.UUID
	LedgerType          *string
	ArrearsNote         *string
	VoidedAt            *time.Time
	VoidReason          *string
	SettledPeriod       *time.Time
}

type ReceiptCounter struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
	NextNo     int64
}

type RentRun struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	UnitID         uuid.UUID
	Period         time.Time
	AmountSnapshot moneyfmt.Money
	Locked         bool
	GeneratedAt    time.Time
}

type Report struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	PropertyID  uuid.UUID
	Period      time.Time
	Totals      json.RawMessage
	GeneratedBy uuid.UUID
	GeneratedAt time.Time
	Notes       json.RawMessage
}

type ReportConfirmation struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	PropertyID     uuid.UUID
	Period         time.Time
	TotalsChecksum string
	NoteLines      json.RawMessage
	ConfirmedBy    uuid.UUID
	ConfirmedAt    time.Time
}

type ReportConfirmationHistory struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	PropertyID     uuid.UUID
	Period         time.Time
	TotalsChecksum string
	NoteLines      json.RawMessage
	ConfirmedBy    uuid.UUID
	ConfirmedAt    time.Time
	SupersededAt   time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type Subscription struct {
	ID                 uuid.UUID
	ManagerID          uuid.UUID
	PlanID             uuid.UUID
	Status             string
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
	PayheroChannelID   *string
	Version            int32
}

type SubscriptionInvoice struct {
	ID             uuid.UUID
	ManagerID      uuid.UUID
	SubscriptionID uuid.UUID
	Amount         moneyfmt.Money
	Period         time.Time
	MpesaReceipt   string
	Status         string
	PaidAt         *time.Time
	CreatedAt      time.Time
	PlanID         uuid.UUID
}

type SubscriptionPlan struct {
	ID              uuid.UUID
	Name            string
	Price           moneyfmt.Money
	BillingInterval string
	UnitCap         sql.NullInt32
	IsTest          bool
	ArchivedAt      *time.Time
	PricingType     string
	PerUnitPrice    *moneyfmt.Money
	MinPrice        *moneyfmt.Money
	SortOrder       int32
}

type SystemMetadatum struct {
	Key       string
	Value     json.RawMessage
	UpdatedAt time.Time
}

type Token struct {
	Hash      []byte
	ManagerID uuid.UUID
	Expiry    time.Time
	Scope     string
}

type TransactionHeader struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	Type           string
	IdempotencyKey string
	Description    string
	CreatedBy      string
	CreatedAt      time.Time
}

type Unit struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	PropertyID  uuid.UUID
	UnitCode    string
	MeterNumber *string
	Status      string
	CreatedAt   time.Time
	Version     int32
}

type UnitLedgerBalance struct {
	UnitID  uuid.UUID
	Type    string
	Balance interface{}
}

type UnitQrCode struct {
	ID            uuid.UUID
	Token         string
	LeaseID       uuid.UUID
	UnitID        uuid.UUID
	PropertyID    uuid.UUID
	TenantID      uuid.UUID
	CreatedBy     uuid.UUID
	CreatedAt     time.Time
	RevokedAt     *time.Time
	ScanCount     int32
	LastScannedAt *time.Time
}

type WaterReading struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	UnitID          uuid.UUID
	Period          time.Time
	PreviousReading moneyfmt.Money
	CurrentReading  moneyfmt.Money
	UnitsConsumed   *moneyfmt.Money
	RateSnapshot    moneyfmt.Money
	Amount          *moneyfmt.Money
	Locked          bool
	RecordedBy      uuid.UUID
	CreatedAt       time.Time
	LockedAt        *time.Time
	ReadingDate     time.Time
}
