// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pay_otp.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bumpPayOTPAttempts = `-- name: BumpPayOTPAttempts :exec
UPDATE pay_otps SET attempts = attempts + 1 WHERE tenant_id = $1 AND id = $2
`

type BumpPayOTPAttemptsParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) BumpPayOTPAttempts(ctx context.Context, arg BumpPayOTPAttemptsParams) error {
	_, err := q.db.ExecContext(ctx, bumpPayOTPAttempts, arg.TenantID, arg.ID)
	return err
}

const consumePayOTP = `-- name: ConsumePayOTP :execrows
UPDATE pay_otps SET consumed_at = now()
WHERE tenant_id = $1 AND id = $2 AND consumed_at IS NULL
`

type ConsumePayOTPParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// ConsumePayOTP marks a code used; zero rows means it already was.
func (q *Queries) ConsumePayOTP(ctx context.Context, arg ConsumePayOTPParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumePayOTP, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countRecentPayOTPs = `-- name: CountRecentPayOTPs :one
SELECT count(*)::int AS n
FROM pay_otps
WHERE tenant_id = $1 AND unit_id = $2 AND phone = $3 AND created_at > $4
`

type CountRecentPayOTPsParams struct {
	TenantID  uuid.UUID
	UnitID    uuid.UUID
	Phone     string
	CreatedAt time.Time
}

func (q *Queries) CountRecentPayOTPs(ctx context.Context, arg CountRecentPayOTPsParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countRecentPayOTPs,
		arg.TenantID,
		arg.UnitID,
		arg.Phone,
		arg.CreatedAt,
	)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const createPayOTP = `-- name: CreatePayOTP :exec
INSERT INTO pay_otps (tenant_id, unit_id, phone, code_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreatePayOTPParams struct {
	TenantID  uuid.UUID
	UnitID    uuid.UUID
	Phone     string
	CodeHash  string
	ExpiresAt time.Time
}

func (q *Queries) CreatePayOTP(ctx context.Context, arg CreatePayOTPParams) error {
	_, err := q.db.ExecContext(ctx, createPayOTP,
		arg.TenantID,
		arg.UnitID,
		arg.Phone,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	return err
}

const getLatestPayOTP = `-- name: GetLatestPayOTP :one
SELECT id, tenant_id, unit_id, phone, code_hash, attempts, expires_at, consumed_at, created_at FROM pay_otps
WHERE tenant_id = $1 AND unit_id = $2 AND phone = $3
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestPayOTPParams struct {
	TenantID uuid.UUID
	UnitID   uuid.UUID
	Phone    string
}

func (q *Queries) GetLatestPayOTP(ctx context.Context, arg GetLatestPayOTPParams) (PayOtp, error) {
	row := q.db.QueryRowContext(ctx, getLatestPayOTP, arg.TenantID, arg.UnitID, arg.Phone)
	var i PayOtp
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnitID,
		&i.Phone,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUnitPayPhones = `-- name: ListUnitPayPhones :many

SELECT l.primary_phone AS phone
FROM leases l
WHERE l.tenant_id = $1 AND l.unit_id = $2 AND l.status = 'active'
UNION
SELECT lp.phone
FROM lease_payers lp
INNER JOIN leases l ON l.id = lp.lease_id
WHERE lp.tenant_id = $1 AND l.unit_id = $2 AND l.status = 'active' AND lp.phone IS NOT NULL
`

type ListUnitPayPhonesParams struct {
	TenantID uuid.UUID
	UnitID   uuid.UUID
}

// The public pay page (system-design.txt 4.7): who may pay for a unit, the
// one-time codes that prove it, and the payer-facing view of the unit.
// Tenant-scoped under RLS: the caller resolves the manager first.
// ListUnitPayPhones is every phone on the unit active lease: the tenant and
// any co-payers. Only these numbers may request a code.
func (q *Queries) ListUnitPayPhones(ctx context.Context, arg ListUnitPayPhonesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUnitPayPhones, arg.TenantID, arg.UnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var phone string
		if err := rows.Scan(&phone); err != nil {
			return nil, err
		}
		items = append(items, phone)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgePayOTPs = `-- name: PurgePayOTPs :exec
DELETE FROM pay_otps WHERE tenant_id = $1 AND created_at < $2
`

type PurgePayOTPsParams struct {
	TenantID  uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) PurgePayOTPs(ctx context.Context, arg PurgePayOTPsParams) error {
	_, err := q.db.ExecContext(ctx, purgePayOTPs, arg.TenantID, arg.CreatedAt)
	return err
}
