// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_ingest.sql

package sqlc

import (
	"context"

	"github.com/codercollo/willcoll/backend/pkg/moneyfmt"
	"github.com/google/uuid"
)

const getPaymentIntentByReference = `-- name: GetPaymentIntentByReference :one
SELECT id, tenant_id, unit_id, lines, external_reference, phone, status, created_at, expires_at, checkout_request_id, failure_reason FROM payment_intents
WHERE tenant_id = $1 AND external_reference = $2
`

type GetPaymentIntentByReferenceParams struct {
	TenantID          uuid.UUID
	ExternalReference string
}

// GetPaymentIntentByReference is the tenant-scoped intent lookup for a webhook
// whose tenant is now known.
func (q *Queries) GetPaymentIntentByReference(ctx context.Context, arg GetPaymentIntentByReferenceParams) (PaymentIntent, error) {
	row := q.db.QueryRowContext(ctx, getPaymentIntentByReference, arg.TenantID, arg.ExternalReference)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnitID,
		&i.Lines,
		&i.ExternalReference,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CheckoutRequestID,
		&i.FailureReason,
	)
	return i, err
}

const listPayerCandidates = `-- name: ListPayerCandidates :many
SELECT u.id AS unit_id, 'phone'::text AS kind, l.primary_phone AS value
FROM leases l
INNER JOIN units u ON u.id = l.unit_id
INNER JOIN properties p ON p.id = u.property_id
WHERE l.tenant_id = $1 AND l.status = 'active'
  AND p.payhero_channel_id = $2 AND p.deleted_at IS NULL
UNION ALL
SELECT u.id, 'name', l.tenant_name
FROM leases l
INNER JOIN units u ON u.id = l.unit_id
INNER JOIN properties p ON p.id = u.property_id
WHERE l.tenant_id = $1 AND l.status = 'active'
  AND p.payhero_channel_id = $2 AND p.deleted_at IS NULL
UNION ALL
SELECT u.id, 'phone', lp.phone
FROM lease_payers lp
INNER JOIN leases l ON l.id = lp.lease_id AND l.status = 'active'
INNER JOIN units u ON u.id = l.unit_id
INNER JOIN properties p ON p.id = u.property_id
WHERE lp.tenant_id = $1 AND lp.phone IS NOT NULL
  AND p.payhero_channel_id = $2 AND p.deleted_at IS NULL
UNION ALL
SELECT u.id, 'name', lp.name
FROM lease_payers lp
INNER JOIN leases l ON l.id = lp.lease_id AND l.status = 'active'
INNER JOIN units u ON u.id = l.unit_id
INNER JOIN properties p ON p.id = u.property_id
WHERE lp.tenant_id = $1
  AND p.payhero_channel_id = $2 AND p.deleted_at IS NULL
`

type ListPayerCandidatesParams struct {
	TenantID  uuid.UUID
	ChannelID *string
}

type ListPayerCandidatesRow struct {
	UnitID uuid.UUID
	Kind   string
	Value  string
}

// ListPayerCandidates is every payer identity (phone or name) on the active
// leases of units in the manager properties that use a PayHero channel.
func (q *Queries) ListPayerCandidates(ctx context.Context, arg ListPayerCandidatesParams) ([]ListPayerCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPayerCandidates, arg.TenantID, arg.ChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayerCandidatesRow{}
	for rows.Next() {
		var i ListPayerCandidatesRow
		if err := rows.Scan(&i.UnitID, &i.Kind, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitBalances = `-- name: ListUnitBalances :many
SELECT b.type, b.balance::numeric(12,2) AS balance
FROM unit_ledger_balances b
INNER JOIN units u ON u.id = b.unit_id
WHERE u.tenant_id = $1 AND b.unit_id = $2
`

type ListUnitBalancesParams struct {
	TenantID uuid.UUID
	UnitID   uuid.UUID
}

type ListUnitBalancesRow struct {
	Type    string
	Balance moneyfmt.Money
}

// ListUnitBalances is every derived ledger balance of one unit.
func (q *Queries) ListUnitBalances(ctx context.Context, arg ListUnitBalancesParams) ([]ListUnitBalancesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnitBalances, arg.TenantID, arg.UnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnitBalancesRow{}
	for rows.Next() {
		var i ListUnitBalancesRow
		if err := rows.Scan(&i.Type, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveChannelTenants = `-- name: ResolveChannelTenants :many
SELECT DISTINCT tenant_id
FROM properties
WHERE payhero_channel_id = $1 AND deleted_at IS NULL
`

// ResolveChannelTenants finds the manager(s) whose properties use a PayHero
// collections channel. More than one row means the channel is ambiguous and
// the payment cannot be routed.
func (q *Queries) ResolveChannelTenants(ctx context.Context, payheroChannelID *string) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, resolveChannelTenants, payheroChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var tenant_id uuid.UUID
		if err := rows.Scan(&tenant_id); err != nil {
			return nil, err
		}
		items = append(items, tenant_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveIntentByReference = `-- name: ResolveIntentByReference :one

SELECT id, tenant_id, unit_id
FROM payment_intents
WHERE external_reference = $1
`

type ResolveIntentByReferenceRow struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	UnitID   uuid.UUID
}

// Payment ingestion (system-design.txt 4.8, 5).
//
// The first three queries are CROSS-TENANT lookups: an inbound webhook does
// not know its tenant yet, so they run on the willcoll_admin pool (BYPASSRLS,
// SELECT only), return only ids, and are called only by data.ResolverModel.
// Everything after them is tenant-scoped under RLS.
// ResolveIntentByReference finds the tenant and intent an STK reference
// belongs to.
func (q *Queries) ResolveIntentByReference(ctx context.Context, externalReference string) (ResolveIntentByReferenceRow, error) {
	row := q.db.QueryRowContext(ctx, resolveIntentByReference, externalReference)
	var i ResolveIntentByReferenceRow
	err := row.Scan(&i.ID, &i.TenantID, &i.UnitID)
	return i, err
}

const resolvePayTarget = `-- name: ResolvePayTarget :one
SELECT p.tenant_id, p.id AS property_id, u.id AS unit_id
FROM properties p
INNER JOIN units u ON u.property_id = p.id
WHERE p.slug = $1 AND u.unit_code = $2 AND p.deleted_at IS NULL
`

type ResolvePayTargetParams struct {
	Slug     string
	UnitCode string
}

type ResolvePayTargetRow struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
	UnitID     uuid.UUID
}

// ResolvePayTarget maps the public pay URL to its tenant, property and unit.
func (q *Queries) ResolvePayTarget(ctx context.Context, arg ResolvePayTargetParams) (ResolvePayTargetRow, error) {
	row := q.db.QueryRowContext(ctx, resolvePayTarget, arg.Slug, arg.UnitCode)
	var i ResolvePayTargetRow
	err := row.Scan(&i.TenantID, &i.PropertyID, &i.UnitID)
	return i, err
}

const setPaymentIntentStatus = `-- name: SetPaymentIntentStatus :exec
UPDATE payment_intents
SET status = $3, failure_reason = $4
WHERE tenant_id = $1 AND id = $2
`

type SetPaymentIntentStatusParams struct {
	TenantID      uuid.UUID
	ID            uuid.UUID
	Status        string
	FailureReason *string
}

// SetPaymentIntentStatus moves an intent to completed, expired or failed.
func (q *Queries) SetPaymentIntentStatus(ctx context.Context, arg SetPaymentIntentStatusParams) error {
	_, err := q.db.ExecContext(ctx, setPaymentIntentStatus,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.FailureReason,
	)
	return err
}
