// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/codercollo/willcoll/backend/pkg/moneyfmt"
	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    tenant_id, source, mpesa_receipt, payhero_reference, amount, msisdn,
    payer_name, account_reference, status, raw_payload, received_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (mpesa_receipt) DO NOTHING
RETURNING id, tenant_id, source, mpesa_receipt, payhero_reference, amount, msisdn, payer_name, account_reference, matched_unit_id, matched_intent_id, status, raw_payload, received_at, created_at, auto_applied_unconfirmed, review_note
`

type CreatePaymentParams struct {
	TenantID         uuid.UUID
	Source           string
	MpesaReceipt     string
	PayheroReference *string
	Amount           moneyfmt.Money
	Msisdn           string
	PayerName        *string
	AccountReference *string
	Status           string
	RawPayload       json.RawMessage
	ReceivedAt       time.Time
}

// CreatePayment is idempotent on mpesa_receipt: a PayHero retry of the
// same delivery inserts nothing and returns no row (sql.ErrNoRows).
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.TenantID,
		arg.Source,
		arg.MpesaReceipt,
		arg.PayheroReference,
		arg.Amount,
		arg.Msisdn,
		arg.PayerName,
		arg.AccountReference,
		arg.Status,
		arg.RawPayload,
		arg.ReceivedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.MpesaReceipt,
		&i.PayheroReference,
		&i.Amount,
		&i.Msisdn,
		&i.PayerName,
		&i.AccountReference,
		&i.MatchedUnitID,
		&i.MatchedIntentID,
		&i.Status,
		&i.RawPayload,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.AutoAppliedUnconfirmed,
		&i.ReviewNote,
	)
	return i, err
}

const createPaymentIntent = `-- name: CreatePaymentIntent :one

INSERT INTO payment_intents (tenant_id, unit_id, lines, external_reference, phone, status, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, unit_id, lines, external_reference, phone, status, created_at, expires_at, checkout_request_id, failure_reason
`

type CreatePaymentIntentParams struct {
	TenantID          uuid.UUID
	UnitID            uuid.UUID
	Lines             json.RawMessage
	ExternalReference string
	Phone             string
	Status            string
	ExpiresAt         time.Time
}

// Payment intents and inbound payments (system-design.txt 3.5, 3.8).
// Tenant-scoped under RLS.
func (q *Queries) CreatePaymentIntent(ctx context.Context, arg CreatePaymentIntentParams) (PaymentIntent, error) {
	row := q.db.QueryRowContext(ctx, createPaymentIntent,
		arg.TenantID,
		arg.UnitID,
		arg.Lines,
		arg.ExternalReference,
		arg.Phone,
		arg.Status,
		arg.ExpiresAt,
	)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnitID,
		&i.Lines,
		&i.ExternalReference,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CheckoutRequestID,
		&i.FailureReason,
	)
	return i, err
}

const getPaymentByMpesaReceipt = `-- name: GetPaymentByMpesaReceipt :one
SELECT id, tenant_id, source, mpesa_receipt, payhero_reference, amount, msisdn, payer_name, account_reference, matched_unit_id, matched_intent_id, status, raw_payload, received_at, created_at, auto_applied_unconfirmed, review_note FROM payments
WHERE tenant_id = $1 AND mpesa_receipt = $2
`

type GetPaymentByMpesaReceiptParams struct {
	TenantID     uuid.UUID
	MpesaReceipt string
}

func (q *Queries) GetPaymentByMpesaReceipt(ctx context.Context, arg GetPaymentByMpesaReceiptParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByMpesaReceipt, arg.TenantID, arg.MpesaReceipt)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.MpesaReceipt,
		&i.PayheroReference,
		&i.Amount,
		&i.Msisdn,
		&i.PayerName,
		&i.AccountReference,
		&i.MatchedUnitID,
		&i.MatchedIntentID,
		&i.Status,
		&i.RawPayload,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.AutoAppliedUnconfirmed,
		&i.ReviewNote,
	)
	return i, err
}

const getPaymentIntent = `-- name: GetPaymentIntent :one
SELECT id, tenant_id, unit_id, lines, external_reference, phone, status, created_at, expires_at, checkout_request_id, failure_reason FROM payment_intents
WHERE tenant_id = $1 AND id = $2
`

type GetPaymentIntentParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetPaymentIntent(ctx context.Context, arg GetPaymentIntentParams) (PaymentIntent, error) {
	row := q.db.QueryRowContext(ctx, getPaymentIntent, arg.TenantID, arg.ID)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnitID,
		&i.Lines,
		&i.ExternalReference,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CheckoutRequestID,
		&i.FailureReason,
	)
	return i, err
}

const getPendingIntentForUnit = `-- name: GetPendingIntentForUnit :one
SELECT id, tenant_id, unit_id, lines, external_reference, phone, status, created_at, expires_at, checkout_request_id, failure_reason FROM payment_intents
WHERE tenant_id = $1 AND unit_id = $2 AND status = $3 AND expires_at > $4 AND lines = $5
ORDER BY created_at DESC
LIMIT 1
`

type GetPendingIntentForUnitParams struct {
	TenantID  uuid.UUID
	UnitID    uuid.UUID
	Status    string
	ExpiresAt time.Time
	Lines     json.RawMessage
}

// A tenant who resubmits the same payment after an ambiguous PayHero
// timeout (the STK push may already be out) must get back the intent
// already created for it, not a fresh one with a new reference — otherwise
// a second prompt to the same phone risks a double charge.
func (q *Queries) GetPendingIntentForUnit(ctx context.Context, arg GetPendingIntentForUnitParams) (PaymentIntent, error) {
	row := q.db.QueryRowContext(ctx, getPendingIntentForUnit,
		arg.TenantID,
		arg.UnitID,
		arg.Status,
		arg.ExpiresAt,
		arg.Lines,
	)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnitID,
		&i.Lines,
		&i.ExternalReference,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CheckoutRequestID,
		&i.FailureReason,
	)
	return i, err
}
