// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_queue.sql

package sqlc

import (
	"context"
	"time"

	"github.com/codercollo/willcoll/backend/pkg/moneyfmt"
	"github.com/google/uuid"
)

const confirmPayment = `-- name: ConfirmPayment :execrows
UPDATE payments
SET auto_applied_unconfirmed = false, review_note = NULL,
    status = CASE WHEN status = 'matched' THEN 'allocated' ELSE status END
WHERE tenant_id = $1 AND id = $2 AND auto_applied_unconfirmed
`

type ConfirmPaymentParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// ConfirmPayment clears the unconfirmed flag once a manager has checked the
// engine placement, and settles the payment: one placed on a guess is stored as
// 'matched' until then, and would otherwise stay in the review list for ever.
// Zero rows means there was nothing to confirm.
func (q *Queries) ConfirmPayment(ctx context.Context, arg ConfirmPaymentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, confirmPayment, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countPendingPaymentsForPeriod = `-- name: CountPendingPaymentsForPeriod :one
SELECT count(*)
FROM payments p
INNER JOIN units u ON u.id = p.matched_unit_id
WHERE p.tenant_id = $1
  AND u.property_id = $2
  AND (p.received_at AT TIME ZONE 'Africa/Nairobi')::date >= $3::date
  AND (p.received_at AT TIME ZONE 'Africa/Nairobi')::date < ($3::date + interval '1 month')
  AND (p.status <> 'allocated' OR p.auto_applied_unconfirmed)
`

type CountPendingPaymentsForPeriodParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
	Period     time.Time
}

// CountPendingPaymentsForPeriod is the sanity check's "no unallocated or
// review-queue payments left for the period": payments matched to one of
// the property's units, received within the period, that are not a
// confirmed allocation.
func (q *Queries) CountPendingPaymentsForPeriod(ctx context.Context, arg CountPendingPaymentsForPeriodParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingPaymentsForPeriod, arg.TenantID, arg.PropertyID, arg.Period)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const expireStaleIntents = `-- name: ExpireStaleIntents :execrows
UPDATE payment_intents
SET status = 'expired'
WHERE tenant_id = $1 AND status = 'pending' AND expires_at < now()
`

// ExpireStaleIntents closes intents whose STK push window has passed.
func (q *Queries) ExpireStaleIntents(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireStaleIntents, tenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPayment = `-- name: GetPayment :one
SELECT id, tenant_id, source, mpesa_receipt, payhero_reference, amount, msisdn, payer_name, account_reference, matched_unit_id, matched_intent_id, status, raw_payload, received_at, created_at, auto_applied_unconfirmed, review_note FROM payments
WHERE tenant_id = $1 AND id = $2
`

type GetPaymentParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetPayment(ctx context.Context, arg GetPaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPayment, arg.TenantID, arg.ID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.MpesaReceipt,
		&i.PayheroReference,
		&i.Amount,
		&i.Msisdn,
		&i.PayerName,
		&i.AccountReference,
		&i.MatchedUnitID,
		&i.MatchedIntentID,
		&i.Status,
		&i.RawPayload,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.AutoAppliedUnconfirmed,
		&i.ReviewNote,
	)
	return i, err
}

const getPaymentForIntent = `-- name: GetPaymentForIntent :one
SELECT id, tenant_id, source, mpesa_receipt, payhero_reference, amount, msisdn, payer_name, account_reference, matched_unit_id, matched_intent_id, status, raw_payload, received_at, created_at, auto_applied_unconfirmed, review_note FROM payments
WHERE tenant_id = $1 AND matched_intent_id = $2
ORDER BY received_at DESC
LIMIT 1
`

type GetPaymentForIntentParams struct {
	TenantID        uuid.UUID
	MatchedIntentID *uuid.UUID
}

// GetPaymentForIntent is the payment that settled an intent: the tenant
// receipt shown when the pay page sees the intent complete.
func (q *Queries) GetPaymentForIntent(ctx context.Context, arg GetPaymentForIntentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentForIntent, arg.TenantID, arg.MatchedIntentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.MpesaReceipt,
		&i.PayheroReference,
		&i.Amount,
		&i.Msisdn,
		&i.PayerName,
		&i.AccountReference,
		&i.MatchedUnitID,
		&i.MatchedIntentID,
		&i.Status,
		&i.RawPayload,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.AutoAppliedUnconfirmed,
		&i.ReviewNote,
	)
	return i, err
}

const listPaymentsForReview = `-- name: ListPaymentsForReview :many

SELECT
    count(*) OVER() AS total_records,
    p.id, p.source, p.mpesa_receipt, p.amount, p.msisdn, p.payer_name,
    p.account_reference, p.matched_unit_id, p.status,
    p.auto_applied_unconfirmed, p.review_note, p.received_at,
    u.unit_code
FROM payments p
LEFT JOIN units u ON u.id = p.matched_unit_id
WHERE p.tenant_id = $1
  AND (p.status <> 'allocated' OR p.auto_applied_unconfirmed)
ORDER BY p.received_at DESC, p.id ASC
LIMIT $3 OFFSET $2
`

type ListPaymentsForReviewParams struct {
	TenantID   uuid.UUID
	PageOffset int32
	PageLimit  int32
}

type ListPaymentsForReviewRow struct {
	TotalRecords           int64
	ID                     uuid.UUID
	Source                 string
	MpesaReceipt           string
	Amount                 moneyfmt.Money
	Msisdn                 string
	PayerName              *string
	AccountReference       *string
	MatchedUnitID          *uuid.UUID
	Status                 string
	AutoAppliedUnconfirmed bool
	ReviewNote             *string
	ReceivedAt             time.Time
	UnitCode               *string
}

// The manager review queue for inbound payments, and payment-intent upkeep
// (system-design.txt 4.7, 4.8, 5). Tenant-scoped under RLS.
// ListPaymentsForReview is everything a manager still has to look at: payments
// that are unmatched, matched but not placed, or placed by the engine on a
// guess that is not yet confirmed. Newest first.
func (q *Queries) ListPaymentsForReview(ctx context.Context, arg ListPaymentsForReviewParams) ([]ListPaymentsForReviewRow, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentsForReview, arg.TenantID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsForReviewRow{}
	for rows.Next() {
		var i ListPaymentsForReviewRow
		if err := rows.Scan(
			&i.TotalRecords,
			&i.ID,
			&i.Source,
			&i.MpesaReceipt,
			&i.Amount,
			&i.Msisdn,
			&i.PayerName,
			&i.AccountReference,
			&i.MatchedUnitID,
			&i.Status,
			&i.AutoAppliedUnconfirmed,
			&i.ReviewNote,
			&i.ReceivedAt,
			&i.UnitCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPaymentIntentCheckout = `-- name: SetPaymentIntentCheckout :exec
UPDATE payment_intents
SET checkout_request_id = $3
WHERE tenant_id = $1 AND id = $2
`

type SetPaymentIntentCheckoutParams struct {
	TenantID          uuid.UUID
	ID                uuid.UUID
	CheckoutRequestID *string
}

// SetPaymentIntentCheckout records PayHero checkout request id for a push.
func (q *Queries) SetPaymentIntentCheckout(ctx context.Context, arg SetPaymentIntentCheckoutParams) error {
	_, err := q.db.ExecContext(ctx, setPaymentIntentCheckout, arg.TenantID, arg.ID, arg.CheckoutRequestID)
	return err
}
