// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: properties.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/codercollo/willcoll/backend/pkg/moneyfmt"
	"github.com/google/uuid"
)

const archiveProperty = `-- name: ArchiveProperty :execrows
UPDATE properties
SET deleted_at = now(), version = version + 1
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
`

type ArchivePropertyParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// ArchiveProperty is the soft delete behind DELETE /v1/properties/:id. The
// API role has no DELETE on properties (000019); zero rows affected means
// the property doesn't exist or is already archived.
func (q *Queries) ArchiveProperty(ctx context.Context, arg ArchivePropertyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveProperty, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createProperty = `-- name: CreateProperty :one

INSERT INTO properties (
    tenant_id, landlord_id, name, location, slug, garbage_enabled,
    garbage_fee, electricity_enabled, electricity_deposit_amount,
    water_rate_per_unit, management_fee_percent, payhero_channel_id,
    underground_capacity_units, rooftop_capacity_units, reconnection_fee
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15
)
RETURNING id, tenant_id, landlord_id, name, location, slug, garbage_enabled, garbage_fee, water_rate_per_unit, management_fee_percent, payhero_channel_id, created_at, version, deleted_at, print_theme, underground_capacity_units, rooftop_capacity_units, reconnection_fee, electricity_enabled, electricity_deposit_amount
`

type CreatePropertyParams struct {
	TenantID                 uuid.UUID
	LandlordID               uuid.UUID
	Name                     string
	Location                 string
	Slug                     string
	GarbageEnabled           bool
	GarbageFee               moneyfmt.Money
	ElectricityEnabled       bool
	ElectricityDepositAmount moneyfmt.Money
	WaterRatePerUnit         moneyfmt.Money
	ManagementFeePercent     float64
	PayheroChannelID         *string
	UndergroundCapacityUnits *moneyfmt.Money
	RooftopCapacityUnits     *moneyfmt.Money
	ReconnectionFee          *moneyfmt.Money
}

// Properties (system-design.txt 3.2, 4.6). Every query also filters on
// tenant_id: RLS is the enforcing layer, this is the belt to its braces.
// Archived properties (deleted_at set, migration 000019) are invisible to
// every read and update below.
func (q *Queries) CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error) {
	row := q.db.QueryRowContext(ctx, createProperty,
		arg.TenantID,
		arg.LandlordID,
		arg.Name,
		arg.Location,
		arg.Slug,
		arg.GarbageEnabled,
		arg.GarbageFee,
		arg.ElectricityEnabled,
		arg.ElectricityDepositAmount,
		arg.WaterRatePerUnit,
		arg.ManagementFeePercent,
		arg.PayheroChannelID,
		arg.UndergroundCapacityUnits,
		arg.RooftopCapacityUnits,
		arg.ReconnectionFee,
	)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LandlordID,
		&i.Name,
		&i.Location,
		&i.Slug,
		&i.GarbageEnabled,
		&i.GarbageFee,
		&i.WaterRatePerUnit,
		&i.ManagementFeePercent,
		&i.PayheroChannelID,
		&i.CreatedAt,
		&i.Version,
		&i.DeletedAt,
		&i.PrintTheme,
		&i.UndergroundCapacityUnits,
		&i.RooftopCapacityUnits,
		&i.ReconnectionFee,
		&i.ElectricityEnabled,
		&i.ElectricityDepositAmount,
	)
	return i, err
}

const getProperty = `-- name: GetProperty :one
SELECT id, tenant_id, landlord_id, name, location, slug, garbage_enabled, garbage_fee, water_rate_per_unit, management_fee_percent, payhero_channel_id, created_at, version, deleted_at, print_theme, underground_capacity_units, rooftop_capacity_units, reconnection_fee, electricity_enabled, electricity_deposit_amount FROM properties
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetPropertyParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetProperty(ctx context.Context, arg GetPropertyParams) (Property, error) {
	row := q.db.QueryRowContext(ctx, getProperty, arg.TenantID, arg.ID)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LandlordID,
		&i.Name,
		&i.Location,
		&i.Slug,
		&i.GarbageEnabled,
		&i.GarbageFee,
		&i.WaterRatePerUnit,
		&i.ManagementFeePercent,
		&i.PayheroChannelID,
		&i.CreatedAt,
		&i.Version,
		&i.DeletedAt,
		&i.PrintTheme,
		&i.UndergroundCapacityUnits,
		&i.RooftopCapacityUnits,
		&i.ReconnectionFee,
		&i.ElectricityEnabled,
		&i.ElectricityDepositAmount,
	)
	return i, err
}

const landlordBelongsToTenant = `-- name: LandlordBelongsToTenant :one
SELECT EXISTS (
    SELECT 1 FROM landlords WHERE tenant_id = $1 AND id = $2
)
`

type LandlordBelongsToTenantParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// LandlordBelongsToTenant guards landlord_id on create/update. Foreign-key
// checks run with the table owner's rights and ignore RLS, so without
// this a manager could attach a property to another firm's landlord.
func (q *Queries) LandlordBelongsToTenant(ctx context.Context, arg LandlordBelongsToTenantParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, landlordBelongsToTenant, arg.TenantID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listProperties = `-- name: ListProperties :many
SELECT count(*) OVER() AS total_records, properties.id, properties.tenant_id, properties.landlord_id, properties.name, properties.location, properties.slug, properties.garbage_enabled, properties.garbage_fee, properties.water_rate_per_unit, properties.management_fee_percent, properties.payhero_channel_id, properties.created_at, properties.version, properties.deleted_at, properties.print_theme, properties.underground_capacity_units, properties.rooftop_capacity_units, properties.reconnection_fee, properties.electricity_enabled, properties.electricity_deposit_amount
FROM properties
WHERE tenant_id = $1
  AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR landlord_id = $2::uuid)
ORDER BY
    CASE WHEN $3::text = 'name' THEN name END ASC,
    CASE WHEN $3::text = '-name' THEN name END DESC,
    CASE WHEN $3::text = 'created_at' THEN created_at END ASC,
    CASE WHEN $3::text = '-created_at' THEN created_at END DESC,
    id ASC
LIMIT $5 OFFSET $4
`

type ListPropertiesParams struct {
	TenantID   uuid.UUID
	LandlordID *uuid.UUID
	Sort       string
	PageOffset int32
	PageLimit  int32
}

type ListPropertiesRow struct {
	TotalRecords int64
	Property     Property
}

// ListProperties pages a tenant's properties, optionally filtered to one
// landlord. The sort key comes from the handler's safelist; each CASE arm
// is NULL unless selected, so only one ordering applies, with id as the
// stable tie-breaker.
func (q *Queries) ListProperties(ctx context.Context, arg ListPropertiesParams) ([]ListPropertiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listProperties,
		arg.TenantID,
		arg.LandlordID,
		arg.Sort,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPropertiesRow{}
	for rows.Next() {
		var i ListPropertiesRow
		if err := rows.Scan(
			&i.TotalRecords,
			&i.Property.ID,
			&i.Property.TenantID,
			&i.Property.LandlordID,
			&i.Property.Name,
			&i.Property.Location,
			&i.Property.Slug,
			&i.Property.GarbageEnabled,
			&i.Property.GarbageFee,
			&i.Property.WaterRatePerUnit,
			&i.Property.ManagementFeePercent,
			&i.Property.PayheroChannelID,
			&i.Property.CreatedAt,
			&i.Property.Version,
			&i.Property.DeletedAt,
			&i.Property.PrintTheme,
			&i.Property.UndergroundCapacityUnits,
			&i.Property.RooftopCapacityUnits,
			&i.Property.ReconnectionFee,
			&i.Property.ElectricityEnabled,
			&i.Property.ElectricityDepositAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const propertyHasActiveLeases = `-- name: PropertyHasActiveLeases :one
SELECT EXISTS (
    SELECT 1
    FROM leases
    INNER JOIN units ON units.id = leases.unit_id
    WHERE leases.tenant_id = $1 AND units.property_id = $2 AND leases.status = 'active'
)
`

type PropertyHasActiveLeasesParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
}

// PropertyHasActiveLeases blocks archiving a property people still live in.
func (q *Queries) PropertyHasActiveLeases(ctx context.Context, arg PropertyHasActiveLeasesParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, propertyHasActiveLeases, arg.TenantID, arg.PropertyID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setPropertyPrintTheme = `-- name: SetPropertyPrintTheme :one
UPDATE properties
SET print_theme = $1::jsonb,
    version = version + 1
WHERE tenant_id = $2 AND id = $3 AND version = $4 AND deleted_at IS NULL
RETURNING version
`

type SetPropertyPrintThemeParams struct {
	PrintTheme *json.RawMessage
	TenantID   uuid.UUID
	ID         uuid.UUID
	Version    int32
}

// SetPropertyPrintTheme replaces the property's print theme (NULL clears
// it), with the same optimistic version check as UpdateProperty.
func (q *Queries) SetPropertyPrintTheme(ctx context.Context, arg SetPropertyPrintThemeParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, setPropertyPrintTheme,
		arg.PrintTheme,
		arg.TenantID,
		arg.ID,
		arg.Version,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const updateProperty = `-- name: UpdateProperty :one
UPDATE properties
SET landlord_id = $1,
    name = $2,
    location = $3,
    slug = $4,
    garbage_enabled = $5,
    garbage_fee = $6,
    electricity_enabled = $7,
    electricity_deposit_amount = $8,
    water_rate_per_unit = $9,
    management_fee_percent = $10,
    payhero_channel_id = $11,
    underground_capacity_units = $12,
    rooftop_capacity_units = $13,
    reconnection_fee = $14,
    version = version + 1
WHERE tenant_id = $15 AND id = $16 AND version = $17 AND deleted_at IS NULL
RETURNING version
`

type UpdatePropertyParams struct {
	LandlordID               uuid.UUID
	Name                     string
	Location                 string
	Slug                     string
	GarbageEnabled           bool
	GarbageFee               moneyfmt.Money
	ElectricityEnabled       bool
	ElectricityDepositAmount moneyfmt.Money
	WaterRatePerUnit         moneyfmt.Money
	ManagementFeePercent     float64
	PayheroChannelID         *string
	UndergroundCapacityUnits *moneyfmt.Money
	RooftopCapacityUnits     *moneyfmt.Money
	ReconnectionFee          *moneyfmt.Money
	TenantID                 uuid.UUID
	ID                       uuid.UUID
	Version                  int32
}

// UpdateProperty applies optimistic concurrency control: zero rows (and so
// sql.ErrNoRows) means the version moved on since the caller read it.
func (q *Queries) UpdateProperty(ctx context.Context, arg UpdatePropertyParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, updateProperty,
		arg.LandlordID,
		arg.Name,
		arg.Location,
		arg.Slug,
		arg.GarbageEnabled,
		arg.GarbageFee,
		arg.ElectricityEnabled,
		arg.ElectricityDepositAmount,
		arg.WaterRatePerUnit,
		arg.ManagementFeePercent,
		arg.PayheroChannelID,
		arg.UndergroundCapacityUnits,
		arg.RooftopCapacityUnits,
		arg.ReconnectionFee,
		arg.TenantID,
		arg.ID,
		arg.Version,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}
