// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: property_summary.sql

package sqlc

import (
	"context"
	"time"

	"github.com/codercollo/willcoll/backend/pkg/moneyfmt"
	"github.com/google/uuid"
)

const listPropertySummaries = `-- name: ListPropertySummaries :many

SELECT
    p.id AS property_id,
    ll.name AS landlord_name,
    (count(u.id) FILTER (WHERE u.status = 'occupied'))::int AS occupied,
    (count(u.id) FILTER (WHERE u.id IS NOT NULL AND u.status <> 'occupied'))::int AS vacant,
    COALESCE(SUM(COALESCE(rr.amount_snapshot, l.rent_amount)) FILTER (WHERE u.status = 'occupied'), 0)::numeric(12,2) AS expected,
    COALESCE(SUM(paid.amount), 0)::numeric(12,2) AS collected
FROM properties p
INNER JOIN landlords ll ON ll.id = p.landlord_id
LEFT JOIN units u ON u.property_id = p.id
LEFT JOIN leases l ON l.unit_id = u.id AND l.status = 'active'
LEFT JOIN rent_runs rr ON rr.unit_id = u.id AND rr.period = $1
LEFT JOIN LATERAL (
    SELECT SUM(pa.amount) AS amount
    FROM payment_allocations pa
    INNER JOIN payments py ON py.id = pa.payment_id
    INNER JOIN ledger_accounts la ON la.id = pa.ledger_account_id
    WHERE la.unit_id = u.id
      AND la.type = 'RENT'
      AND (py.received_at AT TIME ZONE 'Africa/Nairobi')::date >= $1::date
      AND (py.received_at AT TIME ZONE 'Africa/Nairobi')::date < ($1::date + interval '1 month')
      AND NOT EXISTS (
          SELECT 1 FROM ledger_entries r
          WHERE r.reference_type = 'reversal' AND r.reference_id = pa.ledger_entry_id
      )
) paid ON true
WHERE p.tenant_id = $2 AND p.deleted_at IS NULL
GROUP BY p.id, ll.name
`

type ListPropertySummariesParams struct {
	Period   time.Time
	TenantID uuid.UUID
}

type ListPropertySummariesRow struct {
	PropertyID   uuid.UUID
	LandlordName string
	Occupied     int32
	Vacant       int32
	Expected     moneyfmt.Money
	Collected    moneyfmt.Money
}

// The Properties card grid (system-design.txt 6.1, 10): per property, who
// owns it, how many units are occupied and vacant, and how much rent has been
// collected against what was expected this period. Tenant-scoped under RLS.
// ListPropertySummaries has one row per live property of the manager.
// Expected is what the occupied units owe for the period (the billed snapshot
// if the month has been run, else the lease current rent). Collected is rent
// received in the period in Kenya calendar dates, ignoring payments since
// reversed; it counts every unit, since a payment can arrive after a move-out.
func (q *Queries) ListPropertySummaries(ctx context.Context, arg ListPropertySummariesParams) ([]ListPropertySummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPropertySummaries, arg.Period, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPropertySummariesRow{}
	for rows.Next() {
		var i ListPropertySummariesRow
		if err := rows.Scan(
			&i.PropertyID,
			&i.LandlordName,
			&i.Occupied,
			&i.Vacant,
			&i.Expected,
			&i.Collected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
