// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/codercollo/willcoll/backend/pkg/moneyfmt"
	"github.com/google/uuid"
)

type Querier interface {
	// ActivateSubscription starts a paid period, on the plan the paid invoice
	// named (a switch takes effect here, not at renewal request time).
	ActivateSubscription(ctx context.Context, arg ActivateSubscriptionParams) (int32, error)
	// AdminArchiveSubscriptionPlan hides a plan from managers and blocks renewals
	// onto it; existing subscribers keep their period, and history is untouched.
	AdminArchiveSubscriptionPlan(ctx context.Context, id uuid.UUID) (SubscriptionPlan, error)
	// Subscription plan management for the Super Admin (system-design.txt 1.1,
	// 3.6). subscription_plans is global (no tenant), and only the willcoll_admin
	// role may write it; the API role can only read it. Plans are never deleted:
	// subscriptions reference them.
	AdminCreateSubscriptionPlan(ctx context.Context, arg AdminCreateSubscriptionPlanParams) (SubscriptionPlan, error)
	// AdminGetManager is one manager with the same oversight columns.
	AdminGetManager(ctx context.Context, id uuid.UUID) (AdminGetManagerRow, error)
	// ---------------------------------------------------------------- oversight
	// AdminListManagers pages every manager (firm) with its latest
	// subscription (NULL when it has none) and portfolio size
	// (GET /v1/admin/managers).
	AdminListManagers(ctx context.Context, arg AdminListManagersParams) ([]AdminListManagersRow, error)
	// AdminPlanSubscriberCount is how many subscriptions use a plan, so the admin
	// sees what a change affects.
	AdminListSubscriptionPlans(ctx context.Context) ([]AdminListSubscriptionPlansRow, error)
	// AdminListSubscriptions pages every firm's subscriptions
	// (GET /v1/admin/subscriptions), soonest-ending first by default.
	AdminListSubscriptions(ctx context.Context, arg AdminListSubscriptionsParams) ([]AdminListSubscriptionsRow, error)
	// AdminRestoreSubscriptionPlan un-archives a plan.
	AdminRestoreSubscriptionPlan(ctx context.Context, id uuid.UUID) (SubscriptionPlan, error)
	// Business gauges for GET /debug/vars (system-design.txt section 5). Counts
	// only, across every manager, on the willcoll_admin pool (BYPASSRLS, SELECT
	// only); no row, id or amount leaves the database.
	// AdminReviewQueueDepth is how many payments still need a manager: those no
	// unit could be found for (the number that should trend to zero as intent
	// payments replace paybill ones), and those the engine placed on a guess.
	AdminReviewQueueDepth(ctx context.Context) (AdminReviewQueueDepthRow, error)
	// AdminUpdateSubscriptionPlan changes a plan. A new price applies to invoices
	// raised from then on; invoices already issued keep the amount they carry.
	AdminUpdateSubscriptionPlan(ctx context.Context, arg AdminUpdateSubscriptionPlanParams) (SubscriptionPlan, error)
	// AdvanceReceiptCounter hands out the locked next_no and increments it.
	// Call after LockReceiptCounter, in the same transaction.
	AdvanceReceiptCounter(ctx context.Context, arg AdvanceReceiptCounterParams) error
	// ArchiveProperty is the soft delete behind DELETE /v1/properties/:id. The
	// API role has no DELETE on properties (000019); zero rows affected means
	// the property doesn't exist or is already archived.
	ArchiveProperty(ctx context.Context, arg ArchivePropertyParams) (int64, error)
	// Copies the current confirmation row (if any) into history before a
	// re-confirm overwrites it. A no-op insert-select when nothing exists yet.
	ArchiveReportConfirmation(ctx context.Context, arg ArchiveReportConfirmationParams) error
	BumpPayOTPAttempts(ctx context.Context, arg BumpPayOTPAttemptsParams) error
	// ConfirmPayment clears the unconfirmed flag once a manager has checked the
	// engine placement, and settles the payment: one placed on a guess is stored as
	// 'matched' until then, and would otherwise stay in the review list for ever.
	// Zero rows means there was nothing to confirm.
	ConfirmPayment(ctx context.Context, arg ConfirmPaymentParams) (int64, error)
	// ConsumePayOTP marks a code used; zero rows means it already was.
	ConsumePayOTP(ctx context.Context, arg ConsumePayOTPParams) (int64, error)
	// CountManagerUnits is the manager's occupied+vacant unit count across their
	// live properties, checked against a plan's unit_cap before a renewal.
	CountManagerUnits(ctx context.Context, tenantID uuid.UUID) (int32, error)
	// CountPendingPaymentsForPeriod is the sanity check's "no unallocated or
	// review-queue payments left for the period": payments matched to one of
	// the property's units, received within the period, that are not a
	// confirmed allocation.
	CountPendingPaymentsForPeriod(ctx context.Context, arg CountPendingPaymentsForPeriodParams) (int64, error)
	CountRecentPayOTPs(ctx context.Context, arg CountRecentPayOTPsParams) (int32, error)
	CreateArrearsCommitment(ctx context.Context, arg CreateArrearsCommitmentParams) (CreateArrearsCommitmentRow, error)
	// Charges: WHAT IS OWED (system-design.txt 3.3). Append-only: INSERT and
	// SELECT only. A wrong charge is corrected by a negative-amount 'manual'
	// charge (storno), never an UPDATE or DELETE.
	CreateCharge(ctx context.Context, arg CreateChargeParams) (uuid.UUID, error)
	// CreateGarbageRun records the run. A second run for the same property and
	// period violates garbage_runs_property_id_period_key.
	CreateGarbageRun(ctx context.Context, arg CreateGarbageRunParams) (uuid.UUID, error)
	// Landlords (system-design.txt 1.3, 3.2). Tenant-scoped under RLS; every
	// query also filters on tenant_id.
	CreateLandlord(ctx context.Context, arg CreateLandlordParams) (Landlord, error)
	// Leases (system-design.txt 3.2, 3.2.1). Tenant-scoped under RLS. The
	// LEASE_START deposit posting runs in the same transaction as CreateLease;
	// see data.LeaseModel.Insert and ADR 0002.
	CreateLease(ctx context.Context, arg CreateLeaseParams) (Lease, error)
	// Lease co-payers (system-design.txt 2, 1.4): the other people allowed to pay
	// for a unit, the "OR" names on the payments schedule. Their phones can also
	// request the pay-page one-time code and identify organic paybill payments.
	// Tenant-scoped under RLS. Not ledger tables, so rows may be removed.
	// CreateLeasePayer adds a co-payer to a lease.
	CreateLeasePayer(ctx context.Context, arg CreateLeasePayerParams) (LeasePayer, error)
	CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (uuid.UUID, error)
	// Managers: the SaaS tenant (system-design.txt 3.1). Not tenant-scoped (no
	// RLS), so these run on the Store directly, outside ExecTenantTx.
	CreateManager(ctx context.Context, arg CreateManagerParams) (Manager, error)
	CreatePayOTP(ctx context.Context, arg CreatePayOTPParams) error
	// CreatePayment is idempotent on mpesa_receipt: a PayHero retry of the
	// same delivery inserts nothing and returns no row (sql.ErrNoRows).
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	// CreatePaymentAllocation links a payment to the ledger entry that credited
	// it. The caller picks the id up front because the credit entry reference_id
	// must point back at this row: entry first, then this row. INSERT only.
	CreatePaymentAllocation(ctx context.Context, arg CreatePaymentAllocationParams) error
	// Payment intents and inbound payments (system-design.txt 3.5, 3.8).
	// Tenant-scoped under RLS.
	CreatePaymentIntent(ctx context.Context, arg CreatePaymentIntentParams) (PaymentIntent, error)
	// Properties (system-design.txt 3.2, 4.6). Every query also filters on
	// tenant_id: RLS is the enforcing layer, this is the belt to its braces.
	// Archived properties (deleted_at set, migration 000019) are invisible to
	// every read and update below.
	CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error)
	// CreateReceipt issues one allocation's receipt. payment_allocation_id is
	// unique, so a retried posting that (however it happened) reused the same
	// allocation id conflicts here instead of consuming a second number —
	// callers check for that conflict and reuse GetReceiptByAllocation's row
	// instead of treating it as an error.
	CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error)
	// CreateReceiptCounter is called once, when a property is created (not
	// lazily), so every property always has a counter row before its first
	// payment.
	CreateReceiptCounter(ctx context.Context, arg CreateReceiptCounterParams) error
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	// CreateSubscriptionInvoice opens a pending invoice. mpesa_receipt is unique
	// and not yet known, so it holds a placeholder until the payment arrives.
	// plan_id is the plan the manager chose for this renewal: it may differ from
	// the subscription's current plan_id, and is what the webhook activates once
	// the payment is confirmed.
	CreateSubscriptionInvoice(ctx context.Context, arg CreateSubscriptionInvoiceParams) (SubscriptionInvoice, error)
	// Tokens: activation / password-reset (system-design.txt 3.1, 4.4). Only
	// the SHA-256 hash is stored. Not tenant-scoped.
	CreateToken(ctx context.Context, arg CreateTokenParams) error
	CreateTransactionHeader(ctx context.Context, arg CreateTransactionHeaderParams) (uuid.UUID, error)
	CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error)
	// Lease-bound unit QR codes (migration 000028). Tenant-scoped under RLS except
	// ResolveUnitQRToken, which runs on the willcoll_admin pool (SELECT only)
	// because the public scan endpoint has no tenant yet.
	CreateUnitQRCode(ctx context.Context, arg CreateUnitQRCodeParams) (UnitQrCode, error)
	DeleteAllTokensForManager(ctx context.Context, arg DeleteAllTokensForManagerParams) error
	// DeleteLeasePayer removes a co-payer. Zero rows means it is not on that lease.
	DeleteLeasePayer(ctx context.Context, arg DeleteLeasePayerParams) (int64, error)
	// DeleteTokensForManager removes every token a manager holds, whatever its
	// scope: after a password reset, no outstanding link of any kind should
	// still work.
	DeleteTokensForManager(ctx context.Context, managerID uuid.UUID) error
	// DevDeleteSubscription removes a manager's subscription (and, by cascade,
	// its invoices). Used only by cmd/devtools' dev/reset-trial, never by the API.
	DevDeleteSubscription(ctx context.Context, managerID uuid.UUID) (int64, error)
	// ExpireStaleIntents closes intents whose STK push window has passed.
	ExpireStaleIntents(ctx context.Context, tenantID uuid.UUID) (int64, error)
	// GarbageRunExists tells the preview whether the period is already billed.
	GarbageRunExists(ctx context.Context, arg GarbageRunExistsParams) (bool, error)
	// Rent (system-design.txt 2, 3.3). Expected rent is leases.rent_amount; a
	// rent run copies it into rent_runs.amount_snapshot when a month is billed,
	// and UNIQUE (unit_id, period) is what stops a period being billed twice.
	// GetActiveLeaseByUnit is the current lease of a unit (at most one: the
	// partial unique index on active leases).
	GetActiveLeaseByUnit(ctx context.Context, arg GetActiveLeaseByUnitParams) (Lease, error)
	// GetActiveUnitQRCodeByLease is the lease's live code, if it has one.
	GetActiveUnitQRCodeByLease(ctx context.Context, arg GetActiveUnitQRCodeByLeaseParams) (UnitQrCode, error)
	// Super Admin (system-design.txt 1.1, 3.1, 4.9). Platform-level, outside
	// the tenant boundary.
	//
	// The admin account queries (GetAdmin, GetAdminByEmail, UpsertAdmin) run on
	// the API's willcoll_app pool. The oversight queries further down run ONLY
	// on the willcoll_admin pool (BYPASSRLS, read-mostly — system-design.txt
	// 3.7), because they read across every tenant; under willcoll_app, RLS
	// would hide the tenant-scoped rows they count.
	GetAdmin(ctx context.Context, id uuid.UUID) (Admin, error)
	GetAdminByEmail(ctx context.Context, email string) (Admin, error)
	GetLandlord(ctx context.Context, arg GetLandlordParams) (Landlord, error)
	GetLatestPayOTP(ctx context.Context, arg GetLatestPayOTPParams) (PayOtp, error)
	GetLease(ctx context.Context, arg GetLeaseParams) (Lease, error)
	// GetLedgerEntryForReversal loads an entry with its account, tenant-scoped,
	// and whether it has already been reversed.
	GetLedgerEntryForReversal(ctx context.Context, arg GetLedgerEntryForReversalParams) (GetLedgerEntryForReversalRow, error)
	GetManager(ctx context.Context, id uuid.UUID) (Manager, error)
	GetManagerBillingContact(ctx context.Context, id uuid.UUID) (GetManagerBillingContactRow, error)
	GetManagerByEmail(ctx context.Context, email string) (Manager, error)
	// GetManagerForToken finds the manager a still-valid token of the given
	// scope belongs to. The caller passes the token's SHA-256 hash.
	GetManagerForToken(ctx context.Context, arg GetManagerForTokenParams) (Manager, error)
	// GetManualPaymentByReference finds an earlier hand-entered payment with the
	// same reference, so a double submit is refused instead of credited twice.
	GetManualPaymentByReference(ctx context.Context, arg GetManualPaymentByReferenceParams) (uuid.UUID, error)
	// The append-only ledger core (system-design.txt 3.3/3.4, ADR 0002).
	// transaction_headers and ledger_entries are INSERT and SELECT only: there
	// is deliberately no UPDATE or DELETE query here, the API role has no such
	// privilege (000018/000019), and data.TestAppendOnlyQueries fails if one
	// is ever added. Corrections are storno reversals.
	// GetOrCreateLedgerAccount returns the unit's anchor account of the given
	// type, creating it on first use. (ledger_accounts is not append-only; the
	// no-op DO UPDATE just makes RETURNING yield the existing row's id.)
	GetOrCreateLedgerAccount(ctx context.Context, arg GetOrCreateLedgerAccountParams) (uuid.UUID, error)
	GetPayment(ctx context.Context, arg GetPaymentParams) (Payment, error)
	GetPaymentByMpesaReceipt(ctx context.Context, arg GetPaymentByMpesaReceiptParams) (Payment, error)
	// GetPaymentForIntent is the payment that settled an intent: the tenant
	// receipt shown when the pay page sees the intent complete.
	GetPaymentForIntent(ctx context.Context, arg GetPaymentForIntentParams) (Payment, error)
	GetPaymentIntent(ctx context.Context, arg GetPaymentIntentParams) (PaymentIntent, error)
	// GetPaymentIntentByReference is the tenant-scoped intent lookup for a webhook
	// whose tenant is now known.
	GetPaymentIntentByReference(ctx context.Context, arg GetPaymentIntentByReferenceParams) (PaymentIntent, error)
	// A tenant who resubmits the same payment after an ambiguous PayHero
	// timeout (the STK push may already be out) must get back the intent
	// already created for it, not a fresh one with a new reference — otherwise
	// a second prompt to the same phone risks a double charge.
	GetPendingIntentForUnit(ctx context.Context, arg GetPendingIntentForUnitParams) (PaymentIntent, error)
	// GetPlotMeterReadingRow is the period's own saved plot-meter row, if any.
	// No row (sql.ErrNoRows) means the period hasn't been read yet.
	GetPlotMeterReadingRow(ctx context.Context, arg GetPlotMeterReadingRowParams) (GetPlotMeterReadingRowRow, error)
	// GetPreviousPropertyMeterReading is the last period before this one that
	// was read, for the reading form's "Previous: X" default (same shape as
	// ListWaterGrid's per-unit default). No row (sql.ErrNoRows) means the
	// property has never been read before — Previous stays editable.
	GetPreviousPropertyMeterReading(ctx context.Context, arg GetPreviousPropertyMeterReadingParams) (moneyfmt.Money, error)
	GetProperty(ctx context.Context, arg GetPropertyParams) (Property, error)
	// GetPropertyMeterReading is the period's plot-meter units used, for
	// NOTE:1's storage-deviation line. No row, or a row with no previous
	// reading yet, means units used is unknown; the line is omitted, never
	// printed as zero.
	GetPropertyMeterReading(ctx context.Context, arg GetPropertyMeterReadingParams) (*moneyfmt.Money, error)
	// GetReceiptByAllocation is the idempotency read: a retried posting that
	// names the same allocation gets this row back instead of a new receipt.
	GetReceiptByAllocation(ctx context.Context, arg GetReceiptByAllocationParams) (Receipt, error)
	GetRentRun(ctx context.Context, arg GetRentRunParams) (RentRun, error)
	// GetReport reads the period's report row (its manager-typed notes).
	GetReport(ctx context.Context, arg GetReportParams) (GetReportRow, error)
	// Period confirmation gate. The checksum is a hash of the confirmed totals;
	// staleness is detected by recomputing it on every PDF request and
	// comparing, not by a trigger (system-design.txt PDF confirmation addendum).
	GetReportConfirmation(ctx context.Context, arg GetReportConfirmationParams) (GetReportConfirmationRow, error)
	GetSubscriptionByManager(ctx context.Context, managerID uuid.UUID) (Subscription, error)
	GetSubscriptionInvoice(ctx context.Context, arg GetSubscriptionInvoiceParams) (SubscriptionInvoice, error)
	GetSubscriptionPlan(ctx context.Context, id uuid.UUID) (SubscriptionPlan, error)
	// GetSystemMetadata reads a platform fact recorded outside the API, e.g.
	// 'last_backup' from scripts/db_backup_verify.sh (migration 000022).
	GetSystemMetadata(ctx context.Context, key string) (SystemMetadatum, error)
	GetUnit(ctx context.Context, arg GetUnitParams) (Unit, error)
	// GetUnitLedgerBalance reads the derived balance (never a stored column).
	// The view is security_invoker (000020), so RLS applies through it; the
	// units join adds the explicit tenant filter.
	GetUnitLedgerBalance(ctx context.Context, arg GetUnitLedgerBalanceParams) (moneyfmt.Money, error)
	// GetUnitLedgerBalanceAsOf is GetUnitLedgerBalance frozen at a cutoff
	// (exclusive), for telling apart genuine carried-over arrears (a balance
	// already positive before the current period's own charge was posted)
	// from a just-billed current-period charge that simply hasn't been paid
	// yet — the two look identical as an instantaneous "balance right now"
	// but only the first is arrears. Same shape as ListUnitRentBalancesAsOf,
	// for one unit instead of a whole property.
	GetUnitLedgerBalanceAsOf(ctx context.Context, arg GetUnitLedgerBalanceAsOfParams) (moneyfmt.Money, error)
	GetUnitQRCodeByToken(ctx context.Context, arg GetUnitQRCodeByTokenParams) (UnitQrCode, error)
	// GetWaterSummary totals the period's locked readings. Expected is the
	// consumed units at the property's current rate; billed is what was actually
	// charged (readings can carry a per-run rate), so the difference is the
	// "deviation" on the schedule.
	GetWaterSummary(ctx context.Context, arg GetWaterSummaryParams) (GetWaterSummaryRow, error)
	// IncrementUnitQRScan counts one scan of a live code. Zero rows means the
	// code was revoked between the lookup and now.
	IncrementUnitQRScan(ctx context.Context, arg IncrementUnitQRScanParams) (int64, error)
	// InsertRentRun records the run, already locked: rent has no draft step.
	// Zero rows (sql.ErrNoRows) means the unit is already billed for the period.
	InsertRentRun(ctx context.Context, arg InsertRentRunParams) (uuid.UUID, error)
	// LandlordBelongsToTenant guards landlord_id on create/update. Foreign-key
	// checks run with the table owner's rights and ignore RLS, so without
	// this a manager could attach a property to another firm's landlord.
	LandlordBelongsToTenant(ctx context.Context, arg LandlordBelongsToTenantParams) (bool, error)
	// ListActiveLeasesForProperty is every active lease on the property with its
	// unit: the source of expected rent for the rent schedule and monthly runs.
	ListActiveLeasesForProperty(ctx context.Context, arg ListActiveLeasesForPropertyParams) ([]ListActiveLeasesForPropertyRow, error)
	// ListActiveLeasesWithoutElectricityDeposit is every active lease on the
	// property that has never had an electricity deposit charged (amount still
	// zero — the same invariant the lease-start charge loop uses: zero means
	// "nothing to charge," never "waived after being charged"). Used to
	// retroactively charge existing leases the one time electricity_enabled
	// flips on for the property.
	ListActiveLeasesWithoutElectricityDeposit(ctx context.Context, arg ListActiveLeasesWithoutElectricityDepositParams) ([]Lease, error)
	// Commitment letters: the one piece of NOTE:2 that is a manager's record
	// of a real paper document, not derived from the ledger.
	ListArrearsCommitments(ctx context.Context, arg ListArrearsCommitmentsParams) ([]ListArrearsCommitmentsRow, error)
	// Electricity deposit (Feature 2): a one-off refundable deposit, not a
	// monthly bill, so unlike garbage/water there is no "run" — just the
	// lease-start (or EnableElectricityDeposit) charge and whatever the tenant
	// has paid down since.
	// ListElectricityDeposits is every occupied unit's electricity deposit
	// line for the property tab: same shape as ListGarbageUnitsForPeriod (all
	// occupied units, not just the ones with a deposit — a unit with none
	// shows zero required, matching "Not billed" for garbage).
	ListElectricityDeposits(ctx context.Context, arg ListElectricityDepositsParams) ([]ListElectricityDepositsRow, error)
	// ListGarbageInvoices is the data for every unit billed by the period's
	// run. The fee is the charge actually posted; prior_balance is the GARBAGE
	// balance before the run.
	ListGarbageInvoices(ctx context.Context, arg ListGarbageInvoicesParams) ([]ListGarbageInvoicesRow, error)
	// Garbage billing (system-design.txt 3.9 step 4). No per-unit input: the
	// property's fixed fee is charged to every occupied unit. A garbage_runs
	// row is the run itself (locked on insert); its generated_at is the moment
	// an invoice's "previous balance B/F" is measured against.
	// ListGarbageUnitsForPeriod is every occupied unit with its tenant, current
	// GARBAGE balance, and whether its active lease has garbage billing turned
	// on: the preview grid lists all of these (toggled-off units show "Not
	// billed" rather than disappearing), and a run only charges the billed ones.
	ListGarbageUnitsForPeriod(ctx context.Context, arg ListGarbageUnitsForPeriodParams) ([]ListGarbageUnitsForPeriodRow, error)
	// ListLandlords pages a tenant's landlords. The sort key comes from the
	// handler's safelist (see ListProperties for the CASE-ordering idiom).
	ListLandlords(ctx context.Context, arg ListLandlordsParams) ([]ListLandlordsRow, error)
	ListLeasePayers(ctx context.Context, arg ListLeasePayersParams) ([]LeasePayer, error)
	// ListLeasesForUnit is a unit's lease history, newest first: the active lease
	// (at most one) and every terminated one.
	ListLeasesForUnit(ctx context.Context, arg ListLeasesForUnitParams) ([]Lease, error)
	// Read side of the append-only ledger, plus what a reversal (storno) and a
	// payment posting need. INSERT and SELECT only on the ledger tables; see
	// ledger_entries.sql for the writes and data.TestAppendOnlyQueries.
	// ListLedgerEntriesWithBalance pages one unit ledger for display: each entry
	// with the running balance after it (over the whole ledger, oldest first),
	// its transaction type and description (a reversal reason lives there), and
	// whether a later reversal has cancelled it. Newest first unless
	// sort = 'created_at'.
	ListLedgerEntriesWithBalance(ctx context.Context, arg ListLedgerEntriesWithBalanceParams) ([]ListLedgerEntriesWithBalanceRow, error)
	// ListPayerCandidates is every payer identity (phone or name) on the active
	// leases of units in the manager properties that use a PayHero channel.
	ListPayerCandidates(ctx context.Context, arg ListPayerCandidatesParams) ([]ListPayerCandidatesRow, error)
	// The manager review queue for inbound payments, and payment-intent upkeep
	// (system-design.txt 4.7, 4.8, 5). Tenant-scoped under RLS.
	// ListPaymentsForReview is everything a manager still has to look at: payments
	// that are unmatched, matched but not placed, or placed by the engine on a
	// guess that is not yet confirmed. Newest first.
	ListPaymentsForReview(ctx context.Context, arg ListPaymentsForReviewParams) ([]ListPaymentsForReviewRow, error)
	// ListPeriodPayments is every allocation of a payment received in the
	// period against a unit of the property: one line per allocation.
	ListPeriodPayments(ctx context.Context, arg ListPeriodPaymentsParams) ([]ListPeriodPaymentsRow, error)
	// ListProperties pages a tenant's properties, optionally filtered to one
	// landlord. The sort key comes from the handler's safelist; each CASE arm
	// is NULL unless selected, so only one ordering applies, with id as the
	// stable tie-breaker.
	ListProperties(ctx context.Context, arg ListPropertiesParams) ([]ListPropertiesRow, error)
	// The Properties card grid (system-design.txt 6.1, 10): per property, who
	// owns it, how many units are occupied and vacant, and how much rent has been
	// collected against what was expected this period. Tenant-scoped under RLS.
	// ListPropertySummaries has one row per live property of the manager.
	// Expected is what the occupied units owe for the period (the billed snapshot
	// if the month has been run, else the lease current rent). Collected is rent
	// received in the period in Kenya calendar dates, ignoring payments since
	// reversed; it counts every unit, since a payment can arrive after a move-out.
	ListPropertySummaries(ctx context.Context, arg ListPropertySummariesParams) ([]ListPropertySummariesRow, error)
	// ListReceiptsForPeriod is every (non-void, unless included) receipt for a
	// property's period, for the schedule's "generate receipts" PDF — a read
	// now, since receipts are issued at posting time, not batch-generated.
	ListReceiptsForPeriod(ctx context.Context, arg ListReceiptsForPeriodParams) ([]ListReceiptsForPeriodRow, error)
	// ListRentOverview is the property Rent tab: one row per occupied unit with
	// an active lease. Expected is the billed snapshot if the period has been
	// run, else the current lease rent. Paid is what was received in the period
	// (Kenya calendar dates) against the RENT ledger, ignoring payments that
	// have since been reversed. Balance is the derived RENT balance.
	ListRentOverview(ctx context.Context, arg ListRentOverviewParams) ([]ListRentOverviewRow, error)
	ListRentRunsForProperty(ctx context.Context, arg ListRentRunsForPropertyParams) ([]RentRun, error)
	// Monthly reports and receipts (system-design.txt 4.6, 4.10). Documents are
	// rendered on demand from the ledger; nothing here stores a PDF. Payment
	// dates are calendar dates in Kenya (Africa/Nairobi), not UTC, so a payment
	// made late on the 30th belongs to that month.
	// ListScheduleUnits is every unit of the property, with the tenant of the
	// lease that started most recently on or before the end of the period and
	// that lease's co-payers (newline-separated, since arrays would need
	// lib/pq in the generated code).
	ListScheduleUnits(ctx context.Context, arg ListScheduleUnitsParams) ([]ListScheduleUnitsRow, error)
	ListSubscriptionInvoices(ctx context.Context, arg ListSubscriptionInvoicesParams) ([]ListSubscriptionInvoicesRow, error)
	// Platform billing: a manager pays Willcoll a subscription through PayHero
	// (system-design.txt 3.6, 4.8, 7b). Plans are global; subscriptions and
	// their invoices are scoped to the manager (the tenant) under RLS.
	// ListSubscriptionPlans is what a manager may subscribe to: archived plans
	// never show, and a TEST plan (is_test) only shows when include_test is set
	// (the API sets it only in development — cmd/api's source of truth, not the
	// frontend).
	ListSubscriptionPlans(ctx context.Context, includeTest bool) ([]SubscriptionPlan, error)
	// ListUnitBalances is every derived ledger balance of one unit.
	ListUnitBalances(ctx context.Context, arg ListUnitBalancesParams) ([]ListUnitBalancesRow, error)
	// ListUnitCodes is every unit code on a property, for the bulk import to
	// report clashes before it writes anything.
	ListUnitCodes(ctx context.Context, arg ListUnitCodesParams) ([]string, error)
	// ListUnitLeaseRentHistory gives every lease a unit has had (any status),
	// so the caller can look up which rent_amount was in force for a given
	// past month rather than assuming today's rent applied throughout.
	ListUnitLeaseRentHistory(ctx context.Context, arg ListUnitLeaseRentHistoryParams) ([]ListUnitLeaseRentHistoryRow, error)
	// The public pay page (system-design.txt 4.7): who may pay for a unit, the
	// one-time codes that prove it, and the payer-facing view of the unit.
	// Tenant-scoped under RLS: the caller resolves the manager first.
	// ListUnitPayPhones is every phone on the unit active lease: the tenant and
	// any co-payers. Only these numbers may request a code.
	ListUnitPayPhones(ctx context.Context, arg ListUnitPayPhonesParams) ([]string, error)
	// ListUnitRentBalancesAsOf gives each unit's rent-account balance using only
	// entries posted before the cutoff (exclusive). Called twice by the NOTE:2
	// arrears/advance derivation — once with the previous period's end as
	// cutoff, once with this period's end — so the caller can diff the two
	// balances into "cleared" / "carried" / "new" arrears, and FIFO-derive
	// advance months from a positive balance at the later cutoff. A positive
	// balance is money owed (arrears); a negative balance is a credit (advance).
	ListUnitRentBalancesAsOf(ctx context.Context, arg ListUnitRentBalancesAsOfParams) ([]ListUnitRentBalancesAsOfRow, error)
	// Onboarding import (migration 000030): what a property already has, so an import
	// can be checked row by row before anything is written.
	// ListUnitStatesForProperty lists a property's units with whether each has an
	// active lease, keyed for lookup by unit code.
	ListUnitStatesForProperty(ctx context.Context, arg ListUnitStatesForPropertyParams) ([]ListUnitStatesForPropertyRow, error)
	// ListUnitsForProperty pages a property's units for the Units tab: each
	// with its current (active) lease's tenant and start date, for the unit
	// cards (system-design.txt 6.1). Optional filters:
	//   status        vacant | occupied
	//   tenant_query  a prefix tsquery built by the service layer (e.g.
	//                 'wanj:* & jane:*'), matched against the active lease's
	//                 tenant_name or any of its lease_payers' names. This is
	//                 the API's one full-text search that earns its keep
	//                 (Greenlight ch.9.5); the GIN indexes are in 000021.
	ListUnitsForProperty(ctx context.Context, arg ListUnitsForPropertyParams) ([]ListUnitsForPropertyRow, error)
	// Water billing (system-design.txt 3.9). water_readings rows are drafts
	// (locked = false) until a run locks them; only then are they charged.
	// Balances are never stored: the grid reads the current derived balance and
	// an invoice recomputes "previous balance B/F" from ledger entries created
	// strictly before the reading's locked_at, so it can be re-rendered at any
	// time without a stored PDF.
	// ListWaterGrid is the draft grid: one row per occupied unit, with its
	// saved reading for the period (if any), last period's closing reading as
	// the default "previous", and the unit's current WATER balance.
	ListWaterGrid(ctx context.Context, arg ListWaterGridParams) ([]ListWaterGridRow, error)
	// ListWaterInvoices is the data for every billed unit's water bill in a
	// period. The customer is the lease that started most recently on or before
	// the end of the period; prior_balance is the WATER balance before the run.
	ListWaterInvoices(ctx context.Context, arg ListWaterInvoicesParams) ([]ListWaterInvoicesRow, error)
	// ListWaterReadingsForRun is every reading of the property's period, the
	// input to a run.
	ListWaterReadingsForRun(ctx context.Context, arg ListWaterReadingsForRunParams) ([]ListWaterReadingsForRunRow, error)
	// LockReceiptCounter takes the property's counter row lock for the rest of
	// the transaction (SELECT ... FOR UPDATE, not MAX()+1), so two concurrent
	// postings for the same property can never read the same next_no.
	LockReceiptCounter(ctx context.Context, arg LockReceiptCounterParams) (int64, error)
	// LockWaterReading locks a draft as part of a run. Zero rows affected means
	// it was already locked.
	LockWaterReading(ctx context.Context, arg LockWaterReadingParams) (int64, error)
	// MarkSubscriptionInvoiceFailed records a failed or cancelled push, leaving a
	// paid invoice alone.
	MarkSubscriptionInvoiceFailed(ctx context.Context, arg MarkSubscriptionInvoiceFailedParams) (int64, error)
	// MarkSubscriptionInvoicePaid settles a pending or failed invoice. Zero rows
	// means it was already paid: a redelivered callback.
	MarkSubscriptionInvoicePaid(ctx context.Context, arg MarkSubscriptionInvoicePaidParams) (int64, error)
	// OnboardingCounts feeds the setup checklist in one round trip.
	OnboardingCounts(ctx context.Context, tenantID uuid.UUID) (OnboardingCountsRow, error)
	// PropertyHasActiveLeases blocks archiving a property people still live in.
	PropertyHasActiveLeases(ctx context.Context, arg PropertyHasActiveLeasesParams) (bool, error)
	// Units (system-design.txt 3.2). Tenant-scoped under RLS.
	// PropertyIsActive guards every write that takes a property_id: the FK
	// check ignores RLS, and archived properties (000019) take no new units.
	PropertyIsActive(ctx context.Context, arg PropertyIsActiveParams) (bool, error)
	PurgePayOTPs(ctx context.Context, arg PurgePayOTPsParams) error
	// ResolveChannelTenants finds the manager(s) whose properties use a PayHero
	// collections channel. More than one row means the channel is ambiguous and
	// the payment cannot be routed.
	ResolveChannelTenants(ctx context.Context, payheroChannelID *string) ([]uuid.UUID, error)
	// Payment ingestion (system-design.txt 4.8, 5).
	//
	// The first three queries are CROSS-TENANT lookups: an inbound webhook does
	// not know its tenant yet, so they run on the willcoll_admin pool (BYPASSRLS,
	// SELECT only), return only ids, and are called only by data.ResolverModel.
	// Everything after them is tenant-scoped under RLS.
	// ResolveIntentByReference finds the tenant and intent an STK reference
	// belongs to.
	ResolveIntentByReference(ctx context.Context, externalReference string) (ResolveIntentByReferenceRow, error)
	// ResolvePayTarget maps the public pay URL to its tenant, property and unit.
	ResolvePayTarget(ctx context.Context, arg ResolvePayTargetParams) (ResolvePayTargetRow, error)
	// ResolveSubscriptionInvoice is a CROSS-TENANT lookup for the subscriptions
	// webhook, which arrives with only the invoice reference. Runs on the
	// willcoll_admin pool (BYPASSRLS, SELECT only) and returns ids only.
	ResolveSubscriptionInvoice(ctx context.Context, id uuid.UUID) (ResolveSubscriptionInvoiceRow, error)
	// ResolveUnitQRToken is the public scan lookup: token to the unit's pay URL
	// parts, plus whether the code and its lease are still live. It joins only what
	// a redirect needs and returns nothing about the tenant.
	ResolveUnitQRToken(ctx context.Context, token string) (ResolveUnitQRTokenRow, error)
	// RevokeUnitQRCodesForLease retires the lease's live code. Zero rows means it
	// had none (already revoked, or never generated), which is fine.
	RevokeUnitQRCodesForLease(ctx context.Context, arg RevokeUnitQRCodesForLeaseParams) (int64, error)
	// SetLeaseElectricityDeposit records the amount an existing lease was
	// retroactively charged for its electricity deposit, in the same
	// transaction as the charge itself (EnableElectricityDeposit). Not part of
	// UpdateLease: like the other deposits, this is a one-time posting, not an
	// ordinary edit.
	SetLeaseElectricityDeposit(ctx context.Context, arg SetLeaseElectricityDepositParams) error
	// SetManagerStatus moves a manager from one status to another: the Super
	// Admin's suspend and reinstate (/v1/admin/managers/:id/suspend|reinstate).
	// The from_status guard makes each move explicit: zero rows means the
	// manager doesn't exist or wasn't in from_status.
	SetManagerStatus(ctx context.Context, arg SetManagerStatusParams) (int32, error)
	// SetPaymentIntentCheckout records PayHero checkout request id for a push.
	SetPaymentIntentCheckout(ctx context.Context, arg SetPaymentIntentCheckoutParams) error
	// SetPaymentIntentStatus moves an intent to completed, expired or failed.
	SetPaymentIntentStatus(ctx context.Context, arg SetPaymentIntentStatusParams) error
	// SetPaymentMatch records where a payment landed: its status, unit and
	// intent, whether the engine applied it on a guess a manager should confirm,
	// and a note saying why it needs review.
	SetPaymentMatch(ctx context.Context, arg SetPaymentMatchParams) error
	// SetPropertyPrintTheme replaces the property's print theme (NULL clears
	// it), with the same optimistic version check as UpdateProperty.
	SetPropertyPrintTheme(ctx context.Context, arg SetPropertyPrintThemeParams) (int32, error)
	// SetUnitStatus is the only way a unit's status changes: occupied when a
	// lease starts (or is reactivated), vacant when it's terminated, in the
	// same transaction as that lease write (data.LeaseModel). It bumps version
	// so a unit edit based on the old row gets an edit conflict.
	SetUnitStatus(ctx context.Context, arg SetUnitStatusParams) error
	// SumPaymentAllocations backs the zero-sum assertion (system-design.txt
	// 3.8): what has been allocated from one payment so far.
	SumPaymentAllocations(ctx context.Context, arg SumPaymentAllocationsParams) (moneyfmt.Money, error)
	// UpdateLandlord: optimistic concurrency; zero rows means the version moved on.
	UpdateLandlord(ctx context.Context, arg UpdateLandlordParams) (int32, error)
	// UpdateLease covers edits and termination. Deposits and start_date are
	// deliberately not updatable: they were posted to the ledger at lease
	// start, and changing them is a storno adjustment, not an edit.
	UpdateLease(ctx context.Context, arg UpdateLeaseParams) (int32, error)
	// UpdateLeaseRentAmount sets the expected monthly rent on an active lease.
	// It posts nothing: rent runs copy this amount when a month is billed, so
	// already-billed periods are unaffected. Zero rows means the lease is not
	// active (or is gone).
	UpdateLeaseRentAmount(ctx context.Context, arg UpdateLeaseRentAmountParams) (int32, error)
	// UpdateManager: optimistic concurrency; zero rows means the version moved on.
	UpdateManager(ctx context.Context, arg UpdateManagerParams) (int32, error)
	// UpdateProperty applies optimistic concurrency control: zero rows (and so
	// sql.ErrNoRows) means the version moved on since the caller read it.
	UpdateProperty(ctx context.Context, arg UpdatePropertyParams) (int32, error)
	// UpdateUnit: optimistic concurrency; zero rows means the version moved on.
	// status is deliberately not settable here: it follows the unit's lease
	// (SetUnitStatus), so a manual edit can never contradict the lease record.
	UpdateUnit(ctx context.Context, arg UpdateUnitParams) (int32, error)
	// UpsertAdmin provisions the one Super Admin from configuration at
	// startup. It conflicts on is_singleton (000023), so there is only ever
	// one row: a changed ADMIN_EMAIL updates it in place, keeping its id.
	UpsertAdmin(ctx context.Context, arg UpsertAdminParams) (Admin, error)
	UpsertPropertyMeterReading(ctx context.Context, arg UpsertPropertyMeterReadingParams) error
	UpsertReportConfirmation(ctx context.Context, arg UpsertReportConfirmationParams) (UpsertReportConfirmationRow, error)
	// UpsertReportNotes saves the period's NOTE: 2 lines, creating the row
	// (with empty totals) if the report has not been generated yet.
	UpsertReportNotes(ctx context.Context, arg UpsertReportNotesParams) error
	// UpsertReportTotals records the totals snapshot when a report is
	// generated, keeping any notes already saved.
	UpsertReportTotals(ctx context.Context, arg UpsertReportTotalsParams) error
	// UpsertWaterReading saves a draft. The WHERE on the conflict arm makes a
	// locked reading immutable: zero rows (sql.ErrNoRows) means it is locked.
	// Callers verify the unit belongs to the property first.
	UpsertWaterReading(ctx context.Context, arg UpsertWaterReadingParams) (uuid.UUID, error)
	// VoidReceipt marks a receipt void when its allocation is reversed. The
	// number is never reused and the row is never deleted — the PDF renders
	// "VOID" over it instead.
	VoidReceipt(ctx context.Context, arg VoidReceiptParams) error
}

var _ Querier = (*Queries)(nil)
