// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rent_runs.sql

package sqlc

import (
	"context"
	"time"

	"github.com/codercollo/willcoll/backend/pkg/moneyfmt"
	"github.com/google/uuid"
)

const getActiveLeaseByUnit = `-- name: GetActiveLeaseByUnit :one

SELECT id, tenant_id, unit_id, tenant_name, primary_phone, rent_amount, rent_deposit_amount, water_deposit_amount, start_date, end_date, status, created_at, version, garbage_billed, electricity_deposit_amount FROM leases
WHERE tenant_id = $1 AND unit_id = $2 AND status = 'active'
`

type GetActiveLeaseByUnitParams struct {
	TenantID uuid.UUID
	UnitID   uuid.UUID
}

// Rent (system-design.txt 2, 3.3). Expected rent is leases.rent_amount; a
// rent run copies it into rent_runs.amount_snapshot when a month is billed,
// and UNIQUE (unit_id, period) is what stops a period being billed twice.
// GetActiveLeaseByUnit is the current lease of a unit (at most one: the
// partial unique index on active leases).
func (q *Queries) GetActiveLeaseByUnit(ctx context.Context, arg GetActiveLeaseByUnitParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, getActiveLeaseByUnit, arg.TenantID, arg.UnitID)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnitID,
		&i.TenantName,
		&i.PrimaryPhone,
		&i.RentAmount,
		&i.RentDepositAmount,
		&i.WaterDepositAmount,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.Version,
		&i.GarbageBilled,
		&i.ElectricityDepositAmount,
	)
	return i, err
}

const getRentRun = `-- name: GetRentRun :one
SELECT id, tenant_id, unit_id, period, amount_snapshot, locked, generated_at FROM rent_runs
WHERE tenant_id = $1 AND unit_id = $2 AND period = $3
`

type GetRentRunParams struct {
	TenantID uuid.UUID
	UnitID   uuid.UUID
	Period   time.Time
}

func (q *Queries) GetRentRun(ctx context.Context, arg GetRentRunParams) (RentRun, error) {
	row := q.db.QueryRowContext(ctx, getRentRun, arg.TenantID, arg.UnitID, arg.Period)
	var i RentRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnitID,
		&i.Period,
		&i.AmountSnapshot,
		&i.Locked,
		&i.GeneratedAt,
	)
	return i, err
}

const insertRentRun = `-- name: InsertRentRun :one
INSERT INTO rent_runs (tenant_id, unit_id, period, amount_snapshot, locked)
VALUES ($1, $2, $3, $4, true)
ON CONFLICT (unit_id, period) DO NOTHING
RETURNING id
`

type InsertRentRunParams struct {
	TenantID       uuid.UUID
	UnitID         uuid.UUID
	Period         time.Time
	AmountSnapshot moneyfmt.Money
}

// InsertRentRun records the run, already locked: rent has no draft step.
// Zero rows (sql.ErrNoRows) means the unit is already billed for the period.
func (q *Queries) InsertRentRun(ctx context.Context, arg InsertRentRunParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertRentRun,
		arg.TenantID,
		arg.UnitID,
		arg.Period,
		arg.AmountSnapshot,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listActiveLeasesForProperty = `-- name: ListActiveLeasesForProperty :many
SELECT
    u.id AS unit_id,
    u.unit_code,
    l.id AS lease_id,
    l.tenant_name,
    l.rent_amount,
    l.start_date
FROM leases l
INNER JOIN units u ON u.id = l.unit_id
WHERE l.tenant_id = $1
  AND u.property_id = $2
  AND l.status = 'active'
ORDER BY u.unit_code
`

type ListActiveLeasesForPropertyParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
}

type ListActiveLeasesForPropertyRow struct {
	UnitID     uuid.UUID
	UnitCode   string
	LeaseID    uuid.UUID
	TenantName string
	RentAmount moneyfmt.Money
	StartDate  time.Time
}

// ListActiveLeasesForProperty is every active lease on the property with its
// unit: the source of expected rent for the rent schedule and monthly runs.
func (q *Queries) ListActiveLeasesForProperty(ctx context.Context, arg ListActiveLeasesForPropertyParams) ([]ListActiveLeasesForPropertyRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveLeasesForProperty, arg.TenantID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveLeasesForPropertyRow{}
	for rows.Next() {
		var i ListActiveLeasesForPropertyRow
		if err := rows.Scan(
			&i.UnitID,
			&i.UnitCode,
			&i.LeaseID,
			&i.TenantName,
			&i.RentAmount,
			&i.StartDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRentOverview = `-- name: ListRentOverview :many
SELECT
    u.id AS unit_id,
    u.unit_code,
    l.tenant_name,
    COALESCE(rr.amount_snapshot, l.rent_amount)::numeric(12,2) AS expected,
    (rr.id IS NOT NULL)::boolean AS billed,
    COALESCE((
        SELECT SUM(pa.amount)
        FROM payment_allocations pa
        INNER JOIN payments p ON p.id = pa.payment_id
        INNER JOIN ledger_accounts la ON la.id = pa.ledger_account_id
        WHERE la.unit_id = u.id
          AND la.type = 'RENT'
          AND (p.received_at AT TIME ZONE 'Africa/Nairobi')::date >= $1::date
          AND (p.received_at AT TIME ZONE 'Africa/Nairobi')::date < ($1::date + interval '1 month')
          AND NOT EXISTS (
              SELECT 1 FROM ledger_entries r
              WHERE r.reference_type = 'reversal' AND r.reference_id = pa.ledger_entry_id
          )
    ), 0)::numeric(12,2) AS paid,
    COALESCE(b.balance, 0)::numeric(12,2) AS balance
FROM units u
INNER JOIN leases l ON l.unit_id = u.id AND l.status = 'active'
LEFT JOIN rent_runs rr ON rr.unit_id = u.id AND rr.period = $1
LEFT JOIN LATERAL (
    SELECT ub.balance FROM unit_ledger_balances ub
    WHERE ub.unit_id = u.id AND ub.type = 'RENT'
) b ON true
WHERE u.tenant_id = $2 AND u.property_id = $3 AND u.status = 'occupied'
ORDER BY u.unit_code
`

type ListRentOverviewParams struct {
	Period     time.Time
	TenantID   uuid.UUID
	PropertyID uuid.UUID
}

type ListRentOverviewRow struct {
	UnitID     uuid.UUID
	UnitCode   string
	TenantName string
	Expected   moneyfmt.Money
	Billed     bool
	Paid       moneyfmt.Money
	Balance    moneyfmt.Money
}

// ListRentOverview is the property Rent tab: one row per occupied unit with
// an active lease. Expected is the billed snapshot if the period has been
// run, else the current lease rent. Paid is what was received in the period
// (Kenya calendar dates) against the RENT ledger, ignoring payments that
// have since been reversed. Balance is the derived RENT balance.
func (q *Queries) ListRentOverview(ctx context.Context, arg ListRentOverviewParams) ([]ListRentOverviewRow, error) {
	rows, err := q.db.QueryContext(ctx, listRentOverview, arg.Period, arg.TenantID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRentOverviewRow{}
	for rows.Next() {
		var i ListRentOverviewRow
		if err := rows.Scan(
			&i.UnitID,
			&i.UnitCode,
			&i.TenantName,
			&i.Expected,
			&i.Billed,
			&i.Paid,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRentRunsForProperty = `-- name: ListRentRunsForProperty :many
SELECT rr.id, rr.tenant_id, rr.unit_id, rr.period, rr.amount_snapshot, rr.locked, rr.generated_at
FROM rent_runs rr
INNER JOIN units u ON u.id = rr.unit_id
WHERE rr.tenant_id = $1 AND u.property_id = $2 AND rr.period = $3
`

type ListRentRunsForPropertyParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
	Period     time.Time
}

func (q *Queries) ListRentRunsForProperty(ctx context.Context, arg ListRentRunsForPropertyParams) ([]RentRun, error) {
	rows, err := q.db.QueryContext(ctx, listRentRunsForProperty, arg.TenantID, arg.PropertyID, arg.Period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RentRun{}
	for rows.Next() {
		var i RentRun
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UnitID,
			&i.Period,
			&i.AmountSnapshot,
			&i.Locked,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLeaseRentAmount = `-- name: UpdateLeaseRentAmount :one
UPDATE leases
SET rent_amount = $1,
    version = version + 1
WHERE tenant_id = $2 AND id = $3 AND status = 'active'
RETURNING version
`

type UpdateLeaseRentAmountParams struct {
	RentAmount moneyfmt.Money
	TenantID   uuid.UUID
	ID         uuid.UUID
}

// UpdateLeaseRentAmount sets the expected monthly rent on an active lease.
// It posts nothing: rent runs copy this amount when a month is billed, so
// already-billed periods are unaffected. Zero rows means the lease is not
// active (or is gone).
func (q *Queries) UpdateLeaseRentAmount(ctx context.Context, arg UpdateLeaseRentAmountParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, updateLeaseRentAmount, arg.RentAmount, arg.TenantID, arg.ID)
	var version int32
	err := row.Scan(&version)
	return version, err
}
