// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report_confirmations.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const archiveReportConfirmation = `-- name: ArchiveReportConfirmation :exec
INSERT INTO report_confirmation_history (tenant_id, property_id, period, totals_checksum, note_lines, confirmed_by, confirmed_at)
SELECT rc.tenant_id, rc.property_id, rc.period, rc.totals_checksum, rc.note_lines, rc.confirmed_by, rc.confirmed_at
FROM report_confirmations rc
WHERE rc.tenant_id = $1 AND rc.property_id = $2 AND rc.period = $3
`

type ArchiveReportConfirmationParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
	Period     time.Time
}

// Copies the current confirmation row (if any) into history before a
// re-confirm overwrites it. A no-op insert-select when nothing exists yet.
func (q *Queries) ArchiveReportConfirmation(ctx context.Context, arg ArchiveReportConfirmationParams) error {
	_, err := q.db.ExecContext(ctx, archiveReportConfirmation, arg.TenantID, arg.PropertyID, arg.Period)
	return err
}

const getReportConfirmation = `-- name: GetReportConfirmation :one

SELECT id, totals_checksum, note_lines, confirmed_by, confirmed_at
FROM report_confirmations
WHERE tenant_id = $1 AND property_id = $2 AND period = $3
`

type GetReportConfirmationParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
	Period     time.Time
}

type GetReportConfirmationRow struct {
	ID             uuid.UUID
	TotalsChecksum string
	NoteLines      json.RawMessage
	ConfirmedBy    uuid.UUID
	ConfirmedAt    time.Time
}

// Period confirmation gate. The checksum is a hash of the confirmed totals;
// staleness is detected by recomputing it on every PDF request and
// comparing, not by a trigger (system-design.txt PDF confirmation addendum).
func (q *Queries) GetReportConfirmation(ctx context.Context, arg GetReportConfirmationParams) (GetReportConfirmationRow, error) {
	row := q.db.QueryRowContext(ctx, getReportConfirmation, arg.TenantID, arg.PropertyID, arg.Period)
	var i GetReportConfirmationRow
	err := row.Scan(
		&i.ID,
		&i.TotalsChecksum,
		&i.NoteLines,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
	)
	return i, err
}

const upsertReportConfirmation = `-- name: UpsertReportConfirmation :one
INSERT INTO report_confirmations (tenant_id, property_id, period, totals_checksum, note_lines, confirmed_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (property_id, period) DO UPDATE
SET totals_checksum = EXCLUDED.totals_checksum,
    note_lines = EXCLUDED.note_lines,
    confirmed_by = EXCLUDED.confirmed_by,
    confirmed_at = now()
RETURNING id, confirmed_at
`

type UpsertReportConfirmationParams struct {
	TenantID       uuid.UUID
	PropertyID     uuid.UUID
	Period         time.Time
	TotalsChecksum string
	NoteLines      json.RawMessage
	ConfirmedBy    uuid.UUID
}

type UpsertReportConfirmationRow struct {
	ID          uuid.UUID
	ConfirmedAt time.Time
}

func (q *Queries) UpsertReportConfirmation(ctx context.Context, arg UpsertReportConfirmationParams) (UpsertReportConfirmationRow, error) {
	row := q.db.QueryRowContext(ctx, upsertReportConfirmation,
		arg.TenantID,
		arg.PropertyID,
		arg.Period,
		arg.TotalsChecksum,
		arg.NoteLines,
		arg.ConfirmedBy,
	)
	var i UpsertReportConfirmationRow
	err := row.Scan(&i.ID, &i.ConfirmedAt)
	return i, err
}
