// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/codercollo/willcoll/backend/pkg/moneyfmt"
	"github.com/google/uuid"
	"github.com/lib/pq"
)

const advanceReceiptCounter = `-- name: AdvanceReceiptCounter :exec
UPDATE receipt_counters SET next_no = next_no + 1
WHERE tenant_id = $1 AND property_id = $2
`

type AdvanceReceiptCounterParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
}

// AdvanceReceiptCounter hands out the locked next_no and increments it.
// Call after LockReceiptCounter, in the same transaction.
func (q *Queries) AdvanceReceiptCounter(ctx context.Context, arg AdvanceReceiptCounterParams) error {
	_, err := q.db.ExecContext(ctx, advanceReceiptCounter, arg.TenantID, arg.PropertyID)
	return err
}

const createReceipt = `-- name: CreateReceipt :one
INSERT INTO receipts (tenant_id, property_id, unit_id, receipt_no, period, payment_allocation_id, ledger_type, arrears_note, settled_period)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, unit_id, receipt_no, payment_ids, period, generated_at, property_id, payment_allocation_id, ledger_type, arrears_note, voided_at, void_reason, settled_period
`

type CreateReceiptParams struct {
	TenantID            uuid.UUID
	PropertyID          uuid.UUID
	UnitID              uuid.UUID
	ReceiptNo           int64
	Period              time.Time
	PaymentAllocationID *uuid.UUID
	LedgerType          *string
	ArrearsNote         *string
	SettledPeriod       *time.Time
}

// CreateReceipt issues one allocation's receipt. payment_allocation_id is
// unique, so a retried posting that (however it happened) reused the same
// allocation id conflicts here instead of consuming a second number —
// callers check for that conflict and reuse GetReceiptByAllocation's row
// instead of treating it as an error.
func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, createReceipt,
		arg.TenantID,
		arg.PropertyID,
		arg.UnitID,
		arg.ReceiptNo,
		arg.Period,
		arg.PaymentAllocationID,
		arg.LedgerType,
		arg.ArrearsNote,
		arg.SettledPeriod,
	)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnitID,
		&i.ReceiptNo,
		pq.Array(&i.PaymentIds),
		&i.Period,
		&i.GeneratedAt,
		&i.PropertyID,
		&i.PaymentAllocationID,
		&i.LedgerType,
		&i.ArrearsNote,
		&i.VoidedAt,
		&i.VoidReason,
		&i.SettledPeriod,
	)
	return i, err
}

const createReceiptCounter = `-- name: CreateReceiptCounter :exec
INSERT INTO receipt_counters (tenant_id, property_id, next_no)
VALUES ($1, $2, 1)
`

type CreateReceiptCounterParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
}

// CreateReceiptCounter is called once, when a property is created (not
// lazily), so every property always has a counter row before its first
// payment.
func (q *Queries) CreateReceiptCounter(ctx context.Context, arg CreateReceiptCounterParams) error {
	_, err := q.db.ExecContext(ctx, createReceiptCounter, arg.TenantID, arg.PropertyID)
	return err
}

const getPlotMeterReadingRow = `-- name: GetPlotMeterReadingRow :one
SELECT previous_reading, current_reading, units_consumed, reading_date
FROM property_meter_readings
WHERE tenant_id = $1 AND property_id = $2 AND period = $3
`

type GetPlotMeterReadingRowParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
	Period     time.Time
}

type GetPlotMeterReadingRowRow struct {
	PreviousReading *moneyfmt.Money
	CurrentReading  moneyfmt.Money
	UnitsConsumed   *moneyfmt.Money
	ReadingDate     time.Time
}

// GetPlotMeterReadingRow is the period's own saved plot-meter row, if any.
// No row (sql.ErrNoRows) means the period hasn't been read yet.
func (q *Queries) GetPlotMeterReadingRow(ctx context.Context, arg GetPlotMeterReadingRowParams) (GetPlotMeterReadingRowRow, error) {
	row := q.db.QueryRowContext(ctx, getPlotMeterReadingRow, arg.TenantID, arg.PropertyID, arg.Period)
	var i GetPlotMeterReadingRowRow
	err := row.Scan(
		&i.PreviousReading,
		&i.CurrentReading,
		&i.UnitsConsumed,
		&i.ReadingDate,
	)
	return i, err
}

const getPreviousPropertyMeterReading = `-- name: GetPreviousPropertyMeterReading :one
SELECT current_reading FROM property_meter_readings
WHERE tenant_id = $1 AND property_id = $2 AND period < $3
ORDER BY period DESC
LIMIT 1
`

type GetPreviousPropertyMeterReadingParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
	Period     time.Time
}

// GetPreviousPropertyMeterReading is the last period before this one that
// was read, for the reading form's "Previous: X" default (same shape as
// ListWaterGrid's per-unit default). No row (sql.ErrNoRows) means the
// property has never been read before — Previous stays editable.
func (q *Queries) GetPreviousPropertyMeterReading(ctx context.Context, arg GetPreviousPropertyMeterReadingParams) (moneyfmt.Money, error) {
	row := q.db.QueryRowContext(ctx, getPreviousPropertyMeterReading, arg.TenantID, arg.PropertyID, arg.Period)
	var current_reading moneyfmt.Money
	err := row.Scan(&current_reading)
	return current_reading, err
}

const getPropertyMeterReading = `-- name: GetPropertyMeterReading :one
SELECT units_consumed FROM property_meter_readings
WHERE tenant_id = $1 AND property_id = $2 AND period = $3
  AND units_consumed IS NOT NULL
`

type GetPropertyMeterReadingParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
	Period     time.Time
}

// GetPropertyMeterReading is the period's plot-meter units used, for
// NOTE:1's storage-deviation line. No row, or a row with no previous
// reading yet, means units used is unknown; the line is omitted, never
// printed as zero.
func (q *Queries) GetPropertyMeterReading(ctx context.Context, arg GetPropertyMeterReadingParams) (*moneyfmt.Money, error) {
	row := q.db.QueryRowContext(ctx, getPropertyMeterReading, arg.TenantID, arg.PropertyID, arg.Period)
	var units_consumed *moneyfmt.Money
	err := row.Scan(&units_consumed)
	return units_consumed, err
}

const getReceiptByAllocation = `-- name: GetReceiptByAllocation :one
SELECT id, tenant_id, unit_id, receipt_no, payment_ids, period, generated_at, property_id, payment_allocation_id, ledger_type, arrears_note, voided_at, void_reason, settled_period FROM receipts WHERE tenant_id = $1 AND payment_allocation_id = $2
`

type GetReceiptByAllocationParams struct {
	TenantID            uuid.UUID
	PaymentAllocationID *uuid.UUID
}

// GetReceiptByAllocation is the idempotency read: a retried posting that
// names the same allocation gets this row back instead of a new receipt.
func (q *Queries) GetReceiptByAllocation(ctx context.Context, arg GetReceiptByAllocationParams) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, getReceiptByAllocation, arg.TenantID, arg.PaymentAllocationID)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UnitID,
		&i.ReceiptNo,
		pq.Array(&i.PaymentIds),
		&i.Period,
		&i.GeneratedAt,
		&i.PropertyID,
		&i.PaymentAllocationID,
		&i.LedgerType,
		&i.ArrearsNote,
		&i.VoidedAt,
		&i.VoidReason,
		&i.SettledPeriod,
	)
	return i, err
}

const getReport = `-- name: GetReport :one
SELECT id, totals, notes, generated_at
FROM reports
WHERE tenant_id = $1 AND property_id = $2 AND period = $3
`

type GetReportParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
	Period     time.Time
}

type GetReportRow struct {
	ID          uuid.UUID
	Totals      json.RawMessage
	Notes       json.RawMessage
	GeneratedAt time.Time
}

// GetReport reads the period's report row (its manager-typed notes).
func (q *Queries) GetReport(ctx context.Context, arg GetReportParams) (GetReportRow, error) {
	row := q.db.QueryRowContext(ctx, getReport, arg.TenantID, arg.PropertyID, arg.Period)
	var i GetReportRow
	err := row.Scan(
		&i.ID,
		&i.Totals,
		&i.Notes,
		&i.GeneratedAt,
	)
	return i, err
}

const getWaterSummary = `-- name: GetWaterSummary :one
SELECT
    COALESCE(SUM(wr.units_consumed), 0)::numeric(12,2) AS units_consumed,
    (COALESCE(SUM(wr.units_consumed), 0) * $1::numeric(12,2))::numeric(12,2) AS expected,
    COALESCE(SUM(wr.amount), 0)::numeric(12,2) AS billed
FROM water_readings wr
INNER JOIN units u ON u.id = wr.unit_id
WHERE wr.tenant_id = $2
  AND u.property_id = $3
  AND wr.period = $4
  AND wr.locked = true
`

type GetWaterSummaryParams struct {
	Rate       moneyfmt.Money
	TenantID   uuid.UUID
	PropertyID uuid.UUID
	Period     time.Time
}

type GetWaterSummaryRow struct {
	UnitsConsumed moneyfmt.Money
	Expected      moneyfmt.Money
	Billed        moneyfmt.Money
}

// GetWaterSummary totals the period's locked readings. Expected is the
// consumed units at the property's current rate; billed is what was actually
// charged (readings can carry a per-run rate), so the difference is the
// "deviation" on the schedule.
func (q *Queries) GetWaterSummary(ctx context.Context, arg GetWaterSummaryParams) (GetWaterSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getWaterSummary,
		arg.Rate,
		arg.TenantID,
		arg.PropertyID,
		arg.Period,
	)
	var i GetWaterSummaryRow
	err := row.Scan(&i.UnitsConsumed, &i.Expected, &i.Billed)
	return i, err
}

const listPeriodPayments = `-- name: ListPeriodPayments :many
SELECT
    la.unit_id,
    la.type AS ledger_type,
    (p.received_at AT TIME ZONE 'Africa/Nairobi')::date AS paid_on,
    pa.amount,
    p.id AS payment_id,
    p.source
FROM payment_allocations pa
INNER JOIN payments p ON p.id = pa.payment_id
INNER JOIN ledger_accounts la ON la.id = pa.ledger_account_id
INNER JOIN units u ON u.id = la.unit_id
WHERE pa.tenant_id = $1
  AND u.property_id = $2
  AND (p.received_at AT TIME ZONE 'Africa/Nairobi')::date >= $3::date
  AND (p.received_at AT TIME ZONE 'Africa/Nairobi')::date < ($3::date + interval '1 month')
  AND NOT EXISTS (
      SELECT 1 FROM ledger_entries r
      WHERE r.reference_type = 'reversal' AND r.reference_id = pa.ledger_entry_id
  )
ORDER BY u.unit_code, paid_on, p.received_at, pa.created_at
`

type ListPeriodPaymentsParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
	Period     time.Time
}

type ListPeriodPaymentsRow struct {
	UnitID     uuid.UUID
	LedgerType string
	PaidOn     time.Time
	Amount     moneyfmt.Money
	PaymentID  uuid.UUID
	Source     string
}

// ListPeriodPayments is every allocation of a payment received in the
// period against a unit of the property: one line per allocation.
func (q *Queries) ListPeriodPayments(ctx context.Context, arg ListPeriodPaymentsParams) ([]ListPeriodPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPeriodPayments, arg.TenantID, arg.PropertyID, arg.Period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPeriodPaymentsRow{}
	for rows.Next() {
		var i ListPeriodPaymentsRow
		if err := rows.Scan(
			&i.UnitID,
			&i.LedgerType,
			&i.PaidOn,
			&i.Amount,
			&i.PaymentID,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiptsForPeriod = `-- name: ListReceiptsForPeriod :many
SELECT r.id, r.tenant_id, r.unit_id, r.receipt_no, r.payment_ids, r.period, r.generated_at, r.property_id, r.payment_allocation_id, r.ledger_type, r.arrears_note, r.voided_at, r.void_reason, r.settled_period, u.unit_code, COALESCE(l.tenant_name, '')::text AS tenant_name, COALESCE(l.payer_names, '')::text AS payer_names,
    p.mpesa_receipt, p.source, p.received_at, pa.amount
FROM receipts r
INNER JOIN units u ON u.id = r.unit_id
INNER JOIN payment_allocations pa ON pa.id = r.payment_allocation_id
INNER JOIN payments p ON p.id = pa.payment_id
LEFT JOIN LATERAL (
    SELECT
        le.tenant_name,
        (SELECT string_agg(x.name, chr(10)) FROM (SELECT lp.name FROM lease_payers lp WHERE lp.lease_id = le.id ORDER BY lp.name) x) AS payer_names
    FROM leases le
    WHERE le.unit_id = u.id AND le.start_date <= r.period
    ORDER BY le.start_date DESC
    LIMIT 1
) l ON true
WHERE r.tenant_id = $1 AND r.property_id = $2 AND r.period = $3
  AND ($4::uuid IS NULL OR r.unit_id = $4::uuid)
ORDER BY u.unit_code, r.receipt_no
`

type ListReceiptsForPeriodParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
	Period     time.Time
	UnitID     *uuid.UUID
}

type ListReceiptsForPeriodRow struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	UnitID              uuid.UUID
	ReceiptNo           int64
	PaymentIds          []uuid.UUID
	Period              time.Time
	GeneratedAt         time.Time
	PropertyID          uuid.UUID
	PaymentAllocationID *uuid.UUID
	LedgerType          *string
	ArrearsNote         *string
	VoidedAt            *time.Time
	VoidReason          *string
	SettledPeriod       *time.Time
	UnitCode            string
	TenantName          string
	PayerNames          string
	MpesaReceipt        string
	Source              string
	ReceivedAt          time.Time
	Amount              moneyfmt.Money
}

// ListReceiptsForPeriod is every (non-void, unless included) receipt for a
// property's period, for the schedule's "generate receipts" PDF — a read
// now, since receipts are issued at posting time, not batch-generated.
func (q *Queries) ListReceiptsForPeriod(ctx context.Context, arg ListReceiptsForPeriodParams) ([]ListReceiptsForPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, listReceiptsForPeriod,
		arg.TenantID,
		arg.PropertyID,
		arg.Period,
		arg.UnitID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReceiptsForPeriodRow{}
	for rows.Next() {
		var i ListReceiptsForPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UnitID,
			&i.ReceiptNo,
			pq.Array(&i.PaymentIds),
			&i.Period,
			&i.GeneratedAt,
			&i.PropertyID,
			&i.PaymentAllocationID,
			&i.LedgerType,
			&i.ArrearsNote,
			&i.VoidedAt,
			&i.VoidReason,
			&i.SettledPeriod,
			&i.UnitCode,
			&i.TenantName,
			&i.PayerNames,
			&i.MpesaReceipt,
			&i.Source,
			&i.ReceivedAt,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleUnits = `-- name: ListScheduleUnits :many

SELECT
    u.id AS unit_id,
    u.unit_code,
    u.status,
    COALESCE(l.tenant_name, '')::text AS tenant_name,
    COALESCE(l.payer_names, '')::text AS payer_names,
    COALESCE(l.garbage_billed, false) AS garbage_billed
FROM units u
LEFT JOIN LATERAL (
    SELECT
        le.tenant_name,
        le.garbage_billed,
        (SELECT string_agg(x.name, chr(10)) FROM (SELECT lp.name FROM lease_payers lp WHERE lp.lease_id = le.id ORDER BY lp.name) x) AS payer_names
    FROM leases le
    WHERE le.unit_id = u.id AND le.start_date < ($1::date + interval '1 month')
    ORDER BY le.start_date DESC
    LIMIT 1
) l ON true
WHERE u.tenant_id = $2 AND u.property_id = $3
ORDER BY u.unit_code
`

type ListScheduleUnitsParams struct {
	Period     time.Time
	TenantID   uuid.UUID
	PropertyID uuid.UUID
}

type ListScheduleUnitsRow struct {
	UnitID        uuid.UUID
	UnitCode      string
	Status        string
	TenantName    string
	PayerNames    string
	GarbageBilled bool
}

// Monthly reports and receipts (system-design.txt 4.6, 4.10). Documents are
// rendered on demand from the ledger; nothing here stores a PDF. Payment
// dates are calendar dates in Kenya (Africa/Nairobi), not UTC, so a payment
// made late on the 30th belongs to that month.
// ListScheduleUnits is every unit of the property, with the tenant of the
// lease that started most recently on or before the end of the period and
// that lease's co-payers (newline-separated, since arrays would need
// lib/pq in the generated code).
func (q *Queries) ListScheduleUnits(ctx context.Context, arg ListScheduleUnitsParams) ([]ListScheduleUnitsRow, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleUnits, arg.Period, arg.TenantID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleUnitsRow{}
	for rows.Next() {
		var i ListScheduleUnitsRow
		if err := rows.Scan(
			&i.UnitID,
			&i.UnitCode,
			&i.Status,
			&i.TenantName,
			&i.PayerNames,
			&i.GarbageBilled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitLeaseRentHistory = `-- name: ListUnitLeaseRentHistory :many
SELECT unit_id, rent_amount, start_date, end_date
FROM leases
WHERE tenant_id = $1 AND unit_id = ANY($2::uuid[])
ORDER BY unit_id, start_date
`

type ListUnitLeaseRentHistoryParams struct {
	TenantID uuid.UUID
	UnitIds  []uuid.UUID
}

type ListUnitLeaseRentHistoryRow struct {
	UnitID     uuid.UUID
	RentAmount moneyfmt.Money
	StartDate  time.Time
	EndDate    *time.Time
}

// ListUnitLeaseRentHistory gives every lease a unit has had (any status),
// so the caller can look up which rent_amount was in force for a given
// past month rather than assuming today's rent applied throughout.
func (q *Queries) ListUnitLeaseRentHistory(ctx context.Context, arg ListUnitLeaseRentHistoryParams) ([]ListUnitLeaseRentHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnitLeaseRentHistory, arg.TenantID, pq.Array(arg.UnitIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnitLeaseRentHistoryRow{}
	for rows.Next() {
		var i ListUnitLeaseRentHistoryRow
		if err := rows.Scan(
			&i.UnitID,
			&i.RentAmount,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitRentBalancesAsOf = `-- name: ListUnitRentBalancesAsOf :many
SELECT
    la.unit_id,
    COALESCE(SUM(
        CASE
            WHEN le.direction = 'DEBIT' THEN le.amount
            WHEN le.direction = 'CREDIT' THEN -le.amount
        END
    ), 0)::numeric(12,2) AS balance
FROM ledger_accounts la
INNER JOIN units u ON u.id = la.unit_id
LEFT JOIN ledger_entries le ON le.ledger_account_id = la.id AND le.created_at < $1::timestamptz
WHERE la.tenant_id = $2 AND u.property_id = $3 AND la.type = 'RENT'
GROUP BY la.unit_id
`

type ListUnitRentBalancesAsOfParams struct {
	AsOf       time.Time
	TenantID   uuid.UUID
	PropertyID uuid.UUID
}

type ListUnitRentBalancesAsOfRow struct {
	UnitID  uuid.UUID
	Balance moneyfmt.Money
}

// ListUnitRentBalancesAsOf gives each unit's rent-account balance using only
// entries posted before the cutoff (exclusive). Called twice by the NOTE:2
// arrears/advance derivation — once with the previous period's end as
// cutoff, once with this period's end — so the caller can diff the two
// balances into "cleared" / "carried" / "new" arrears, and FIFO-derive
// advance months from a positive balance at the later cutoff. A positive
// balance is money owed (arrears); a negative balance is a credit (advance).
func (q *Queries) ListUnitRentBalancesAsOf(ctx context.Context, arg ListUnitRentBalancesAsOfParams) ([]ListUnitRentBalancesAsOfRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnitRentBalancesAsOf, arg.AsOf, arg.TenantID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnitRentBalancesAsOfRow{}
	for rows.Next() {
		var i ListUnitRentBalancesAsOfRow
		if err := rows.Scan(&i.UnitID, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReceiptCounter = `-- name: LockReceiptCounter :one
SELECT next_no FROM receipt_counters
WHERE tenant_id = $1 AND property_id = $2
FOR UPDATE
`

type LockReceiptCounterParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
}

// LockReceiptCounter takes the property's counter row lock for the rest of
// the transaction (SELECT ... FOR UPDATE, not MAX()+1), so two concurrent
// postings for the same property can never read the same next_no.
func (q *Queries) LockReceiptCounter(ctx context.Context, arg LockReceiptCounterParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lockReceiptCounter, arg.TenantID, arg.PropertyID)
	var next_no int64
	err := row.Scan(&next_no)
	return next_no, err
}

const upsertPropertyMeterReading = `-- name: UpsertPropertyMeterReading :exec
INSERT INTO property_meter_readings (tenant_id, property_id, period, previous_reading, current_reading, recorded_by, reading_date)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (property_id, period) DO UPDATE
SET previous_reading = EXCLUDED.previous_reading, current_reading = EXCLUDED.current_reading,
    recorded_by = EXCLUDED.recorded_by, reading_date = EXCLUDED.reading_date
`

type UpsertPropertyMeterReadingParams struct {
	TenantID        uuid.UUID
	PropertyID      uuid.UUID
	Period          time.Time
	PreviousReading *moneyfmt.Money
	CurrentReading  moneyfmt.Money
	RecordedBy      uuid.UUID
	ReadingDate     time.Time
}

func (q *Queries) UpsertPropertyMeterReading(ctx context.Context, arg UpsertPropertyMeterReadingParams) error {
	_, err := q.db.ExecContext(ctx, upsertPropertyMeterReading,
		arg.TenantID,
		arg.PropertyID,
		arg.Period,
		arg.PreviousReading,
		arg.CurrentReading,
		arg.RecordedBy,
		arg.ReadingDate,
	)
	return err
}

const upsertReportNotes = `-- name: UpsertReportNotes :exec
INSERT INTO reports (tenant_id, property_id, period, totals, notes, generated_by)
VALUES ($1, $2, $3, '{}'::jsonb, $4, $5)
ON CONFLICT (property_id, period) DO UPDATE
SET notes = EXCLUDED.notes
`

type UpsertReportNotesParams struct {
	TenantID    uuid.UUID
	PropertyID  uuid.UUID
	Period      time.Time
	Notes       json.RawMessage
	GeneratedBy uuid.UUID
}

// UpsertReportNotes saves the period's NOTE: 2 lines, creating the row
// (with empty totals) if the report has not been generated yet.
func (q *Queries) UpsertReportNotes(ctx context.Context, arg UpsertReportNotesParams) error {
	_, err := q.db.ExecContext(ctx, upsertReportNotes,
		arg.TenantID,
		arg.PropertyID,
		arg.Period,
		arg.Notes,
		arg.GeneratedBy,
	)
	return err
}

const upsertReportTotals = `-- name: UpsertReportTotals :exec
INSERT INTO reports (tenant_id, property_id, period, totals, notes, generated_by)
VALUES ($1, $2, $3, $4, '[]'::jsonb, $5)
ON CONFLICT (property_id, period) DO UPDATE
SET totals = EXCLUDED.totals,
    generated_by = EXCLUDED.generated_by,
    generated_at = now()
`

type UpsertReportTotalsParams struct {
	TenantID    uuid.UUID
	PropertyID  uuid.UUID
	Period      time.Time
	Totals      json.RawMessage
	GeneratedBy uuid.UUID
}

// UpsertReportTotals records the totals snapshot when a report is
// generated, keeping any notes already saved.
func (q *Queries) UpsertReportTotals(ctx context.Context, arg UpsertReportTotalsParams) error {
	_, err := q.db.ExecContext(ctx, upsertReportTotals,
		arg.TenantID,
		arg.PropertyID,
		arg.Period,
		arg.Totals,
		arg.GeneratedBy,
	)
	return err
}

const voidReceipt = `-- name: VoidReceipt :exec
UPDATE receipts SET voided_at = now(), void_reason = $1
WHERE tenant_id = $2 AND payment_allocation_id = $3
`

type VoidReceiptParams struct {
	VoidReason          *string
	TenantID            uuid.UUID
	PaymentAllocationID *uuid.UUID
}

// VoidReceipt marks a receipt void when its allocation is reversed. The
// number is never reused and the row is never deleted — the PDF renders
// "VOID" over it instead.
func (q *Queries) VoidReceipt(ctx context.Context, arg VoidReceiptParams) error {
	_, err := q.db.ExecContext(ctx, voidReceipt, arg.VoidReason, arg.TenantID, arg.PaymentAllocationID)
	return err
}
