// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createToken = `-- name: CreateToken :exec

INSERT INTO tokens (hash, manager_id, expiry, scope)
VALUES ($1, $2, $3, $4)
`

type CreateTokenParams struct {
	Hash      []byte
	ManagerID uuid.UUID
	Expiry    time.Time
	Scope     string
}

// Tokens: activation / password-reset (system-design.txt 3.1, 4.4). Only
// the SHA-256 hash is stored. Not tenant-scoped.
func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.ExecContext(ctx, createToken,
		arg.Hash,
		arg.ManagerID,
		arg.Expiry,
		arg.Scope,
	)
	return err
}

const deleteAllTokensForManager = `-- name: DeleteAllTokensForManager :exec
DELETE FROM tokens
WHERE scope = $1 AND manager_id = $2
`

type DeleteAllTokensForManagerParams struct {
	Scope     string
	ManagerID uuid.UUID
}

func (q *Queries) DeleteAllTokensForManager(ctx context.Context, arg DeleteAllTokensForManagerParams) error {
	_, err := q.db.ExecContext(ctx, deleteAllTokensForManager, arg.Scope, arg.ManagerID)
	return err
}

const deleteTokensForManager = `-- name: DeleteTokensForManager :exec
DELETE FROM tokens
WHERE manager_id = $1
`

// DeleteTokensForManager removes every token a manager holds, whatever its
// scope: after a password reset, no outstanding link of any kind should
// still work.
func (q *Queries) DeleteTokensForManager(ctx context.Context, managerID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTokensForManager, managerID)
	return err
}
