// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: unit_qr_codes.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUnitQRCode = `-- name: CreateUnitQRCode :one

INSERT INTO unit_qr_codes (token, lease_id, unit_id, property_id, tenant_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, token, lease_id, unit_id, property_id, tenant_id, created_by, created_at, revoked_at, scan_count, last_scanned_at
`

type CreateUnitQRCodeParams struct {
	Token      string
	LeaseID    uuid.UUID
	UnitID     uuid.UUID
	PropertyID uuid.UUID
	TenantID   uuid.UUID
	CreatedBy  uuid.UUID
}

// Lease-bound unit QR codes (migration 000028). Tenant-scoped under RLS except
// ResolveUnitQRToken, which runs on the willcoll_admin pool (SELECT only)
// because the public scan endpoint has no tenant yet.
func (q *Queries) CreateUnitQRCode(ctx context.Context, arg CreateUnitQRCodeParams) (UnitQrCode, error) {
	row := q.db.QueryRowContext(ctx, createUnitQRCode,
		arg.Token,
		arg.LeaseID,
		arg.UnitID,
		arg.PropertyID,
		arg.TenantID,
		arg.CreatedBy,
	)
	var i UnitQrCode
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.LeaseID,
		&i.UnitID,
		&i.PropertyID,
		&i.TenantID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ScanCount,
		&i.LastScannedAt,
	)
	return i, err
}

const getActiveUnitQRCodeByLease = `-- name: GetActiveUnitQRCodeByLease :one
SELECT id, token, lease_id, unit_id, property_id, tenant_id, created_by, created_at, revoked_at, scan_count, last_scanned_at FROM unit_qr_codes
WHERE tenant_id = $1 AND lease_id = $2 AND revoked_at IS NULL
`

type GetActiveUnitQRCodeByLeaseParams struct {
	TenantID uuid.UUID
	LeaseID  uuid.UUID
}

// GetActiveUnitQRCodeByLease is the lease's live code, if it has one.
func (q *Queries) GetActiveUnitQRCodeByLease(ctx context.Context, arg GetActiveUnitQRCodeByLeaseParams) (UnitQrCode, error) {
	row := q.db.QueryRowContext(ctx, getActiveUnitQRCodeByLease, arg.TenantID, arg.LeaseID)
	var i UnitQrCode
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.LeaseID,
		&i.UnitID,
		&i.PropertyID,
		&i.TenantID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ScanCount,
		&i.LastScannedAt,
	)
	return i, err
}

const getUnitQRCodeByToken = `-- name: GetUnitQRCodeByToken :one
SELECT id, token, lease_id, unit_id, property_id, tenant_id, created_by, created_at, revoked_at, scan_count, last_scanned_at FROM unit_qr_codes
WHERE tenant_id = $1 AND token = $2
`

type GetUnitQRCodeByTokenParams struct {
	TenantID uuid.UUID
	Token    string
}

func (q *Queries) GetUnitQRCodeByToken(ctx context.Context, arg GetUnitQRCodeByTokenParams) (UnitQrCode, error) {
	row := q.db.QueryRowContext(ctx, getUnitQRCodeByToken, arg.TenantID, arg.Token)
	var i UnitQrCode
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.LeaseID,
		&i.UnitID,
		&i.PropertyID,
		&i.TenantID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ScanCount,
		&i.LastScannedAt,
	)
	return i, err
}

const incrementUnitQRScan = `-- name: IncrementUnitQRScan :execrows
UPDATE unit_qr_codes
SET scan_count = scan_count + 1, last_scanned_at = now()
WHERE tenant_id = $1 AND id = $2 AND revoked_at IS NULL
`

type IncrementUnitQRScanParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// IncrementUnitQRScan counts one scan of a live code. Zero rows means the
// code was revoked between the lookup and now.
func (q *Queries) IncrementUnitQRScan(ctx context.Context, arg IncrementUnitQRScanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, incrementUnitQRScan, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resolveUnitQRToken = `-- name: ResolveUnitQRToken :one
SELECT q.id, q.tenant_id, p.slug AS property_slug, u.unit_code,
       (q.revoked_at IS NULL AND l.status = 'active' AND p.deleted_at IS NULL) AS active
FROM unit_qr_codes q
INNER JOIN leases l ON l.id = q.lease_id
INNER JOIN units u ON u.id = q.unit_id
INNER JOIN properties p ON p.id = q.property_id
WHERE q.token = $1
`

type ResolveUnitQRTokenRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	PropertySlug string
	UnitCode     string
	Active       sql.NullBool
}

// ResolveUnitQRToken is the public scan lookup: token to the unit's pay URL
// parts, plus whether the code and its lease are still live. It joins only what
// a redirect needs and returns nothing about the tenant.
func (q *Queries) ResolveUnitQRToken(ctx context.Context, token string) (ResolveUnitQRTokenRow, error) {
	row := q.db.QueryRowContext(ctx, resolveUnitQRToken, token)
	var i ResolveUnitQRTokenRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertySlug,
		&i.UnitCode,
		&i.Active,
	)
	return i, err
}

const revokeUnitQRCodesForLease = `-- name: RevokeUnitQRCodesForLease :execrows
UPDATE unit_qr_codes
SET revoked_at = now()
WHERE tenant_id = $1 AND lease_id = $2 AND revoked_at IS NULL
`

type RevokeUnitQRCodesForLeaseParams struct {
	TenantID uuid.UUID
	LeaseID  uuid.UUID
}

// RevokeUnitQRCodesForLease retires the lease's live code. Zero rows means it
// had none (already revoked, or never generated), which is fine.
func (q *Queries) RevokeUnitQRCodesForLease(ctx context.Context, arg RevokeUnitQRCodesForLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeUnitQRCodesForLease, arg.TenantID, arg.LeaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
