// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: units.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (tenant_id, property_id, unit_code, meter_number, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, property_id, unit_code, meter_number, status, created_at, version
`

type CreateUnitParams struct {
	TenantID    uuid.UUID
	PropertyID  uuid.UUID
	UnitCode    string
	MeterNumber *string
	Status      string
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, createUnit,
		arg.TenantID,
		arg.PropertyID,
		arg.UnitCode,
		arg.MeterNumber,
		arg.Status,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.UnitCode,
		&i.MeterNumber,
		&i.Status,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const getUnit = `-- name: GetUnit :one
SELECT id, tenant_id, property_id, unit_code, meter_number, status, created_at, version FROM units
WHERE tenant_id = $1 AND id = $2
`

type GetUnitParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetUnit(ctx context.Context, arg GetUnitParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, getUnit, arg.TenantID, arg.ID)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PropertyID,
		&i.UnitCode,
		&i.MeterNumber,
		&i.Status,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const listUnitCodes = `-- name: ListUnitCodes :many
SELECT unit_code FROM units
WHERE tenant_id = $1 AND property_id = $2
`

type ListUnitCodesParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
}

// ListUnitCodes is every unit code on a property, for the bulk import to
// report clashes before it writes anything.
func (q *Queries) ListUnitCodes(ctx context.Context, arg ListUnitCodesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUnitCodes, arg.TenantID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var unit_code string
		if err := rows.Scan(&unit_code); err != nil {
			return nil, err
		}
		items = append(items, unit_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitsForProperty = `-- name: ListUnitsForProperty :many
SELECT count(*) OVER() AS total_records,
       units.id, units.tenant_id, units.property_id, units.unit_code, units.meter_number, units.status, units.created_at, units.version,
       active_lease.id AS lease_id,
       active_lease.tenant_name AS lease_tenant_name,
       active_lease.start_date AS lease_start_date,
       -- whether the lease has a live door-sticker code (migration 000028)
       COALESCE(EXISTS (
           SELECT 1 FROM unit_qr_codes q
           WHERE q.tenant_id = units.tenant_id AND q.lease_id = active_lease.id AND q.revoked_at IS NULL
       ), false)::bool AS has_qr
FROM units
LEFT JOIN leases active_lease
       ON active_lease.unit_id = units.id AND active_lease.status = 'active'
WHERE units.tenant_id = $1
  AND units.property_id = $2
  AND ($3::text IS NULL OR units.status = $3::text)
  AND ($4::text = '' OR EXISTS (
        SELECT 1
        FROM leases l
        LEFT JOIN lease_payers lp ON lp.lease_id = l.id
        WHERE l.unit_id = units.id
          AND l.status = 'active'
          AND (to_tsvector('simple', l.tenant_name) @@ to_tsquery('simple', $4::text)
               OR to_tsvector('simple', lp.name) @@ to_tsquery('simple', $4::text))
      ))
ORDER BY
    CASE WHEN $5::text = 'unit_code' THEN units.unit_code END ASC,
    CASE WHEN $5::text = '-unit_code' THEN units.unit_code END DESC,
    CASE WHEN $5::text = 'created_at' THEN units.created_at END ASC,
    CASE WHEN $5::text = '-created_at' THEN units.created_at END DESC,
    units.id ASC
LIMIT $7 OFFSET $6
`

type ListUnitsForPropertyParams struct {
	TenantID    uuid.UUID
	PropertyID  uuid.UUID
	Status      *string
	TenantQuery string
	Sort        string
	PageOffset  int32
	PageLimit   int32
}

type ListUnitsForPropertyRow struct {
	TotalRecords    int64
	Unit            Unit
	LeaseID         *uuid.UUID
	LeaseTenantName *string
	LeaseStartDate  *time.Time
	HasQr           bool
}

// ListUnitsForProperty pages a property's units for the Units tab: each
// with its current (active) lease's tenant and start date, for the unit
// cards (system-design.txt 6.1). Optional filters:
//
//	status        vacant | occupied
//	tenant_query  a prefix tsquery built by the service layer (e.g.
//	              'wanj:* & jane:*'), matched against the active lease's
//	              tenant_name or any of its lease_payers' names. This is
//	              the API's one full-text search that earns its keep
//	              (Greenlight ch.9.5); the GIN indexes are in 000021.
func (q *Queries) ListUnitsForProperty(ctx context.Context, arg ListUnitsForPropertyParams) ([]ListUnitsForPropertyRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnitsForProperty,
		arg.TenantID,
		arg.PropertyID,
		arg.Status,
		arg.TenantQuery,
		arg.Sort,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnitsForPropertyRow{}
	for rows.Next() {
		var i ListUnitsForPropertyRow
		if err := rows.Scan(
			&i.TotalRecords,
			&i.Unit.ID,
			&i.Unit.TenantID,
			&i.Unit.PropertyID,
			&i.Unit.UnitCode,
			&i.Unit.MeterNumber,
			&i.Unit.Status,
			&i.Unit.CreatedAt,
			&i.Unit.Version,
			&i.LeaseID,
			&i.LeaseTenantName,
			&i.LeaseStartDate,
			&i.HasQr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const propertyIsActive = `-- name: PropertyIsActive :one

SELECT EXISTS (
    SELECT 1 FROM properties
    WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
)
`

type PropertyIsActiveParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// Units (system-design.txt 3.2). Tenant-scoped under RLS.
// PropertyIsActive guards every write that takes a property_id: the FK
// check ignores RLS, and archived properties (000019) take no new units.
func (q *Queries) PropertyIsActive(ctx context.Context, arg PropertyIsActiveParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, propertyIsActive, arg.TenantID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setUnitStatus = `-- name: SetUnitStatus :exec
UPDATE units
SET status = $1, version = version + 1
WHERE tenant_id = $2 AND id = $3
`

type SetUnitStatusParams struct {
	Status   string
	TenantID uuid.UUID
	ID       uuid.UUID
}

// SetUnitStatus is the only way a unit's status changes: occupied when a
// lease starts (or is reactivated), vacant when it's terminated, in the
// same transaction as that lease write (data.LeaseModel). It bumps version
// so a unit edit based on the old row gets an edit conflict.
func (q *Queries) SetUnitStatus(ctx context.Context, arg SetUnitStatusParams) error {
	_, err := q.db.ExecContext(ctx, setUnitStatus, arg.Status, arg.TenantID, arg.ID)
	return err
}

const updateUnit = `-- name: UpdateUnit :one
UPDATE units
SET unit_code = $1,
    meter_number = $2,
    version = version + 1
WHERE tenant_id = $3 AND id = $4 AND version = $5
RETURNING version
`

type UpdateUnitParams struct {
	UnitCode    string
	MeterNumber *string
	TenantID    uuid.UUID
	ID          uuid.UUID
	Version     int32
}

// UpdateUnit: optimistic concurrency; zero rows means the version moved on.
// status is deliberately not settable here: it follows the unit's lease
// (SetUnitStatus), so a manual edit can never contradict the lease record.
func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, updateUnit,
		arg.UnitCode,
		arg.MeterNumber,
		arg.TenantID,
		arg.ID,
		arg.Version,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}
