// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: water.sql

package sqlc

import (
	"context"
	"time"

	"github.com/codercollo/willcoll/backend/pkg/moneyfmt"
	"github.com/google/uuid"
)

const listWaterGrid = `-- name: ListWaterGrid :many

SELECT
    u.id AS unit_id,
    u.unit_code,
    COALESCE(l.tenant_name, '')::text AS tenant_name,
    wr.id AS reading_id,
    (wr.id IS NOT NULL)::boolean AS has_reading,
    COALESCE(wr.previous_reading, prev.current_reading, 0)::numeric(12,2) AS previous_reading,
    COALESCE(wr.current_reading, 0)::numeric(12,2) AS current_reading,
    COALESCE(wr.units_consumed, 0)::numeric(12,2) AS units_consumed,
    COALESCE(wr.rate_snapshot, 0)::numeric(12,2) AS rate,
    COALESCE(wr.amount, 0)::numeric(12,2) AS amount,
    COALESCE(wr.locked, false)::boolean AS locked,
    COALESCE(b.balance, 0)::numeric(12,2) AS prior_balance
FROM units u
LEFT JOIN LATERAL (
    SELECT tenant_name FROM leases
    WHERE unit_id = u.id AND status = 'active'
    LIMIT 1
) l ON true
LEFT JOIN water_readings wr ON wr.unit_id = u.id AND wr.period = $1
LEFT JOIN LATERAL (
    SELECT p.current_reading FROM water_readings p
    WHERE p.unit_id = u.id AND p.period < $1
    ORDER BY p.period DESC
    LIMIT 1
) prev ON true
LEFT JOIN LATERAL (
    SELECT ub.balance FROM unit_ledger_balances ub
    WHERE ub.unit_id = u.id AND ub.type = 'WATER'
) b ON true
WHERE u.tenant_id = $2 AND u.property_id = $3 AND u.status = 'occupied'
ORDER BY u.unit_code
`

type ListWaterGridParams struct {
	Period     time.Time
	TenantID   uuid.UUID
	PropertyID uuid.UUID
}

type ListWaterGridRow struct {
	UnitID          uuid.UUID
	UnitCode        string
	TenantName      string
	ReadingID       *uuid.UUID
	HasReading      bool
	PreviousReading moneyfmt.Money
	CurrentReading  moneyfmt.Money
	UnitsConsumed   moneyfmt.Money
	Rate            moneyfmt.Money
	Amount          moneyfmt.Money
	Locked          bool
	PriorBalance    moneyfmt.Money
}

// Water billing (system-design.txt 3.9). water_readings rows are drafts
// (locked = false) until a run locks them; only then are they charged.
// Balances are never stored: the grid reads the current derived balance and
// an invoice recomputes "previous balance B/F" from ledger entries created
// strictly before the reading's locked_at, so it can be re-rendered at any
// time without a stored PDF.
// ListWaterGrid is the draft grid: one row per occupied unit, with its
// saved reading for the period (if any), last period's closing reading as
// the default "previous", and the unit's current WATER balance.
func (q *Queries) ListWaterGrid(ctx context.Context, arg ListWaterGridParams) ([]ListWaterGridRow, error) {
	rows, err := q.db.QueryContext(ctx, listWaterGrid, arg.Period, arg.TenantID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWaterGridRow{}
	for rows.Next() {
		var i ListWaterGridRow
		if err := rows.Scan(
			&i.UnitID,
			&i.UnitCode,
			&i.TenantName,
			&i.ReadingID,
			&i.HasReading,
			&i.PreviousReading,
			&i.CurrentReading,
			&i.UnitsConsumed,
			&i.Rate,
			&i.Amount,
			&i.Locked,
			&i.PriorBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaterInvoices = `-- name: ListWaterInvoices :many
SELECT
    wr.unit_id,
    u.unit_code,
    COALESCE(l.tenant_name, '')::text AS tenant_name,
    wr.period,
    wr.reading_date,
    wr.previous_reading,
    wr.current_reading,
    COALESCE(wr.units_consumed, 0)::numeric(12,2) AS units_consumed,
    wr.rate_snapshot AS rate,
    COALESCE(wr.amount, 0)::numeric(12,2) AS amount,
    COALESCE((
        SELECT SUM(CASE le.direction WHEN 'DEBIT' THEN le.amount ELSE -le.amount END)
        FROM ledger_entries le
        INNER JOIN ledger_accounts la ON la.id = le.ledger_account_id
        WHERE la.tenant_id = $1
          AND la.unit_id = wr.unit_id
          AND la.type = 'WATER'
          AND le.created_at < wr.locked_at
    ), 0)::numeric(12,2) AS prior_balance
FROM water_readings wr
INNER JOIN units u ON u.id = wr.unit_id
LEFT JOIN LATERAL (
    SELECT tenant_name FROM leases
    WHERE unit_id = wr.unit_id AND start_date < (wr.period + interval '1 month')
    ORDER BY start_date DESC
    LIMIT 1
) l ON true
WHERE wr.tenant_id = $1
  AND u.property_id = $2
  AND wr.period = $3
  AND wr.locked = true
  AND ($4::uuid IS NULL OR wr.unit_id = $4::uuid)
ORDER BY u.unit_code
`

type ListWaterInvoicesParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
	Period     time.Time
	UnitID     *uuid.UUID
}

type ListWaterInvoicesRow struct {
	UnitID          uuid.UUID
	UnitCode        string
	TenantName      string
	Period          time.Time
	ReadingDate     time.Time
	PreviousReading moneyfmt.Money
	CurrentReading  moneyfmt.Money
	UnitsConsumed   moneyfmt.Money
	Rate            moneyfmt.Money
	Amount          moneyfmt.Money
	PriorBalance    moneyfmt.Money
}

// ListWaterInvoices is the data for every billed unit's water bill in a
// period. The customer is the lease that started most recently on or before
// the end of the period; prior_balance is the WATER balance before the run.
func (q *Queries) ListWaterInvoices(ctx context.Context, arg ListWaterInvoicesParams) ([]ListWaterInvoicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listWaterInvoices,
		arg.TenantID,
		arg.PropertyID,
		arg.Period,
		arg.UnitID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWaterInvoicesRow{}
	for rows.Next() {
		var i ListWaterInvoicesRow
		if err := rows.Scan(
			&i.UnitID,
			&i.UnitCode,
			&i.TenantName,
			&i.Period,
			&i.ReadingDate,
			&i.PreviousReading,
			&i.CurrentReading,
			&i.UnitsConsumed,
			&i.Rate,
			&i.Amount,
			&i.PriorBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaterReadingsForRun = `-- name: ListWaterReadingsForRun :many
SELECT wr.id, wr.unit_id, u.unit_code, COALESCE(wr.amount, 0)::numeric(12,2) AS amount, wr.locked
FROM water_readings wr
INNER JOIN units u ON u.id = wr.unit_id
WHERE wr.tenant_id = $1 AND u.property_id = $2 AND wr.period = $3
ORDER BY u.unit_code
`

type ListWaterReadingsForRunParams struct {
	TenantID   uuid.UUID
	PropertyID uuid.UUID
	Period     time.Time
}

type ListWaterReadingsForRunRow struct {
	ID       uuid.UUID
	UnitID   uuid.UUID
	UnitCode string
	Amount   moneyfmt.Money
	Locked   bool
}

// ListWaterReadingsForRun is every reading of the property's period, the
// input to a run.
func (q *Queries) ListWaterReadingsForRun(ctx context.Context, arg ListWaterReadingsForRunParams) ([]ListWaterReadingsForRunRow, error) {
	rows, err := q.db.QueryContext(ctx, listWaterReadingsForRun, arg.TenantID, arg.PropertyID, arg.Period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWaterReadingsForRunRow{}
	for rows.Next() {
		var i ListWaterReadingsForRunRow
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.UnitCode,
			&i.Amount,
			&i.Locked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWaterReading = `-- name: LockWaterReading :execrows
UPDATE water_readings
SET locked = true, locked_at = now()
WHERE tenant_id = $1 AND id = $2 AND locked = false
`

type LockWaterReadingParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// LockWaterReading locks a draft as part of a run. Zero rows affected means
// it was already locked.
func (q *Queries) LockWaterReading(ctx context.Context, arg LockWaterReadingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockWaterReading, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertWaterReading = `-- name: UpsertWaterReading :one
INSERT INTO water_readings (
    tenant_id, unit_id, period, previous_reading, current_reading, rate_snapshot, recorded_by, reading_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (unit_id, period) DO UPDATE
SET previous_reading = EXCLUDED.previous_reading,
    current_reading = EXCLUDED.current_reading,
    rate_snapshot = EXCLUDED.rate_snapshot,
    recorded_by = EXCLUDED.recorded_by,
    reading_date = EXCLUDED.reading_date
WHERE water_readings.locked = false
RETURNING id
`

type UpsertWaterReadingParams struct {
	TenantID        uuid.UUID
	UnitID          uuid.UUID
	Period          time.Time
	PreviousReading moneyfmt.Money
	CurrentReading  moneyfmt.Money
	RateSnapshot    moneyfmt.Money
	RecordedBy      uuid.UUID
	ReadingDate     time.Time
}

// UpsertWaterReading saves a draft. The WHERE on the conflict arm makes a
// locked reading immutable: zero rows (sql.ErrNoRows) means it is locked.
// Callers verify the unit belongs to the property first.
func (q *Queries) UpsertWaterReading(ctx context.Context, arg UpsertWaterReadingParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, upsertWaterReading,
		arg.TenantID,
		arg.UnitID,
		arg.Period,
		arg.PreviousReading,
		arg.CurrentReading,
		arg.RateSnapshot,
		arg.RecordedBy,
		arg.ReadingDate,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
